### ISSUE TITLE
Keepalive processing needs two timers

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.golang#1]
migrated from Bugzilla [#485186](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485186)
status ASSIGNED severity _normal_ in component _MQTT-Go_ for _1.2_
Reported in version _unspecified_ on platform _All_
Assigned to: Al Stockdill-Mander

On 2016-01-04 21:58:22 -0500, Che-Wei Kuo wrote:

> (When I typed the keyword "Keepalive" in the summary field, I found several same topics.)
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=442683 MQTT-C
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=442691 MQTT-Java
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=442692 MQTT-JS
> 
> In MQTT-Go, lastContact (in ping.go) is used for both ibound and obound messages (in net.go).

**Comment by rcadena** [comment]
Anyone assigned to this issue? It looked assigned on bugzilla.  Would be happy to take it on.

**Comment by alsm** [comment]
It's not currently being worked on, please feel free to get involved :)
