### ISSUE TITLE
Trouble Creating Mocks For Testing

### ISSUE THREAD

**Issue by EricMaibach** [eclipse/paho.mqtt.golang#107]
I am trying to write unit tests for my project that is using this library.  For my unit tests I need to mock out the mqtt connection, so I tried to create a mock client object the implement the Client interface.  However many of the methods in the Client interface return a Token interface object.  The Token interface specifies a private method of flowComplete.  This makes it impossible to create a mock object that implements the Token interface, which makes it impossible to create a mock object that implements the Client interface.

Is there some other way to make this work for testing that I am missing?

Thank You

**Comment by smotes** [comment]
Ditto.
