### ISSUE TITLE
panic: interface conversion: mqtt.Token is nil, not *mqtt.UnsubscribeToken

### ISSUE THREAD

**Issue by liaoliaopro** [eclipse/paho.mqtt.golang#112]
panic: interface conversion: mqtt.Token is nil, not *mqtt.UnsubscribeToken

goroutine 9686 [running]:
github.com/eclipse/paho%2emqtt%2egolang.alllogic(0xc042d87500)
	E:/home/work/src/github.com/eclipse/paho.mqtt.golang/net.go:214 +0x18c8
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	E:/home/work/src/github.com/eclipse/paho.mqtt.golang/client.go:265 +0xac7

-------------------------------------------------------------
src code where triggers panic:
			case *packets.UnsubackPacket:
				DEBUG.Println(NET, "received unsuback, id:", m.MessageID)
				token := c.getToken(m.MessageID).(*UnsubscribeToken)
				token.flowComplete()
				c.freeID(m.MessageID)

**Comment by alsm** [comment]
I'm closing this in favour of the ongoing discussion in #115 thanks for reporting the issue
