### ISSUE TITLE
Downgrade protocol version on reconnect even if first connection was successful?

### ISSUE THREAD

**Issue by brocaar** [eclipse/paho.mqtt.golang#116]
Hi, currently I'm experiencing an issue where the MQTT client won't always reconnect after the MQTT broker has been restarted. Initially I was thinking https://github.com/eclipse/paho.mqtt.golang/issues/96 was the cause. However using the latest master, the problem is still persisting.

After enabling all the logging, I noticed the MQTT client **is** reconnecting, but the connection gets rejected. Then I noticed in the logs that the client switched the MQTT protocol from 3.1.1 to 3.1. I think this is caused by https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L316.

I guess since my code uses a blank ClientID, this might be accepted when using 3.1.1, but gets rejected when switching to 3.1.

Would it be an idea to set `c.options.protocolVersionExplicit` to `true` on the first successful connection? That way this protocol downgrading would not happen anymore after a successful connection is interrupted.

**Comment by alsm** [comment]
Your suggestion is something I think is worth looking at, but your issue is confusing. The first reconnect attempt when no version has been set will be at 3.1.1, only when that fails will it then try again at 3.1. Do you know why your first reconnect attempt is failing?

**Comment by brocaar** [comment]
I think this happens when the MQTT broker is temporarily unavailable, so
the client is making multiple attempts before the server comes back up. At
that point the client library has already downgraded the protocol version.

**Comment by alsm** [comment]
Right, understand, the latest commit should resolve this issue for you, it locks the protocol version level once we've successfully connected so any reconnects will be at the same version.

**Comment by brocaar** [comment]
Cheers for fixing this! 👍
