### ISSUE TITLE
Fail to work with emqttd load balancing

### ISSUE THREAD

**Issue by arthur-xie** [eclipse/paho.mqtt.golang#120]
The MQTT broker [emqttd](http://emqtt.io) has a load balancing feature, the document is [here](http://emqttd-docs.readthedocs.io/en/latest/advanced.html?highlight=%24share).

My sensor data handlers(multiple data consumers running on multiple machines) can subscribe to topic **$share/sensor/data/#** successfully, but cannot get any published(to topic, for example: **data/devId/slot**) message by sensor.

The code in file route.go:
```golang
func routeIncludesTopic(route, topic string) bool {
	return match(strings.Split(route, "/"), strings.Split(topic, "/"))
}
```
does not handle the emqttd tricky topic thing. For my application, I modify the function as:
```golang
func routeIncludesTopic(route, topic string) bool {
	routeSlice := strings.Split(route, "/")
	if len(routeSlice) > 1 {
		switch routeSlice[0] {
		case "$local", "$queue":
			routeSlice = routeSlice[1:]
		case "$share":
			if len(routeSlice) > 2 {
				routeSlice = routeSlice[2:]
			}
		}
	}
	return match(routeSlice, strings.Split(topic, "/"))
}
```
But I **do not know** it is or not a proper solution. Any advice? Thanks!

**Comment by alsm** [comment]
This is a non standard feature to allow subscribers to treat the subscription like a queue and the problem is that we register the full subscription string as the expected topic to see messages on. If you had a handler registered to the defaultMessageHandler you would see the messages there as they wouldn't match any other subscription. Your changes work, but I'm not sure how I'd want to integrate this support into the main client.

**Comment by arthur-xie** [comment]
@alsm Thanks!
The _defaultMessageHandler_ can only(right?) be set in the _ClientOptions_, it is not a ideal point in my application. I need to set the message handler after _NewClient_ (wrapped somewhere in my application code). After double checking the client code, I realized that _AddRoute_ method MUST be a better solution than my former code modification.

**Comment by jhaoheng** [comment]
@arthur-xie 
I try to use Mosquitto and it support this feature.
Then I use AddRoute to sub '$queue/topic' but not useful. Still can not get message. 

But i sub `$share/group/topic/#` and it is work. 
Whatever i use `client.Subscribe()` or `client.AddRoute()` , all are fine.

## verify
> use topic `$share/group/topic/#`
1. use `github.com/eclipse/paho.mqtt.golang` to sub topic
2. use `mosquitto_sub -t topic`
3. use mosquitto_pub to submit N diff-msg in the the time. (use same topic)
4. `github.com/eclipse/paho.mqtt.golang` and `mosquitto_sub` get diff-msg in the same time.

```
  TOPIC := "$share/group/topic/#"
  opts := MQTT.NewClientOptions().AddBroker(broker)
  opts.SetClientID(clientID)
  opts.SetUsername(username)
  opts.SetPassword(password)
  client := MQTT.NewClient(opts)

  if token := client.Connect(); token.Wait() && token.Error() != nil {
    fmt.Println(token.Error())
  }
  
  var wg sync.WaitGroup
  wg.Add(1)
  // client.AddRoute(TOPIC, func(client MQTT.Client, msg MQTT.Message) {
  //   fmt.Println(string(msg.Payload()))
  // })

  client.Subscribe(TOPIC, 0, nil)
  if token := client.Subscribe(TOPIC, 0, func(client MQTT.Client, msg MQTT.Message) {
    fmt.Println(string(msg.Payload()))
  }); token.Wait() && token.Error() != nil {
    fmt.Println(token.Error())
  }
  wg.Wait()
```
