### ISSUE TITLE
Data race on connect

### ISSUE THREAD

**Issue by manland** [eclipse/paho.mqtt.golang#121]
Hi, thanks to share this amazing lib!

I use it in [lorhammer](https://gitlab.com/itk.fr/lorhammer). Since the commit dd157a8d803ef8fae7c9af135689243afe8fcbec i have a lot of data race.

I use the lib like this [mqtt.go](https://gitlab.com/itk.fr/lorhammer/blob/master/src/tools/mqtt.go) and you can find a stack trace in [this pipeline](https://gitlab.com/itk.fr/lorhammer/-/jobs/20474365) (at the end).

Have you an idea on what happens ? I have made a mistake !?

I use golang 1.8 to build.

**Comment by alsm** [comment]
For some reason I moved the starting of the keepalive goroutine to prior to creating the channels it reads from. It seems that I got lucky with timing while testing and hadn't hit the data race. Should be resolved now, thanks for reporting.
