### ISSUE TITLE
IsConnected() is aways true when I stoped  mqtt server

### ISSUE THREAD

**Issue by kekemuyu** [eclipse/paho.mqtt.golang#131]
#connect the mqtt server in initial,and then stop the mqtt server,the status of IsConnected is aways true.Is that a bug?  I want to  reconnect the mqtt server automatically，how to do ？

**Comment by alsm** [comment]
It depends, if autoreconnect is enabled then the client will continue to report true for IsConnected() while it is attempting to reconnect. This is intentional behaviour and not a bug.
