### ISSUE TITLE
Calls that publish messages hang when buffers are full (QOS > 0)

### ISSUE THREAD

**Issue by abferm** [eclipse/paho.mqtt.golang#138]
Calls to functions that push to the obound and oboundP buffered channels (Publish, Subscribe, Unsubscribe) can fill the buffer while in the "reconnecting" state. When these buffers are full calls to these functions will hang indefinitely. Ideally the function should return a complete token with an error rather than hanging.

Suggested solution:
```
// Publish will publish a message with the specified QoS and content
// to the specified topic.
// Returns a token to track delivery of the message to the broker
func (c *client) Publish(topic string, qos byte, retained bool, payload interface{}) Token {
//...
	persistOutbound(c.persist, pub)
	select{
	case c.obound <- &PacketAndToken{p: pub, t: token}:
	// NOTE: using default may not work correctly when the channel is not buffered.
	//   This may be a case to always buffer the channel, or use another case with a
	//   short timeout. ex: case <- time.After(bufferTimeout):
	default:
		token.flowComplete()
		token.err = ErrBufferFull
	}
	return token
}
```

**Comment by abferm** [comment]
Could be considered to relate to #133, but the cause is different.

**Comment by alsm** [comment]
I'm not sure about this, the buffers are there to try and smooth out any blips in connectivity, why should your app need to know if we can continue to accept your Publishes and send them when we reconnect. I guess the question is what would the app do with the error? I'm not averse to doing what you suggest, just putting out some thoughts.
Would you be interested in offering a PR for this?

**Comment by abferm** [comment]
The core of the issue is you are offering an Asynchronous interface, but it can block in certain circumstances. I'm not sure my proposed solution is ideal, but can open a PR.

**Comment by alsm** [comment]
You are right, an asynchronous API that blocks seems wrong, it just comes into conflict with the intention to try and hide internal issues like connectivity, Your proposed change would be a change in behaviour so I'd probably wait a short while to merge it and do it in a new version release.

**Comment by Niondir** [comment]
I have some issues that my MQTT client stops working after few days. I also got blocking requests once.

The only thing I can say about it is, that I had no chance to log or debug this. But this issue could be he reason. Any fix would be very welcome. I will also try to use QoS 0 to see if I run into the same issues.

**Comment by ovaltzer** [comment]
Hey there,
Are there any news about this issue?

**Comment by alsm** [comment]
I would recommend starting with QoS 0 messages and moving up from there, the fundamental problem behind this issue is not solvable with the current design of the client code.

**Comment by ovaltzer** [comment]
Will Qos 0 make the consumer code avoid hanging for sure ?
