### ISSUE TITLE
Subscribing in a message handler causes the client to block

### ISSUE THREAD

**Issue by jasalisbury** [eclipse/paho.mqtt.golang#142]
Calls to subscribe inside of a message handler callback block. It may have something to do with the message handler because calls to subscribe without a message handler do not block. This behavior was introduced sometime between tag v1.0.0 and v1.1.0. Gist that displays the issue https://gist.github.com/jasalisbury/ce8f62657857ba5776fbe0e46d64e385

**Comment by alsm** [comment]
This should have been resolved by PR #139

**Comment by jasalisbury** [comment]
That fixes it. Thanks!
