### ISSUE TITLE
block at receiving a connack

### ISSUE THREAD

**Issue by iamcc** [eclipse/paho.mqtt.golang#143]
> 09-16 07:00:02.649 I/GoLog   (10607): [mqtt][D][pinger]   ping check 15
09-16 07:00:07.649 I/GoLog   (10607): [mqtt][D][pinger]   ping check 20
09-16 07:00:12.651 I/GoLog   (10607): [mqtt][D][pinger]   ping check 25
09-16 07:00:17.649 I/GoLog   (10607): [mqtt][D][pinger]   ping check 30
09-16 07:00:17.649 I/GoLog   (10607): [mqtt][D][pinger]   keepalive sending ping
09-16 07:00:22.650 I/GoLog   (10607): [mqtt][D][pinger]   ping check 5
09-16 07:00:23.227 I/GoLog   (10607): [mqtt][E][net]      incoming stopped with error read tcp 192.168.199.195:37582->: read: connection timed out
09-16 07:00:23.227 I/GoLog   (10607): [mqtt][E][net]      error triggered, stopping
09-16 07:00:23.227 I/GoLog   (10607): [mqtt] Connect Lost
09-16 07:00:23.227 I/GoLog   (10607): [mqtt][D][net]      outgoing stopped
09-16 07:00:23.227 I/GoLog   (10607): [mqtt][D][pinger]   keepalive stopped
09-16 07:00:23.227 I/GoLog   (10607): [mqtt][W][net]      logic stopped
09-16 07:00:23.228 I/GoLog   (10607): [mqtt][D][client]   enter reconnect
09-16 07:00:23.228 I/GoLog   (10607): [mqtt][D][client]   about to write new connect msg
09-16 07:00:23.236 I/GoLog   (10607): [mqtt][E][client]   dial tcp : connect: network is unreachable
09-16 07:00:23.236 I/GoLog   (10607): [mqtt][W][client]   failed to connect to broker, trying next
09-16 07:00:23.236 I/GoLog   (10607): [mqtt][D][client]   Reconnect failed, sleeping for 1 seconds
09-16 07:00:23.265 I/ReactNativeJS(10607): '[mqtt]', 'read tcp 192.168.199.195:37582->: read: connection timed out'
09-16 07:00:24.236 I/GoLog   (10607): [mqtt][D][client]   about to write new connect msg
09-16 07:00:24.237 I/GoLog   (10607): [mqtt][E][client]   dial tcp : connect: network is unreachable
09-16 07:00:24.237 I/GoLog   (10607): [mqtt][W][client]   failed to connect to broker, trying next
09-16 07:00:24.237 I/GoLog   (10607): [mqtt][D][client]   Reconnect failed, sleeping for 2 seconds
09-16 07:00:26.237 I/GoLog   (10607): [mqtt][D][client]   about to write new connect msg
09-16 07:00:26.238 I/GoLog   (10607): [mqtt][E][client]   dial tcp : connect: network is unreachable
09-16 07:00:26.238 I/GoLog   (10607): [mqtt][W][client]   failed to connect to broker, trying next
09-16 07:00:26.238 I/GoLog   (10607): [mqtt][D][client]   Reconnect failed, sleeping for 4 seconds
09-16 07:00:30.240 I/GoLog   (10607): [mqtt][D][client]   about to write new connect msg
09-16 07:00:30.314 I/GoLog   (10607): [mqtt][D][client]   socket connected to broker
09-16 07:00:30.314 I/GoLog   (10607): [mqtt][D][client]   Using MQTT 3.1.1 protocol
09-16 07:00:30.315 I/GoLog   (10607): [mqtt][D][net]      connect started

**Comment by alsm** [comment]
Sorry, it's not clear from the log the issue you're having. As it's been a while I'm going to close this, please open again if you're still having issues.

**Comment by phearme** [comment]
I have observed the exact same issue on my side. Extract from logs:

```
[INFO][2019-02-10T16:05:41Z][context=CONFIG_MANAGER] [client]   failed to connect to broker, trying next
[INFO][2019-02-10T16:05:41Z][context=CONFIG_MANAGER] [client]   Reconnect failed, sleeping for 2 seconds
[INFO][2019-02-10T16:05:43Z][context=MQTT] fetching new credentials for connection
[INFO][2019-02-10T16:05:43Z][context=CONFIG_MANAGER] [client]   about to write new connect msg
[INFO][2019-02-10T16:05:53Z][context=CONFIG_MANAGER] [client]   failed to connect to broker, trying next
[INFO][2019-02-10T16:05:53Z][context=CONFIG_MANAGER] [client]   Reconnect failed, sleeping for 4 seconds
[INFO][2019-02-10T16:05:57Z][context=MQTT] fetching new credentials for connection
[INFO][2019-02-10T16:05:57Z][context=CONFIG_MANAGER] [client]   about to write new connect msg
[INFO][2019-02-10T16:06:07Z][context=CONFIG_MANAGER] [client]   socket connected to broker
[INFO][2019-02-10T16:06:07Z][context=CONFIG_MANAGER] [client]   Using MQTT 3.1.1 protocol
[INFO][2019-02-10T16:06:07Z][context=CONFIG_MANAGER] [net]      connect started
```
I think this should be re-opened.
