### ISSUE TITLE
Message loss can happen when ClientOptions (password specifically) must change after disconnect

### ISSUE THREAD

**Issue by mtw-g** [eclipse/paho.mqtt.golang#147]
Background: client is connecting to Google's MQTT broker, which requires a signed JWT in the password field. From [the docs:](https://cloud.google.com/iot/docs/how-tos/credentials/jwts)

> When connecting over MQTT, the JWT must be set in the password field of the CONNECT message.

and

> The maximum lifetime of a token is 24 hours + skew.

With these constraints, and the design of the client API, I do not see a way re-use an existing client while changing options. (aside: the Java client as it allows you specify [options at connect time](http://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttAsyncClient.html#connect-org.eclipse.paho.client.mqttv3.MqttConnectOptions-); one can set a new password on a existing client) 

This leads to a situation where messages waiting to be published by the client can be lost. Example:

1. Client connects to MQTT broker
2. Client stores pending messages in memory store
3. JWT expires before client publishes messages and is disconnected from MQTT broker
4. given there is no way to specify a new password without calling NewClient, the existing client in step 1 is overwritten with the new client, wiping out pending messages in the Store.

It's entirely possible I am misusing the client API and there is a correct way to do what I want to do. If that's the case I'd certainly welcome enlightenment!

**Comment by alsm** [comment]
This is a side effect of my being overly cautious of allowing the options to be changed once the client was running, without considering that, in cases like this, you might need to change something like the password. I'm inclined to change things so that the clientoptions are directly editable and it's on the programmer not to do anything that causes a race. Thoughts?

**Comment by mtw-g** [comment]
In this case, I think the benefits of allowing client options (even possibly a subset of them) to be directly editable outweighs the risks it introduces.

**Comment by danielbprice** [comment]
I think I am about to have the same problem (also connecting to Google's MQTT broker).  Another possible solution here would be to start by whitelisting for _change while connected_ those attributes which really only pertain to connection setup, such as username and password.  I am fairly new to MQTT but that seems reasonably conservative and likely to avoid races to me.

**Comment by vaelen** [comment]
I opened #192 as a suggested way to resolve this issue without tearing down and recreating the client or making the options structure mutable.

**Comment by danielbprice** [comment]
I think this can now be closed.

**Comment by alsm** [comment]
Closing as #192 was merged
