### ISSUE TITLE
MQTT5 Go client library status

### ISSUE THREAD

**Issue by Eric-Ko-ConnectedLab** [eclipse/paho.mqtt.golang#149]
@alsm what is the status of the [v5 branch](https://github.com/eclipse/paho.mqtt.golang/tree/v5)
I apologize in advance if this is the wrong place to ask.

**Comment by alsm** [comment]
It's in active, but periodic, development. The packets library for v5 is mostly done, there is an example of a simple v5 client built on top of it in the `simple` directory, this very much requires the user to do a lot of the work and doesn't do much checking. I've started playing with ideas for a full client in my own fork, but nothing significant yet.
I was hoping to attract some interest so if you have and suggestions/feedback/PRs on what's already done, or ideas about the future development please get involved.

**Comment by alsm** [comment]
Current version visible here https://github.com/eclipse/paho.mqtt.golang/pull/237
