### ISSUE TITLE
crash in MQTT packet parser

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.golang#15]
migrated from Bugzilla [#475949](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475949)
status NEW severity *normal* in component *MQTT-Go* for *1.2*
Reported in version *v0.5* on platform *PC*
Assigned to: Al Stockdill-Mander

On 2015-08-26 11:59:14 -0400, Julien Vermillard wrote:

> if you try to parse a packet with the value "30" in hexa you receive a panic:
> 
> panic: runtime error: makeslice: len out of range [recovered]
> 	panic: runtime error: makeslice: len out of range
> 
> goroutine 8 [running]:
> testing.tRunner.func1(0xc8200902d0)
> 	/usr/local/go/src/testing/testing.go:450 +0x171
> git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets.(*PublishPacket).Unpack(0xc82001c420, 0x7f9fd1e7c648, 0xc820012310)
> 	/home/jvermillar/go/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets/publish.go:55 +0xd9
> git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets.ReadPacket(0x7f9fd1e7c648, 0xc8200122a0, 0x7f9fd1e7c698, 0xc82001c420, 0x0, 0x0)
> 	/home/jvermillar/go/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets/packets.go:126 +0x51e
> git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets.TestInvalidLen(0xc8200902d0)
> 	/home/jvermillar/go/src/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets/packets_test.go:127 +0x25c
> testing.tRunner(0xc8200902d0, 0x6fb568)
> 	/usr/local/go/src/testing/testing.go:456 +0x98
> created by testing.RunTests
> 	/usr/local/go/src/testing/testing.go:561 +0x86d
> 
> goroutine 1 [chan receive]:
> testing.RunTests(0x64f728, 0x6fb520, 0x5, 0x5, 0xc820053e01)
> 	/usr/local/go/src/testing/testing.go:562 +0x8ad
> testing.(*M).Run(0xc820053ef8, 0xc8200961e0)
> 	/usr/local/go/src/testing/testing.go:494 +0x70
> main.main()
> 	git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets/_test/_testmain.go:62 +0x116
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
> exit status 2
> FAIL	git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git/packets	0.005s
> 
> Faulty code:
> p.Payload = make([]byte, payloadLength)
> if the payloadLength is <0 we receive a go panic

On 2015-08-26 12:00:12 -0400, Julien Vermillard wrote:

> the unit tests for testing it (to put in packets_test.go
> 
> func TestInvalidLen(t *testing.T) {
> 	buff, err := hex.DecodeString("30")
> 	if err != nil {
> 		t.Fatalf("Error decoding hex packet: %s", err.Error())
> 	}
> 
> 	packetBytes := bytes.NewBuffer(buff)
> 	_, err = ReadPacket(packetBytes)
> 	if err != nil {
> 		t.Errorf("Must generate an error")
> 	}
> }

On 2015-08-26 12:18:25 -0400, Julien Vermillard wrote:

> type ControlPacket interface {
> 	Write(io.Writer) error
> 	Unpack(io.Reader)
> 	String() string
> 	Details() Details
> 	UUID() uuid.UUID
> }
> Unpack(io.Reader) should be able to return an error, or it will be quite difficult to fix this bug, WDYT?

**Comment by johanstokking** [comment]
We're facing this issue as well;

```
panic: runtime error: makeslice: len out of range

goroutine 135 [running]:
panic(0x3fd7a0, 0xc4201caba0)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho.mqtt.golang/packets.(*PublishPacket).Unpack(0xc4201d8a00, 0x663b20, 0xc4201e29a0)
    /Users/htdvisser/dev/go/src/github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho.mqtt.golang/packets/publish.go:53 +0xa6
github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho.mqtt.golang/packets.ReadPacket(0xc04480, 0xc42026e000, 0xc42026e000, 0xc04480, 0xc42026e000, 0x0)
    /Users/htdvisser/dev/go/src/github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho.mqtt.golang/packets/packets.go:119 +0x23b
github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho%2emqtt%2egolang.incoming(0xc42026c000)
    /Users/htdvisser/dev/go/src/github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho.mqtt.golang/net.go:86 +0x1d2
created by github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
    /Users/htdvisser/dev/go/src/github.com/TheThingsNetwork/ttn/vendor/github.com/eclipse/paho.mqtt.golang/client.go:260 +0xb8f
```

Seems https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/publish.go#L53 to me. Might be negative length?

Is #58 related?

**Comment by jl2005** [comment]
```
//Unpack decodes the details of a ControlPacket after the fixed
//header has been read
func (p *PublishPacket) Unpack(b io.Reader) {
	var payloadLength = p.FixedHeader.RemainingLength
	p.TopicName = decodeString(b)
	if p.Qos > 0 {
		p.MessageID = decodeUint16(b)
		payloadLength -= len(p.TopicName) + 4
	} else {
		payloadLength -= len(p.TopicName) + 2
	}
	p.Payload = make([]byte, payloadLength)
	b.Read(p.Payload)
}
```

This is because  `p.FixedHeader.RemainingLength` is 0, causing `payloadLength` to become a negative number.

**Comment by alsm** [comment]
Unpack on Publish packets now checks that the payloadLength is not less than 0, and if it is returns an error.
Returning an error from Unpack() is now part of the interface for control packets and the ReadPacket function receives and returns any error passed back from Unpack.

Rather than panicing any packet that causes this behaviour will now cause the client to disconnect.
