### ISSUE TITLE
Docs for SetKeepAlive on connection options are incorrect

### ISSUE THREAD

**Issue by natefinch** [eclipse/paho.mqtt.golang#152]
https://godoc.org/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetKeepAlive

The docs say "SetKeepAlive will set the amount of time **(in seconds)**"

I was looking at my callsite, which was 

```go
options.SetKeepAlive(60)
```

Looking at the comment, you'd think this would set the keep alive to 60 seconds.  But it does not. It sets the keepalive to 60 nanoseconds.... (which gets rounded down to 0, so no keepalive). That's kind of a big difference.

Remove "(in seconds)" from the doc string, or clarify that it will be rounded down to the nearest second... but don't say it's in seconds, because it's not.  It's a time.Duration, which is fine, but very different.

**Comment by alsm** [comment]
Sorry about that, must have been from when they were strictly seconds, SetPingTimeout was also wrong.
