### ISSUE TITLE
description about baseToken.WaitTimeout may be wrong

### ISSUE THREAD

**Issue by ZYNCMA** [eclipse/paho.mqtt.golang#155]
As describe at https://golang.org/pkg/time/#Duration, `time.After` takes a time in nanosecond. The description at https://github.com/eclipse/paho.mqtt.golang/blob/master/token.go#L63-L66 and https://godoc.org/github.com/eclipse/paho.mqtt.golang may be wrong.

Btw, I found the function won't return if I call `token.WaitTimeout(time.Millisecond)`. Any duration bigger than Millisecond hits the same issue. Have a look at this if willing :)

**Comment by alsm** [comment]
Have you got an example, I was just testing the WaitTimeout() and it seemed to operate correctly.

**Comment by alsm** [comment]
Btw, I've just updated the doc
