### ISSUE TITLE
Is the SubscribeToken still available after the mqtt server restarted?

### ISSUE THREAD

**Issue by ZYNCMA** [eclipse/paho.mqtt.golang#156]
Consider the situation described below:
1. connect to a mqtt server
2. subscribe to a topic through the connection
3. the mqtt server is down
4. the mqtt server is up again
5. publish a message to the topic subscribed before

The question is: How can I get the message via the subscription in step 2?

My code doesn't work in this situation. Both `WaitTimeout` and `Wait()` doesn't return.
``` go
choke := make(chan [2]string)
opt := mqtt.NewClientOptions()
opt.AddBroker(rule.Src)
opt.SetAutoReconnect(true)
opt.SetDefaultPublishHandler(func(client mqtt.Client, msg mqtt.Message) {
    choke <- [2]string{msg.Topic(), string(msg.Payload())}
})  
client := mqtt.NewClient(opt)
if token := client.Connect(); token.Wait() && token.Error() != nil {
    fmt.Printf("conncent to mqtt server[%s] failed: %v\n", rule.Dst, token.Error())
    w.Write([]byte(token.Error().Error()))
    return
}   
defer client.Disconnect(0)
fmt.Printf("connected to server[%s]\n", rule.Src)
for {
    //if token := client.Subscribe(rule.Topic, byte(0), nil); token.Wait() && token.Error() == nil {
    if token := client.Subscribe(rule.Topic, byte(0), nil); token.WaitTimeout(time.Millisecond) {
        break
    } else {
        fmt.Printf("subscribe to server[%s] on topic[%s] failed: %v\n", rule.Src, rule.Topic, token.Error())
    }   
}   

incoming := <-choke
fmt.Printf("RECEIVED TOPIC: %s MESSAGE: %s\n", incoming[0], incoming[1])
```
Hope somebody can take a look at this. 
Any suggestion is appreciated!

**Comment by alsm** [comment]
The default ClientOptions you get back from NewClientOptions have CleanSession set to true and AutoReconnect set to true. This is a bit of a dichotomy as although you'll automatically reconnect, every time you are disconnected the server will throw away your session (subscriptions, outstanding messages etc).

**Comment by ZYNCMA** [comment]
Setting CleanSession to false resolved my problem. Thanks @alsm a lot!
