### ISSUE TITLE
superfluous var

### ISSUE THREAD

**Issue by timhughes** [eclipse/paho.mqtt.golang#157]
https://github.com/eclipse/paho.mqtt.golang/blob/512dcaa501c1580ea8eccb062ba06cc0c2b78172/cmd/stdoutsub/main.go#L35

I may be wrong but I don't believe the variable `i` serves any purpose. 

I think the only place it is used is to assign 0 to it at https://github.com/eclipse/paho.mqtt.golang/blob/512dcaa501c1580ea8eccb062ba06cc0c2b78172/cmd/stdoutsub/main.go#L41

**Comment by alsm** [comment]
Thanks for reporting the problem.
