### ISSUE TITLE
The acknowledgement for incoming messages are sent even if the associated MessageHandler panics

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.golang#16]
migrated from Bugzilla [#469350](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469350)
status UNCONFIRMED severity _major_ in component _MQTT-Go_ for _1.2_
Reported in version _0.9_ on platform _Macintosh_
Assigned to: Al Stockdill-Mander

On 2015-06-04 02:50:04 -0400, Saikrishnan Ranganathan wrote:

> It looks like the acknowledgement for inbound QoS 1 and 2 messages are sent to the broker even if the MessageHandler associated with the topic panics. So when the client is next re-connected, any QoS 1 or 2 messages will NOT be redelivered by the broker.

**Comment by gleb-chipiga** [comment]
+1
