### ISSUE TITLE
Connection lost before Subscribe completed

### ISSUE THREAD

**Issue by rayjohnson** [eclipse/paho.mqtt.golang#162]
Not sure why I'm getting this failure - it dies in my Subscribe call.

MacBook-Pro:zap rayj$ ./zap subscribe --topic \$SYS/# 
DEBUG: 2017/12/04 15:52:53 client.go:164: [client]   Connect()
DEBUG: 2017/12/04 15:52:53 memstore.go:48: [store]    memorystore initialized
DEBUG: 2017/12/04 15:52:53 client.go:177: [client]   about to write new connect msg
DEBUG: 2017/12/04 15:52:56 client.go:180: [client]   socket connected to broker
DEBUG: 2017/12/04 15:52:56 client.go:187: [client]   Using MQTT 3.1.1 protocol
DEBUG: 2017/12/04 15:52:56 client.go:371: [net]      connect started
DEBUG: 2017/12/04 15:52:56 client.go:389: [net]      received connack
DEBUG: 2017/12/04 15:52:56 client.go:253: [client]   client is connected
WARN: 2017/12/04 15:52:56 memstore.go:137: [store]    memorystore wiped
DEBUG: 2017/12/04 15:52:56 client.go:274: [client]   exit startClient
DEBUG: 2017/12/04 15:52:56 client.go:523: [client]   enter Subscribe
DEBUG: 2017/12/04 15:52:56 ping.go:26: [pinger]   keepalive starting
DEBUG: 2017/12/04 15:52:56 client.go:536: [client]   SUBSCRIBE: dup: false qos: 1 retain: false rLength: 0 MessageID: 0 topics: [$SYS/#]
DEBUG: 2017/12/04 15:52:56 net.go:219: [net]      logic started
DEBUG: 2017/12/04 15:52:56 net.go:222: [net]      logic waiting for msg on ibound
DEBUG: 2017/12/04 15:52:56 net.go:155: [net]      outgoing started
DEBUG: 2017/12/04 15:52:56 net.go:158: [net]      outgoing waiting for an outbound message
DEBUG: 2017/12/04 15:52:56 net.go:193: [net]      obound priority msg to write, type *packets.SubscribePacket
DEBUG: 2017/12/04 15:52:56 net.go:158: [net]      outgoing waiting for an outbound message
DEBUG: 2017/12/04 15:52:56 ping.go:156: [pinger]   keepalive sending ping
DEBUG: 2017/12/04 15:52:56 client.go:544: [client]   exit Subscribe
DEBUG: 2017/12/04 15:52:56 net.go:117: [net]      incoming started
DEBUG: 2017/12/04 15:52:56 ping.go:93: [net]      resetting ping timer
CRITICAL: 2017/12/04 15:52:56 ping.go:111: [pinger]   pingresp not received, disconnecting
ERROR: 2017/12/04 15:52:56 net.go:321: [net]      error triggered, stopping
DEBUG: 2017/12/04 15:52:56 net.go:161: [net]      outgoing stopped
DEBUG: 2017/12/04 15:52:56 net.go:141: [net]      incoming stopped
WARN: 2017/12/04 15:52:56 net.go:309: [net]      logic stopped
Could not subscribe: Connection lost before Subscribe completed
WARN: 2017/12/04 15:52:56 client.go:409: [client]   Disconnect() called but not connected (disconnected/reconnecting)
DEBUG: 2017/12/04 15:52:56 client.go:456: In disconnect and stop channel is already closed
DEBUG: 2017/12/04 15:52:56 client.go:475: [client]   disconnected
DEBUG: 2017/12/04 15:52:56 memstore.go:126: [store]    memorystore closed

**Comment by rayjohnson** [comment]
Well, I moved from the 1.1.0 tag to master and everything works now.  So it must have been a bug and it must have already been fixed!  :)

Maybe you are ready to ship 1.1.1?

**Comment by alsm** [comment]
Interesting, I wonder what it was, I've just committed a couple of changes if it all looks good next week I think yeah I'll cut 1.1.1

**Comment by xaque208** [comment]
This looks to be an issue for me on 64d8663555716776a6fa8dbadcb032caf06e0a86.

**Comment by LourdesMoran** [comment]
This keeps happening for me also with version 1.1.1
