### ISSUE TITLE
Keep getting pingresp not received, disconnecting

### ISSUE THREAD

**Issue by rayjohnson** [eclipse/paho.mqtt.golang#163]
My app runs a bit for like 30 sec to a minute.  I then get this:
```
CRITICAL: 2017/12/06 00:22:01 ping.go:60: [pinger]   pingresp not received, disconnecting
ERROR: 2017/12/06 00:22:01 net.go:324: [net]      error triggered, stopping
```

Looking at the logs of the mqtt server I see this:
```
1512547930: Sending PUBLISH to ray_mac2 (d0, q0, r0, m0, '$SYS/broker/publish/bytes/received', ... (5 bytes))
1512547930: Sending PUBLISH to ray_mac2 (d0, q0, r0, m0, '$SYS/broker/publish/bytes/sent', ... (5 bytes))
1512547931: Received PINGREQ from ray_mac2
1512547931: Sending PINGRESP to ray_mac2
1512547931: Socket error on client ray_mac2, disconnecting.
```

So it looks like the server is sending the ping back - but the lib panics.  Seems to panic rather quickly as well.

I should mention the app is doing a subscribe and it happily receives replies from the server up until it dies on the ping response.

This is a critical issue as it is not good to have an app that only works for 30 seconds...  :(

**Comment by rayjohnson** [comment]
Ug.  I just figured this out.  I was following the example in cmd/stdoutsub/main.go

which was doing this:
	connOpts := &MQTT.ClientOptions{
instead of this:
       connOpts := MQTT.NewClientOptions()

I was also not setting PingTimeout - so the timeout was zero!  Bang head on the table!

You might update that example so some other poor fool doesn't make the same mistake as me...

**Comment by alsm** [comment]
Will do, thanks for reporting that
