### ISSUE TITLE
connect lost fast on success

### ISSUE THREAD

**Issue by JonesSun** [eclipse/paho.mqtt.golang#166]
Why I connect with broker on windows and it will break again, but no problem on Linux.
Is it possible to be a problem with client?

**Comment by alsm** [comment]
If the same code is working fine against one broker, and not against another, it's unlikely to be the client. If you have python installed on the windows system there is a reference v3 server implementation in the paho testing tools https://github.com/eclipse/paho.mqtt.testing/tree/master/interoperability
