### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by rayjohnson** [eclipse/paho.mqtt.golang#167]
Just wanted to say thanks for developing this library.  It is working really well for me!

I'm building this client on top of the library:
https://github.com/rayjohnson/zap
(It does what mosquitto_pub and mosquitto_pub does plus a little more.)

So far I have had very few issues with the library - great work and thanks!

**Comment by alsm** [comment]
Thanks, really appreciate that, cool looking app you've got there too.
