### ISSUE TITLE
Could we have a 1.1.1 release?

### ISSUE THREAD

**Issue by danielbprice** [eclipse/paho.mqtt.golang#168]
There are a bunch of useful looking bugfixes on master.  It would be really nice to have these as a blessed "release."  I'm using `dep` to manage dependencies and so it automatically selected 1.1.0 for me.  As a result I spent a bunch of time tracking down bugs which are perhaps already resolved.  Thanks!  In particular, the fix for #133 would be great to have.  Meanwhile I will update my `dep` config to follow `master`.

Thanks again, and happy new year.

**Comment by Hades32** [comment]
yes, please :+1: 
I really hate to pin a specific Git hash...

**Comment by danievanzyl** [comment]
any update when 1.1.1 will be released?

**Comment by alsm** [comment]
Done, finally. Thanks for waiting.
