### ISSUE TITLE
Data race in mqtt client

### ISSUE THREAD

**Issue by antlad** [eclipse/paho.mqtt.golang#170]
WARNING: DATA RACE
Write by goroutine 82:
  XXX/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1()
      XXX/vendor/github.com/eclipse/paho.mqtt.golang/client.go:240 +0x1603

Previous read by goroutine 60:
  XXX/vendor/github.com/eclipse/paho%2emqtt%2egolang.errorWatch()
      XXX/vendor/github.com/eclipse/paho.mqtt.golang/net.go:324 +0x4b

Goroutine 82 (running) created at:
  XXX/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect()
      XXX/vendor/github.com/eclipse/paho.mqtt.golang/client.go:277 +0x41e
  .....

Goroutine 60 (finished) created at:
  XXX/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1()
      XXX/vendor/github.com/eclipse/paho.mqtt.golang/client.go:267 +0x1bb0

**Comment by danielbprice** [comment]
I can confirm that I have seen this, or something close, involving errorWatch() too.

**Comment by alsm** [comment]
I wonder if that's because errorWatch() was run as a goroutine but not part of the workers syncGroup (and I don't know why it wasn't). I've just made a change to catch it returning as part of the waitgroup, hopefully this will remove this issue.

**Comment by danielbprice** [comment]
I have run a bunch of testing of this change (commit cd4337d9ef8b177236ef7abc7bc2677385c11381) and I have not seen the race recur.  I think that this can be resolved.

**Comment by alsm** [comment]
thanks 👍
