### ISSUE TITLE
 Error when reconnecting

### ISSUE THREAD

**Issue by Achenme** [eclipse/paho.mqtt.golang#172]
Create the default configuration used for the connection。But,Error when reconnecting

goroutine 2364 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost(0xc420343500, 0xef9040, 0xc42000e100)
github.com/eclipse/paho.mqtt.golang/client.go:421 +0x59
github.com/eclipse/paho%2emqtt%2egolang.alllogic(0xc420343500)
	vendor/github.com/eclipse/paho.mqtt.golang/net.go:262 +0x273b
created by ithub.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect
/github.com/eclipse/paho.mqtt.golang/client.go:338 +0x8a5
2017/12/27 20:14:50 exrights info map[]

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x73f421]

goroutine 2169 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect(0xc42083c000)
github.com/eclipse/paho.mqtt.golang/client.go:299 +0x611
created by hsl-l1/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost
ithub.com/eclipse/paho.mqtt.golang/client.go:425 +0xc6

**Comment by alsm** [comment]
Do you have some more details about your code, is it on github somewhere. I haven't seen anything like this with the default config in the tests.

**Comment by Achenme** [comment]
@alsm Thank you very much for your reply
here's my create mqtt code.
No message was received for a long time, and this error occurred.


`       

        opts := mqtt.NewClientOptions()
	opts.AddBroker(config.Default.Mqtt.Broker)
	opts.AddBroker(config.Default.Mqtt.Broker)
	opts.SetDefaultPublishHandler(func(client mqtt.Client, msg mqtt.Message) {
		s.quoteCh <- [2][]byte{[]byte(msg.Topic()), msg.Payload()}
	})

	client := mqtt.NewClient(opts)
	for {
		if token := client.Connect(); token.Wait() && token.Error() != nil {
			log.WithFields(log.Fields{"err": token.Error(), "name": s.bucket}).Warn("connet to mqtt server fail")
			time.Sleep(3 * time.Second)
			continue
		}
		break
	}`

**Comment by alsm** [comment]
This should hopefully have been resolved by https://github.com/eclipse/paho.mqtt.golang/pull/239
