### ISSUE TITLE
No data after reconnect

### ISSUE THREAD

**Issue by rayjohnson** [eclipse/paho.mqtt.golang#173]
I'm testing how my app behaves when the internet goes away.  I registered OnConnectionLost and OnConnect handlers and I can show the user that status which is great.  However, as I'm been testing
I see that I get no more data after I have reconnected.

Do I need to resubscribe to topics?  I had assumed it would re-enable the subscriptions.  Is there a way to tell if mqtt is currently honoring my subscriptions?

Ray

**Comment by rayjohnson** [comment]
Bugger - found the problem.  I was not setting CleanSession and CleanSession is true by default.
With CleanSession = true all subscriptions are removed on reconnect.  Setting CleanSession=false
go the subscriptions sending data again.

**Comment by alsm** [comment]
👍

**Comment by tsauerwein** [comment]
I was also struggling with this. I didn't want to use a clean session, so I am now doing the subscriptions in the connect handler:

```
  opts.SetOnConnectHandler(func(client mqtt.Client) {
    client.SubscribeMultiple(topics, handleMessage)
  })
```

**Comment by cecchisandrone** [comment]
I'm trying setting CleanSession = false but I still don't receive data if the server restarts or connection to it is lost. What else could be?

**Comment by boli2017** [comment]
> I'm trying setting CleanSession = false but I still don't receive data if the server restarts or connection to it is lost. What else could be?
you can try use NewClient function before your reconnection

func (h *Handler) ReStart() error{
	if h.client.IsConnected(){
		logger.Debug("connection is already exist")
		return nil
	}
	h.client = gomqtt.NewClient(h.clientOptions)
	err := h.Connect()

	h.wg.Add(1)

	if err != nil {
		logger.Debug(h.conf)
		logger.Error(err.Error())
	}
	return err
}
