### ISSUE TITLE
Invalid topic causes infinite hang on .Subscribe

### ISSUE THREAD

**Issue by sraimond83** [eclipse/paho.mqtt.golang#174]
If I have this topic the .Subscribe function hangs forever

```
....
topic = "a#"
if token := client.Subscribe(topic, byte(qos), nil); token.Wait() && token.Error() != nil {
    //never reached
    .....
}
//never reached
```

**Comment by alsm** [comment]
Can you try the stdoutsub program in `cmd` against your server and see what you get? For example if I run the following you can see that the subscribe fails
```

**Comment by sraimond83** [comment]
```
 .\stdoutsub.exe -server tcp://localhost:1884 -topic "a#"
Connected to tcp://localhost:1884
```
No exit from the tool, it's stuck exactly as it happens when I try to subscribe to that topic in my code.
I get the same behaviour if I connect to your test broker:

```
./stdoutsub -server tcp://iot.eclipse.org:1883 -topic "a#"
Connected to tcp://iot.eclipse.org:1883
```

**Comment by alsm** [comment]
Seems to be something to do with running on Windows?
Lines 38 and 39 of stdsubout/main.go are commented out logging lines, could you enable them, rerun this and paste the output?

**Comment by sraimond83** [comment]
Here's the output
```
go run main.go -server tcp://iot.eclipse.org:1883 -topic "a#"
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1.1 protocol
[net]      connect started
[net]      received connack
[client]   client is connected
[client]   exit startClient
Connected to tcp://iot.eclipse.org:1883
[client]   enter Subscribe
[pinger]   keepalive starting
[net]      outgoing started
[net]      outgoing waiting for an outbound message
[net]      logic started
[net]      logic waiting for msg on ibound
[net]      incoming started
[client]   SUBSCRIBE: dup: false qos: 1 retain: false rLength: 0 MessageID: 0 topics: [a#]
[client]   exit Subscribe
[net]      obound priority msg to write, type *packets.SubscribePacket
[net]      outgoing waiting for an outbound message
[net]      incoming stopped with error EOF
[net]      error triggered, stopping
[net]      outgoing stopped
[pinger]   keepalive stopped
panic: Connection lost before Subscribe completed

goroutine 7 [running]:
main.main.func1(0x7af240, 0xc04203ae00)
        c:/Workdir/src/github.com/eclipse/paho.mqtt.golang/cmd/stdoutsub/main.go:64 +0xec
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
        C:/Workdir/src/github.com/eclipse/paho.mqtt.golang/client.go:256 +0x889
exit status 2
```

**Comment by alsm** [comment]
I'm confused where the hang is occuring, that output is showing that the library lost it's connection (because of the bad topic name), and then panics. You're saying that after the panic the app doesn't exist back to the command line?

**Comment by sraimond83** [comment]
Actually it panics and exits. Sorry for mentioning that.
However, if the log lines are commented, there's no panic and no exiting.

**Comment by alsm** [comment]
To clear with logging enabled it panics and exits, with logging disabled it hangs? Could you try a building the stdoutsub app with -race to see if there is some race condition occuring? Unfortunately I don't have a windows system to test with and I don't see this problem in linux or macos.

**Comment by sraimond83** [comment]
Sorry for the late answer.

I just forced a rebuild of stdoutsub and now it panics everytime. No more hanging with your tool, logging or not.
Now, the strange part is it still hangs on my program, I'll try to enable logging and come back to you with my log.

**Comment by alsm** [comment]
Closing for no updates
