### ISSUE TITLE
Deadlock waiting for token if error occurs while writing message and QoS == 0

### ISSUE THREAD

**Issue by danielnelson** [eclipse/paho.mqtt.golang#185]
If `func (p *PublishPacket) Write(w io.Writer) error {` returns an error, call to `Wait` on the token returned from `client.Publish` will wait indefinitely.  All of my testing has been with QoS == 0, but this might affect other modes.

**steps**

1. Arrange for an error to be returned from `func (p *PublishPacket) Write(w io.Writer) error {`, this might be difficult, however there are a number of [potential errors](https://golang.org/src/crypto/tls/conn.go?s=29532:29575#L1006) you could attempt to trigger.  I just changed the source of this function to return an error for testing.

2. Run this test program and Wait will never return:
```go
package main

import (
	"fmt"
	"log"
	"os"

	paho "github.com/eclipse/paho.mqtt.golang"
)

func main() {
	paho.ERROR = log.New(os.Stdout, "E: ", 0)
	paho.CRITICAL = log.New(os.Stdout, "C: ", 0)
	paho.WARN = log.New(os.Stdout, "W: ", 0)
	paho.DEBUG = log.New(os.Stdout, "D: ", 0)

	opts := paho.NewClientOptions()
	opts.AddBroker("tcp://localhost:1883")
	opts.SetAutoReconnect(true)

	client := paho.NewClient(opts)
	client.Connect().Wait()

	token := client.Publish("test", byte(0), false, "test")
	token.Wait()
	if token.Error() != nil {
		fmt.Println(token.Error())
	}
}
```

**Comment by alsm** [comment]
Thanks for reporting this, it should be fixed in the above commit, I've changed the code to set an error on the token and complete it if there was an error sending the packet.
