### ISSUE TITLE
Client.Disconnect: Have the quiesce argument be a time.Duration

### ISSUE THREAD

**Issue by nesv** [eclipse/paho.mqtt.golang#186]
Going through the GoDoc for this package, it's not immediately clear that the `quiesce uint` argument to `mqtt.Client.Disconnect` should be the number of milliseconds `Disconnect` should wait before returning. This information can only be found when looking at the documentation for the unexported `client.Disconnect` method, [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L395).

Since `quiesce` gets converted to a `time.Duration` anyways, would it make sense for `quiesce uint` to become `quiesce time.Duration`?

If not, what about an additional method on the `Client` interface, `DisconnectWait`.

Failing either of those, I'd even be fine with an interface-level comment describing _how_ the value of `quiesce` is interpreted. For example:

```go
type Client interface {
	IsConnected() bool
	Connect() Token
        
        // Disconnect will end the connection with the server, but not before waiting
        // the specified number of milliseconds to wait for existing work to be
        // completed.
	Disconnect(quiesce uint)

	Publish(topic string, qos byte, retained bool, payload interface{}) Token
	Subscribe(topic string, qos byte, callback MessageHandler) Token
	SubscribeMultiple(filters map[string]byte, callback MessageHandler) Token
	Unsubscribe(topics ...string) Token
	AddRoute(topic string, callback MessageHandler)
}
```

**Comment by alsm** [comment]
Ahh, right, sorry about that, the latest commit should resolve this. Thanks for reporting it.

**Comment by nesv** [comment]
Thank you for adding in the documentation. :smile:
