### ISSUE TITLE
Client arbitrarily stops listening with "logic stopped"

### ISSUE THREAD

**Issue by mochi-co** [eclipse/paho.mqtt.golang#187]
After an indeterminate amount of time (sometimes immediately after connect, sometimes 8-10 hours), the client will post the warning "logic stopped" and continue publishing but not receiving. 

There are no other error messages or debug messages (although if anyone can advise me on a strategy for analysing the problem I will try any suggestions).

Obviously this is a bit of a problem because it prevents the client from ever being used in production. Experienced on Darwin/10.13.3 (17D47) using latest commit, connecting to both Mosquitto and VolantMQ. The latter appears to last longer.

**Comment by alsm** [comment]
Resolved on eclipse mattermost
