### ISSUE TITLE
Request - response example?

### ISSUE THREAD

**Issue by reejinbouk** [eclipse/paho.mqtt.golang#190]
Hi, please advice how to make mqqt working like request - response.
For example I request "topic/dev1" and catch message to this topic and send it as response.

Something like this:

`status := responseMqtt("topic/dev1")`

and functionMqtt() send request, got message (or wait Timeout). And if got message return it as response

Thanks!

**Comment by alsm** [comment]
MQTT as designed doesn't really support request/response, you would have to code it yourself around what is provided, for example you can't, in one operation, send a message to a topic and wait for a reply on that same topic.
