### ISSUE TITLE
Connection lost before Publish completed

### ISSUE THREAD

**Issue by amenzhinsky** [eclipse/paho.mqtt.golang#195]
Hi there!

Sometimes I'm getting `Connection lost before Publish completed` errors especially using slow connections like LTE, even though the reconnect feature is on, is it expected or not?

My workaround for now:
```
Retry:
	if t := conn.Publish(topic, 1, false, b); t.Wait() && t.Error() != nil {
		if t.Error().Error() == "Connection lost before Publish completed" {
			goto Retry
		}
		return t.Error()
	}
```

**Comment by alsm** [comment]
This is called in the cleanUp() function for the messageids which can happen when the connection is lost, if the session is persistent the message ids will still be valid on reconnect and we probably shouldn't do this.
