### ISSUE TITLE
Client.Disconnect: panic when not connected

### ISSUE THREAD

**Issue by nesv** [eclipse/paho.mqtt.golang#198]
# Synopsis

Attempting to call `Client.Disconnect` when the client is not connected results in the following panic:

```panic: close of nil channel

goroutine 1 [running]:
.../github.com/eclipse/paho%2emqtt%2egolang.(*client).closeStop(0xc42009b180)
        .../github.com/eclipse/paho.mqtt.golang/client.go:482 +0x12f
.../github.com/eclipse/paho%2emqtt%2egolang.(*client).disconnect(0xc42009b180)
        .../github.com/eclipse/paho.mqtt.golang/client.go:495 +0x2f
.../github.com/eclipse/paho%2emqtt%2egolang.(*client).Disconnect(0xc42009b180, 0x1f4)
        .../github.com/eclipse/paho.mqtt.golang/client.go:439 +0x1ce
```

This is on version v1.1.1.

# Details

I had forgotten to start my local MQTT broker before attempting to connect to it. I had hoped that by doing something like

```go
var client mqtt.Client // assume this is initialized
if token := client.Connect(); !token.Wait() {
        return token.Error()
}
```

near the beginning of my program, would have been enough to stall it until the client is connected. However, the `token.Wait()` call returned `true`, and my program sailed on through. When my program goes to do a graceful shutdown, it calls `client.Disconnect(...)`, and that's when the panic occurs.

For now, I'm calling `client.IsConnected()` after doing the above `if token := client.Connect()`, which is catching the instances it's not able to connect to the broker.

**Comment by nguyenthenguyen** [comment]
I'm getting the same issue. Relate to #171

**Comment by mlarva** [comment]
I also look for token.Error() != nil
```
  opts := MQTT.NewClientOptions()
  opts.AddBroker(broker)
  client = MQTT.NewClient(opts)
  token := client.Connect()

  for (token.Wait() && token.Error() != nil && client.IsConnected() == false) {
    time.Sleep(5 * time.Second)
    ErrorLog.Println("Trying to Connect to Broker", broker)
    token = client.Connect()
  }
  InfoLog.Println("Connected to Broker:",broker)
```
