### ISSUE TITLE
Add context.Context support

### ISSUE THREAD

**Issue by amenzhinsky** [eclipse/paho.mqtt.golang#200]
Hi there!

Probably we should think of adding use of contexts in the library since they're getting widespread (http, grpc, cli handlers) and right now we need to come up with workarounds that are not as efficient as they could be, like: 
```go
func contextToken(ctx context.Context, t mqtt.Token) error {
	done := make(chan struct{})
	go func() {
		// check token every second to release goroutine
		// until the token completes or ctx is canceled
		for !t.WaitTimeout(time.Second) {
			select {
			case <-ctx.Done():
				return
			default:
			}
		}
		close(done)
	}()
	select {
	case <-done:
		return t.Error()
	case <-ctx.Done():
		return ctx.Err()
	}
}
```

To avoid breaking changes I'd suggest adding at least `(Token) WaitContext(context.Context) error` plus shortcuts like `(Client) PublishContext(context.Context, ...) ...` that make use of it.

I can provide a draft PR a bit later.

**Comment by alsm** [comment]
I'm not sure that the Token model ended up providing the benefits I'd originally hoped for, really I should have made operations synchronous within the library then we wouldn't have needed them. I'm currently exploring ideas for a new library for the upcoming MQTT v5 standard both in the v5 branch here and my own https://github.com/alsm/paho.mqtt.golang/tree/v5 I hope that we can come up with a better design and that a v2 of this library would be with an API based on the MQTTv5 work.
If this is something you really need I'm more than happy to look at it, if you want to help with dev though I'd really appreciate some more eyes on the v5 stuff.

**Comment by alsm** [comment]
This will not be added for the current v3.1.1 client. I hope to make a new v3 client based on the v5 client which will provide such features.
