### ISSUE TITLE
Can't implement Token interface.

### ISSUE THREAD

**Issue by vaelen** [eclipse/paho.mqtt.golang#203]
I am trying to create unit tests which use a mock implementation of the mqtt.Client interface, but in order to do so I must also create a mock implementation of the mqtt.Token interface.  However, the mqtt.Token interface has an unexported method: `setError(error)`, which means that only types in the `mqtt` package can implement the interface.

My question is: would anyone object to me changing `setError(error)` to `SetError(error)`?

**Comment by estutzenberger** [comment]
I also just ran into this issue. My solution was to leave `setError` private and put it in it's own interface. I can see reasons to hide the `setError` function but... it makes it impossible to mock.
However, that function seems to be needed only by `tokenCompleter`. Locally the change I made looks like:

``` go
//Token defines the interface for the tokens used to indicate when
//actions have completed.
type Token interface {
    Wait() bool
    WaitTimeout(time.Duration) bool
    Error() error
}

type TokenErrorSetter interface {
    setError(error)
}

type tokenCompletor interface {
    Token
    TokenErrorSetter
    flowComplete()
}
```

**Comment by alsm** [comment]
Closing as linked PR was merged
