### ISSUE TITLE
logger options per connect

### ISSUE THREAD

**Issue by lelvisl** [eclipse/paho.mqtt.golang#204]
Hi!
Can you add support for logger per connect?

**Comment by ihsenCh** [comment]
you can add it yourself ! 
Go to packets/packets.go and add at line 113 ( after fh.unpack() )
fmt.Println("MessageType", fh.MessageType ) 

this will display the message exchanged between clients and broker and it will show the number of messages as 
        Connect     = 1
	Connack     = 2
	Publish     = 3
	Puback      = 4
	Pubrec      = 5
	Pubrel      = 6
	Pubcomp     = 7
	Subscribe   = 8
	Suback      = 9
	Unsubscribe = 10
	Unsuback    = 11
	Pingreq     = 12
	Pingresp    = 13
	Disconnect  = 14
