### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by DrmagicE** [eclipse/paho.mqtt.golang#211]
go version 1.9.2
paho.mqtt v1.1.1

I am not sure it is a bug.It does't reproduce every time.
Read at 0x00c04211a418 by goroutine 59:
  gotcpserver/vendor/github.com/eclipse/paho%2emqtt%2egolang.keepalive()
      C:/Users/Lifang/go/src/gotcpserver/vendor/github.com/eclipse/paho.mqtt.golang/ping.go:42 +0x23
d

Previous write at 0x00c04211a418 by goroutine 40:
  gotcpserver/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      C:/Users/Lifang/go/src/gotcpserver/vendor/github.com/eclipse/paho.mqtt.golang/client.go:377 +0
x149e

Goroutine 59 (running) created at:
  gotcpserver/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      C:/Users/Lifang/go/src/gotcpserver/vendor/github.com/eclipse/paho.mqtt.golang/client.go:374 +0
x1918

Goroutine 40 (running) created at:
  gotcpserver/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      C:/Users/Lifang/go/src/gotcpserver/vendor/github.com/eclipse/paho.mqtt.golang/client.go:465 +0
x115

**Comment by kei2100** [comment]
I have the same issue.

go version 1.11.0
paho.mqtt v1.1.1

**Comment by skillcoder** [comment]
```
==================
WARNING: DATA RACE
Read at 0x00c42019c798 by goroutine 39:
...github.com/eclipse/paho%2emqtt%2egolang.keepalive()
      ...github.com/eclipse/paho.mqtt.golang/ping.go:42 +0x22d

Previous write at 0x00c42019c798 by goroutine 20:
  ...github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      ...github.com/eclipse/paho.mqtt.golang/client.go:377 +0x12e6

Goroutine 39 (running) created at:
  ...github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      ...github.com/eclipse/paho.mqtt.golang/client.go:374 +0x1731

Goroutine 20 (running) created at:
  ...github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      ...github.com/eclipse/paho.mqtt.golang/client.go:465 +0x10e
==================
```
No recconect, connection lost program stop working
eclipse/paho.mqtt.golang dead project?
What mqtt client I must switch to?

**Comment by alsm** [comment]
Not dead, but I'm focusing on the v5 client and design with the intention to deprecate the current v3 client and provide a v3 client in the style of the new v5 one, please look at the latest v5 branch for details

**Comment by falknerdominik** [comment]
@alsm thanks for the info. If zou need any more info I could replicate this consistently on my Thinkpad T580 (Opensuse Tumbleweed) when disconnecting the network client (using WIFI)

```
==================
WARNING: DATA RACE
Read at 0x00c420176418 by goroutine 31:
  s7/train-data-publisher/vendor/github.com/eclipse/paho%2emqtt%2egolang.keepalive()
      /home/dominik/projects/go/src/s7/train-data-publisher/vendor/github.com/eclipse/paho.mqtt.golang/ping.go:42 +0x22d

Previous write at 0x00c420176418 by goroutine 26:
  s7/train-data-publisher/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      /home/dominik/projects/go/src/s7/train-data-publisher/vendor/github.com/eclipse/paho.mqtt.golang/client.go:377 +0x12e6

Goroutine 31 (running) created at:
  s7/train-data-publisher/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      /home/dominik/projects/go/src/s7/train-data-publisher/vendor/github.com/eclipse/paho.mqtt.golang/client.go:374 +0x1731

Goroutine 26 (running) created at:
  s7/train-data-publisher/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      /home/dominik/projects/go/src/s7/train-data-publisher/vendor/github.com/eclipse/paho.mqtt.golang/client.go:465 +0x10e
==================
```
