### ISSUE TITLE
IsConnected() method name is misleading

### ISSUE THREAD

**Issue by odedva** [eclipse/paho.mqtt.golang#218]
Hello,
After encountering issues while using the client in a bad network environment, I found out that the client's method IsConnected is returning true even in cases where the client did not manage to connect even once, and also while the client is in reconnecting mode.
I used it mainly for querying the client before publishing an event to the broker. I prefer to use the client only in the most reliable way where I know that it is actually "connected" (up to keep alive interval).
for this reason i thought that the method can help me but turns out it's not...
I suggest maybe to change the name to a different one, and anyway suggested a PR (#217) to add a method which return true iff the client is in connected state.
Another options is to expose the actual state of the client, maybe for "connecting" state. I can offer another PR as well, just let me know what you think is better.

**Comment by alsm** [comment]
Accepted PR
