### ISSUE TITLE
Panic from package files net.go and client.go

### ISSUE THREAD

**Issue by Strosel** [eclipse/paho.mqtt.golang#226]
When I receive, or send a message from/to my server I (sometimes, even though the messages are identical) get  the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1e68cc]

goroutine 228106 [running]:
github.com/eclipse/paho%2emqtt%2egolang.outgoing(0x11eee000)
	/Users/axpa/go/src/github.com/eclipse/paho.mqtt.golang/net.go:204 +0xb54
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect
	/Users/axpa/go/src/github.com/eclipse/paho.mqtt.golang/client.go:412 +0x1124
```

as you can see it doesn't trace back to my own project and would therefore seem to be a bug within the package itself

**Comment by ricardoatsouza** [comment]
The same started happening to me as well. I noticed it would happen when the incoming and outgoing of data is considerable big. In my case, I am speaking of a service that receives, on average, ~ 1k records per second (~ 1Mb/s) and produces ~ 20 k records per second (~ 10 MB/s).

This service in particular is subscribed to 1 topic (only one subscription), and has 10 producer that will send data to the same output topic.

First question that comes to my mind is: would this issue be related to a race condition?
Second is: when using multiple connections in the same service, are they sharing any resources?

**Comment by alsm** [comment]
Closing as PR merged
