### ISSUE TITLE
Problems running the examples in cmd directory

### ISSUE THREAD

**Issue by lg007** [eclipse/paho.mqtt.golang#227]
Hello,

I am having trouble running the examples found in the cmd directory. I am trying to connect to a MQTT broker using a secure websocket connection (URL is like wss://abc.defgh.com:443/mqtt) and I want to subscribe to some topics.

If I use the example "sample" (https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/sample), everything works as expected, so it is OK,

If I use the example "stdoutsub" (https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/stdoutsub/main.go), I get:

```
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1.1 protocol
[net]      connect started
[net]      connect got error EOF
[client]   Trying reconnect using MQTT 3.1 protocol
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1 protocol
[net]      connect started
[net]      connect got error EOF
[client]   Failed to connect to a broker
[store]    memorystore closed
panic: Network Error : %!s(<nil>)
```

So it is not OK.
In both examples I am using exactly the same user, password, MQTT Broker URL, etc.. 

Is there something I am missing? I tried commenting out everything that is related to TLS (lines 18, 58 and 59), but it doesn't help. All help and advice is welcome. And I am sorry if this has been raised earlier, I tried locating information about this problem in this repository, but I found nothing.

Regards,

**Comment by alsm** [comment]
The only way I could replicate your issue was if I tried to connect to a websocket server using a tcp connection, are you sure you specified the server url correctly?
