### ISSUE TITLE
mqtt v5 support

### ISSUE THREAD

**Issue by chowyu08** [eclipse/paho.mqtt.golang#231]
when mqtt v5.0 support?

**Comment by alsm** [comment]
It's in development; https://github.com/eclipse/paho.mqtt.golang/tree/v5 please provide comments/feedback https://github.com/eclipse/paho.mqtt.golang/pull/207 or make your own PRs

**Comment by alsm** [comment]
Development of the v5 client (and future v3 in the same API style) is now in this repo https://github.com/eclipse/paho.golang please help develop it.

**Comment by chowyu08** [comment]
thanks
