### ISSUE TITLE
About URI

### ISSUE THREAD

**Issue by dfang** [eclipse/paho.mqtt.golang#233]
Hi, referring to `https://github.com/mqtt/mqtt.github.io/wiki/URI-Scheme` 

when username contains ":", what is the right MQTT_SERVER ?

and also

`mqtt://` won't work, err msg is "Network Error : Unknown protocol",  but `tcp://` works, curious about this.

**Comment by alsm** [comment]
The mqtt URI scheme is not formalised anywhere else so I'm not sure I'd use it really, I've avoided it in the new V5 client as I don't think it really helps, not sure what to do about a username with a : in.
