### ISSUE TITLE
Publish Store Data in QoS2 

### ISSUE THREAD

**Issue by adityaalviori** [eclipse/paho.mqtt.golang#234]
Hi, I used QoS 2 to publish data to broker. When my device disconnect, the un-publish data store to the directory. When I checked, the latest-10 of data in storage always overwrite with the latest-10 of data. 

my setting options:
`opts = mqtt.NewClientOptions()
	opts.AddBroker("tcp://" + c.ServerHost + ":" + c.ServerPort).SetClientID("PT.IP_test/" + c.LocoID)
	opts.SetUsername("myname").SetPassword("mypass").SetMaxReconnectInterval(1 * time.Minute)
	opts.SetAutoReconnect(true).SetMessageChannelDepth(150)
	opts.SetCleanSession(false).SetStore(mqtt.NewFileStore("/home/my/directory/storeMQTT"))`

my publish method:
`token := a.Publish("myTopic/", 2, false, myPayload)`
`if token2.WaitTimeout(3*time.Second) == true {
log.Printf("++++++++++Send 5 Seconds Packet:%s\n", myPayload)
}`

Did I miss the configuration in options or in publish method?

Thanks

**Comment by alsm** [comment]
The client did not support resuming messages from a filestore, a PR with this function has been merged in today.
