### ISSUE TITLE
Reconnect will receive the last message from the last connection ? 

### ISSUE THREAD

**Issue by JeffreyBool** [eclipse/paho.mqtt.golang#242]
Reconnect will receive the last message from the last connection.?
Is there a way to set up a message that has been received?

```go

client := connect("sub", uri)
	client.Subscribe(topic, 0, func(client mqtt.Client, msg mqtt.Message) {

		data := &tbox_mqtt.Request{}
		proto.Unmarshal(msg.Payload(),data)
		fmt.Printf("data: %+v \n",data)
		fmt.Printf("Topic: %+v \n",msg.Retained())
		//fmt.Printf("subscribe [%s] %+v\n", msg.Topic(), string(msg.Payload()))
	})

```

**Comment by alsm** [comment]
Reconnect relies on the broker to know what messages were and were not delivered in the previous session, there is no way to force a message to be received, although you can publish a message with the retained flag which means that it will be delivered as soon as someone subscribes to the topic
