### ISSUE TITLE
Do not support multiple clients to connect to the same topic subscription?

### ISSUE THREAD

**Issue by JeffreyBool** [eclipse/paho.mqtt.golang#244]
Do not support multiple clients to connect to the same topic subscription?

**Comment by alsm** [comment]
I'm not aware of any reason why that wouldn't work, do you have an example of the issue?

**Comment by lidsid** [comment]
connection lost error: pingresp not received, disconnecting，why only one client？Subscribe topis is "/+/+/rx",publish client 10,000 send message。do not support multiple clients？？？

**Comment by alsm** [comment]
Is your ping timeout set low? pingresp not received usually means that we didn't receive the response to a ping request in time, the default is 10 seconds

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
