### ISSUE TITLE
Receive data hangs up and the lib needs to be restarted

### ISSUE THREAD

**Issue by rcollada** [eclipse/paho.mqtt.golang#245]
I modified one of the samples just to do a simple test since I'm evaluating this project for a production project.
I'm publishing 1000 messages with 5 to 20 mls of delay between each other and at the same time I'm receiving those messages and printing them out in the terminal. 
The thing is at some point my program stops receiving messages and hung up. If I restart it without publishing then the broker delivers the missing messages and the application keeps working. I'm testing with the MqttFx at the same time and it receives all the 1000 messages.
Even if I left all the messages in the broker I need to open the application a few times to be able to receive all the messages.
Here is my code:
```
package main

import (
	"fmt"
	"os"
	"time"

	MQTT "github.com/eclipse/paho.mqtt.golang"
)

func main() {

	topic := "x/server/time"
	broker := "tcp://test.mosquitto.org:1883"
	// password := ""
	// user := ""
	id := "id_sample"
	cleansess := false
	var qos byte = 2
	num := 1000

	opts := MQTT.NewClientOptions()
	opts.AddBroker(broker)
	opts.SetClientID(id)
	// opts.SetUsername(user)
	// opts.SetPassword(password)
	opts.SetCleanSession(cleansess)
	// if *store != ":memory:" {
	// 	opts.SetStore(MQTT.NewFileStore(store))
	// }

	receiveCount := 0
	choke := make(chan [2]string)

	opts.SetDefaultPublishHandler(func(client MQTT.Client, msg MQTT.Message) {
		//fmt.Println("Message received... " + string(msg.Payload()))
		choke <- [2]string{msg.Topic(), string(msg.Payload())}
	})

	client := MQTT.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}

	if token := client.Subscribe(topic, qos, nil); token.Error() != nil {
		fmt.Println(token.Error())
		os.Exit(1)
	}

	//fmt.Println("Sample Publisher Started")
	go func() {
		for receiveCount < num {
			fmt.Println("receive count ", receiveCount)
			incoming := <-choke
			fmt.Printf("RECEIVED TOPIC: %s MESSAGE: %s\n", incoming[0], incoming[1])
			receiveCount++
		}

	}()

	for i := 0; i < num; i++ {
		fmt.Print("---- publishing ----", i)
		time.Sleep(20 * time.Millisecond)
		token := client.Publish(topic, qos, false, fmt.Sprint(i))
		if nil == token.Error() {
			fmt.Print("....OK\n")
		} else {
			fmt.Println(token.Error())
		}
	}

	for {
	}

}
```

**Comment by alsm** [comment]
Hi, running your code with the current HEAD from this repo I have not been able to reproduce this, is that the version you're running with too?

**Comment by rcollada** [comment]
Hi, thank you for your response, I pull the repo again this morning and ran the same tests with the same result. Here https://drive.google.com/file/d/1ZLzxU-Sm71ZLkda_bfwKdprI2S7KrKCu/view?usp=sharing I posted a video on my test, as you can see I send 1000 messages and I receive them with my code and with the MqttFx at the same time. My code stops receiving messages at the 625 and I the rest of them after a restart. I'm using Ubuntu 18.04 but I tried in a mac as well.
Regards and Thanks is advance

**Comment by ricardoatsouza** [comment]
@rcollada I might be facing a similar issue. Did you manage to get any logs?

**Comment by ricardoatsouza** [comment]
@rcollada Looking at your code, I see that you do `Subscribe` after the `connect`. Have you tried to do a `subscribe` as a callback of the `connect` function (via `SetOnConnectHandler` in your `opts` instance)?

**Comment by rcollada** [comment]
I don't think the issue is subscribing to the topics, I actually receive several messages before the mqtt client just stops.
I don't get any logs from the client but sniffing the network seems like the client stops sending replies for the keep alive messages from the broker and gets disconnected.

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
