### ISSUE TITLE
ClientOptions.SetConnectTimeout(...) not affecting websockets connection

### ISSUE THREAD

**Issue by ddhille** [eclipse/paho.mqtt.golang#250]
Setting a ConnectTimeout to e.g. 0.5 seconds to a websockets connection does not change anything in connection behaviour.
``` golang
opts := mqtt.NewClientOptions()
opts.SetConnectTimeout(500 * time.Millisecond)
opts.AddBroker("ws://127.0.0.1:9001")
startTime := time.Now()
if token := client.Connect(); token.Wait() {
  fmt.Println(time.Now().Sub(startTime))
}
```
If the websockets broker is not reachable, the output is ~ `21s`.
If you change `opts.AddBroker("ws://127.0.0.1:9001")` to `opts.AddBroker("tcp://127.0.0.1:1883")`  and the broker is not reachable, the output is exatly `0.5s`.

Edit:
I just discovered a "workaround" (or is this an expected behaviour?): Instead of using `token.Wait()` you need to use `token.WaitTimeout(500 * time.Millisecond)`.
Just wondering why SetConnectTimeout() only affects TCP connections..

**Comment by alsm** [comment]
An oversight, sorry, this should now be fixed
