### ISSUE TITLE
Cut a 1.1.2 release

### ISSUE THREAD

**Issue by dambrisco** [eclipse/paho.mqtt.golang#256]
Current release seems heavily outdated given a lot of important bug fixes in the last 6 months or so (particularly the connection state one with AutoReconnect). Would it be possible to get a 1.1.2 out or similar?

**Comment by alsm** [comment]
I am just waiting to see if any other issues come out of the recent changes, then yes, I plan to cut a new release, shouldn't be long.

**Comment by elakito** [comment]
any update? it's been more than 1 month since the above comment.
we are really waiting for a release.
thanks.

**Comment by wormcc** [comment]
New release please.
thanks.

**Comment by dambrisco** [comment]
@alsm Just wanted to check in on this. Are you still waiting on feedback or are there any issues that need to be closed before a new release can be cut?

**Comment by brocaar** [comment]
@alsm any news on this? I would also be looking for a next tagged release given that the latest tagged release contains some issues that have been solved in the meanwhile :-)

**Comment by evankanderson** [comment]
It also looks like this is licensed under Eclipse Public License v1.0. Any thoughts about upgrading to v2?

**Comment by zamj** [comment]
@alsm Has there been any movement on this? Are you still waiting on feedback on any of the new functionality?

**Comment by thanosd** [comment]
Anything we can do to help move a new release forward?

**Comment by temoto** [comment]
> I am just waiting to see if any other issues come out of the recent changes

You will get increasingly less other issues because (quickly spreading) Go modules stick to last published tag. Particularly, `Message.Ack()` is not available by default under modules.

Using latest untagged code now requires explicit action:
`go get -u github.com/eclipse/paho.mqtt.golang@master`
which you can imagine, not many will do.

**Comment by alsm** [comment]
Thanks, I have just cut 1.2.0

**Comment by alsm** [comment]
If anyone is starting to use MQTT v5 please look at https://github.com/eclipse/paho.golang feeback on the development there would be appreciated.
