### ISSUE TITLE
Unable to receive subscribed topic message with share subscription

### ISSUE THREAD

**Issue by maheshjena1** [eclipse/paho.mqtt.golang#264]
I am running only one client for a shared subscription test.
I am unable to receive the subscribed topics with the shared subscription.
Here is my code:

```
func (ex *Example) subscribe() bool {
	ex.SubscribeTopic = "$share/dummyGrp" + ex.SubscribeTopic
	if token := ex.client.Subscribe(ex.SubscribeTopic, 1, ex.RegdReqHandler); token.Wait() && token.Error() != nil {
		log.Println("Subscribe failure: ", token.Error())
		return false
	}
	return true
}
```

I am able to receive from the topic if I comment the line:
`ex.SubscribeTopic = "$share/dummyGrp" + ex.SubscribeTopic`

looks like the shared subscription is not working in my case.
any suggestion?

**Comment by maheshjena1** [comment]
hi,
any update?

**Comment by filinvadim** [comment]
Reopen please

**Comment by MattBrittan** [comment]
@filinvadim the [change made](https://github.com/eclipse/paho.mqtt.golang/commit/5ca1e82c41c63687f3ed5e5be321a93a361ea44f) was purerly to support Hive MQ (shared subscriptions are not a standard feature of MQTT3). I have had a quick look at the code and it looks correct to me (@maheshjena1 I cannot see anything in the release notes for Hive 4.0 that would have an impact but would need logs to look further).

From my reading of the code if you subscribe to ```$share/my-shared-subscriber-group/myhome/groundfloor/+/temperature``` then that is the topic that will be sent to the broker but internally the package will be looking for incomming messages on ```/myhome/groundfloor/+/temperature``` to pass to your callback (this seems a valid approach to me). I don't use Hive MQ so cannot test this; if you believe it is an issue I would suggest opening a new issue and providing full logs (debug logs for this package and logs from HiveMQ).
