### ISSUE TITLE
v1.1.1: NPE with QoS2

### ISSUE THREAD

**Issue by andig** [eclipse/paho.mqtt.golang#265]
I've not been able to repro this but I saw the following when I killed the mosquitto server during running client calling `Publish()`:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1212b03]

    goroutine 54 [running]:
    github.com/eclipse/paho%2emqtt%2egolang.outgoing(0xc00009ca80)
            /Users/andig/htdocs/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/net.go:202 +0xb33
    created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
            /Users/andig/htdocs/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.1.1/client.go:295 +0x6e7
    exit status 2

Client was created with these options:

    2018/11/25 13:26:47 Connecting MQTT at tcp://localhost:1883
    2018/11/25 13:26:47     clientid:     mqttClientID
    2018/11/25 13:26:47     user:         mqttUser
    2018/11/25 13:26:47     password:     ****
    2018/11/25 13:26:47     topic:        homie
    2018/11/25 13:26:47     qos:          2
    2018/11/25 13:26:47     cleansession: true

**Comment by andig** [comment]
Update: have seen this twice now. Seems to be happing from inside `Client.outgoing()`

**Comment by alsm** [comment]
This should have been fixed in https://github.com/eclipse/paho.mqtt.golang/commit/0a0770a412e6809d9f02287efb20b1955b22cc24 there was an issue that not all outbound messages have a token (pubrel, puback, pubcomp), an interruption while sending one of those can cause the issue you're seeing.

**Comment by andig** [comment]
Great, thank you! I'd fully support the idea of a patch release ;)
