### ISSUE TITLE
Waiting for Publish() token returns success even if not connected

### ISSUE THREAD

**Issue by andig** [eclipse/paho.mqtt.golang#266]
During testing, I forgot to `Connect()` to the broker. Still, `Publish()` returned success:

	mqttClient := mqtt.NewClient(mqttOptions)
	// if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
	// 	log.Fatal("mqtt: error connecting: ", token.Error())
	// 	panic(token.Error())
	// }

	time.Sleep(1 * time.Second)
	token := mqttClient.Publish("input/inject", 0, false, "3.14")
	if token.WaitTimeout(100 * time.Millisecond) {
		log.Println("--> inject done")
	}

Result:

    --> inject done

Listening with `mosquitto` I cannot receive the published message unless I `Connect()` before publishing.

If seems wrong that either `token.Wait` or `token.WaitTimeout` return success if not connected to the broker?

I'm getting the same result with either 1.1.1 or v1.1.2-0.20181129145454-379fd9f99ba5.

**Comment by andig** [comment]
Is anybody able to verify this?

**Comment by andig** [comment]
Ok, I guess I've finally found it- with Qos 0 publish is always assumed to be successful? Not sure that makes sense when not connected to a broker though.

**Comment by johnhydroware** [comment]
I think I would make sense to have as much checks as possible even on qos 0. It should be able to see if its been sent even I think. All type of feedback is useful even om QoS 0.
