### ISSUE TITLE
Go dep not pulling correct source from github

### ISSUE THREAD

**Issue by falknerdominik** [eclipse/paho.mqtt.golang#267]
Hi,

I am working on a project and using dep as a dependency management tool:

```
PROJECT                              CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
github.com/eclipse/paho.mqtt.golang  v1.1.1         v1.1.1         36d01c2   v1.1.1   2  
```

According to the Release (here: https://github.com/eclipse/paho.mqtt.golang/releases) it fixes the issue #107 but it still contains the old code for tokens:

```
//Token defines the interface for the tokens used to indicate when
//actions have completed.
type Token interface {
	Wait() bool
	WaitTimeout(time.Duration) bool
	Error() error
	setError(error)
}

type tokenCompletor interface {
	Token
	flowComplete()
}
```
Did I reference the wrong commit/version or is this fix not in this release?

**Comment by wormcc** [comment]
@falknerdominik Try to switch to the master branch, there is no new release since v1.1.1.

**Comment by tilinna** [comment]
> @wormcc thank you! Will there be a release in the near future?

See #256

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
