### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by jjm011** [eclipse/paho.mqtt.golang#273]
Related to #145 

When I do Connect -> Disconnect -> Connect -> Disconnect, the error says the close(c.stopRouter) is already closed.

	c.Disconnect(250)
	c.Connect()

	time.Sleep(5 * time.Second)
	c.Disconnect(250)
I did something like this after the first connection is well established.

What is the best way to reinitiate the connection process if the first attempt fails due to say broker/network failure? I currently have a ticker that runs every 5 seconds to make sure the connection is always up. Is this recommended?

Thanks.

**Comment by alsm** [comment]
Ahh, so there is no protection of the closing of the router channel, I've just added one.
If you haven't had a successful connection you shouldn't need to call disconnect before calling connect again, if you've had a successful connection the client offers an autoreconnect function.
