### ISSUE TITLE
Key pinning when opening a connection

### ISSUE THREAD

**Issue by willianberf** [eclipse/paho.mqtt.golang#276]
Hello, 
Is there a reason not to support key pinning? 
Seems like an important feature against MITM attacks.

**Comment by dambrisco** [comment]
@willianberf Does [this post](https://tam7t.com/key-pinning-in-golang/) accurately represent what you'd like to see? If so, this could be accomplished by creating a Dialer option that could be set for use inside [net.go](https://github.com/eclipse/paho.mqtt.golang/blob/master/net.go).

**Comment by willianberf** [comment]
> @willianberf Does [this post](https://tam7t.com/key-pinning-in-golang/) accurately represent what you'd like to see? If so, this could be accomplished by creating a Dialer option that could be set for use inside [net.go](https://github.com/eclipse/paho.mqtt.golang/blob/master/net.go).
> 
> This can currently be accomplished using the first method listed in that same blog post, fwiw (we currently use that ourselves).

@dambrisco Thanks for your reply!
I guess the same pinning can be done with SetTLSConfig method of ClientOptions under [options.go](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go), so this ticket can be closed.
