### ISSUE TITLE
Ways to Limit Store Size

### ISSUE THREAD

**Issue by jjm011** [eclipse/paho.mqtt.golang#277]
Hi,

I would like to know what is the best way to limit the size of the store for caching the Qos1or2 messages when the connection is lost. Since the devices we have are embedded systems, we need to limit the number of messages when the connection is down. Is there any simple ways of setting a buffer limit in the existing library?

Any guide or suggestion or example is deeply appreciated.

-Junjie

**Comment by YiuTerran** [comment]
You can create a memory store by yourself, using LRU algrithom with max size.

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if the existing answer is insufficient.
