### ISSUE TITLE
Could we have save to store when `qos > 0` before `client.Connection()`?

### ISSUE THREAD

**Issue by xlebenny** [eclipse/paho.mqtt.golang#279]
Could we no need handle *connection* / *connection fail* like `c.Pushlish` when `c.status == reconnect`?
Because client maybe have a network problem

```golang
opts := MQTT.NewClientOptions().AddBroker("tcp://iot.eclipse.org:1883")
opts.SetStore(mqtt.NewFileStore("./temp"))
c := MQTT.NewClient(opts)
// Without this
// if token := c.Connect(); token.Wait() && token.Error() != nil {
//  panic(token.Error())
// }
c.Publish("go-mqtt/sample", 1, false, "to file storage")
```

**Comment by alsm** [comment]
Honestly, I think the offline buffering was a bad idea, I shouldn't have done it. It at least makes sense in combination with auto reconnect through to smooth out transient connection issues when you've already been connected. I don't want to extend it to allow buffering prior to ever having had a connection.
