### ISSUE TITLE
Accept a net.Conn initing client

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.golang#28]
migrated from Bugzilla [#446895](https://bugs.eclipse.org/bugs/show_bug.cgi?id=446895)
status NEW severity *normal* in component *MQTT-Go* for *1.1*
Reported in version *future* on platform *PC*
Assigned to: Al Stockdill-Mander

On 2014-10-13 09:22:40 -0400, Al Stockdill-Mander wrote:

> Rather than only connecting over a specified set of network transports the client should be able to be initialised with a net.Conn that has already established the connection. The Paho Go library could provide some helper functions that will create connections over known transports.
> It needs to be considered how this would interact with the auto reconnection feature.

**Comment by alsm** [comment]
Not sure if this is really valid, no one is asking for it and it would make connect/disconnect/autoreconnect more awkward.
