### ISSUE TITLE
Race and hangup on continious connect/disconnect 

### ISSUE THREAD

**Issue by antlad** [eclipse/paho.mqtt.golang#280]
We are using paho mqtt client for continuous publish messages to cloud. For all examples above QoS is `1`.  
And we faced with couple of issues.
- First one race condition on token wait from multiple gorutines. As we got from code of library it was design for access from multiple gorutines - it has state synchronization. Here is some info:
```text
WARNING: DATA RACE
Write at 0x00c4219e3268 by goroutine 4103:
  xxx/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*messageIds).cleanUp()
      xxx/vendor/github.com/eclipse/paho.mqtt.golang/messageids.go:43 +0x2e7
  xxx/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      xxx/vendor/github.com/eclipse/paho.mqtt.golang/client.go:462 +0xb2

Previous read at 0x00c4219e3268 by goroutine 2101:
  xxx/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).Error()
      xxx/vendor/github.com/eclipse/paho.mqtt.golang/token.go:92 +0x88
  xxx/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*PublishToken).Error()
      <autogenerated>:1 +0x43
  xxx/cloudconnector.(*publishJob).process()
      xxx/cloudconnector/mqtt_circuit_breaker.go:304 +0x402
  xxx/cloudconnector.(*worker).run()
      xxx/cloudconnector/workers_pool.go:70 +0x6f

Goroutine 4103 (running) created at:
  xxx/vendor/github.com/eclipse/paho%2emqtt%2egolang.errorWatch()
      xxx/vendor/github.com/eclipse/paho.mqtt.golang/net.go:332 +0x2a9

Goroutine 2101 (running) created at:
  xxx/cloudconnector.(*workersPool).run()
      xxx/cloudconnector/workers_pool.go:86 +0xdf
```

After that code was moved out from waiters pool. And all access to library is done only from single gorutine. Exactly this problem was partially solved, but it reduced performance.

- Sometimes publish method can hangup.
During investigation we found that root case is in mqtt client library.
After some time of work (in test it can be about 1 min) and during continuous connect/disconnect it will hang up on publish call and never return back:
![screenshot from 2019-02-04 18-00-18](https://user-images.githubusercontent.com/2556177/52218107-f9ae1e80-28aa-11e9-972a-a1c9d28fe5ee.png)

Usually it happen after race condition:
```text
WARNING: DATA RACE
Write at 0x00c42075aa68 by goroutine 1047:
  github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*messageIds).cleanUp()
      /home/vlad/projects/litmus/go_litmus/src/github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho.mqtt.golang/messageids.go:43 +0x2e7
  github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      /home/vlad/projects/litmus/go_litmus/src/github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho.mqtt.golang/client.go:503 +0x1ca

Previous read at 0x00c42075aa68 by goroutine 7:
  github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).Error()
      /home/vlad/projects/litmus/go_litmus/src/github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho.mqtt.golang/token.go:101 +0x88
  github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*PublishToken).Error()
      <autogenerated>:1 +0x43
  github.com/antlad/mqtt_issue/mqtt_conn.(*mqttConnection).Run()
      /home/vlad/projects/litmus/go_litmus/src/github.com/antlad/mqtt_issue/mqtt_conn/mqtt_conn.go:278 +0xd31

Goroutine 1047 (running) created at:
  github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho%2emqtt%2egolang.errorWatch()
      /home/vlad/projects/litmus/go_litmus/src/github.com/antlad/mqtt_issue/vendor/github.com/eclipse/paho.mqtt.golang/net.go:352 +0x2a9

Goroutine 7 (running) created at:
  main.main()
      /home/vlad/projects/litmus/go_litmus/src/github.com/antlad/mqtt_issue/main.go:178 +0x4c4
```

To reproduce [here](https://github.com/antlad/mqtt_issue) is ready to use test for Linux(was tested on Ubuntu 16).
As mqtt server it is using `mosquitto`, for receiver it is using `mosquitto_sub` (repo has compiled versions for Linux).
Golang version 1.9.7.
Test require python to start. 
I tried latest release v1.1.1 and latest master - it is still there.

So after clone just do:
```bash
go build -race .
./start.py
``` 

Wait for a minute -it will show race conditions and after some time hang up.

Could you please investigate it from your side?

**Comment by antlad** [comment]
@alsm @shoenig Guys could you, please, have a look on this issue?

**Comment by alsm** [comment]
I'm just back from 3 weeks holiday, I'll try and look at this issue this week.

**Comment by alsm** [comment]
Thanks for the effort you put into reporting this, I wasn't able to get the test case you prepared to error, but I've spotted a potential race with setting and accessing a token error that looks like it might be the issue you're seeing. I've just pushed an update to master with a fix for this that passes my local testing. If you could test it with your cases and let me know if it's made a difference.

**Comment by antlad** [comment]
@alsm Thanks for effort.. Race looks like gone. But hang up still there. First I though that this commit helped (I checked on `ba971f185f1bce82b0e8d19c74da95e37c68234a`). But it hanged up again, but much later then usual in test. Again on publish call `Publish(topic string, qos byte, retained bool, payload interface{}) Token` . And as I see at log it is happening right in same moment when connection lost.

**Comment by alsm** [comment]
At least that's one bit gone, I'll have another look and see if I can workout where the contention/deadlock is

**Comment by ovaltzer** [comment]
hey, did you manage to find something @alsm ?

**Comment by dambrisco** [comment]
@antlad In your test script, what indicates that a hangup has occurred? I'm looking into this because it might be related to an issue we're experiencing on our end that's been incredibly difficult to replicate.

**Comment by antlad** [comment]
@dambrisco Yes.. it was also really hard to reproduce on our side. This script and app(code is modified for test) reproducing situation on my laptop after 1-2 minutes. So you can see that no messages are cumming to mqtt after some moment at all. And main - if you uncomment this lines:
![Screenshot from 2019-03-27 09-41-41](https://user-images.githubusercontent.com/2556177/55055753-1417a380-5075-11e9-9740-aa40d583f26c.png)
There will be moment when `before publish` will be last line appeared from this publishing app.

**Comment by dambrisco** [comment]
@antlad I'm not sure this will fix your issue, but #299 fixes the issues we were seeing on our end. I recommend giving it a shot to see if it helps. We have it available in v1.1.4 from our repo: https://github.com/MachineShop-IOT/paho.mqtt.golang/releases/tag/v1.1.4

**Comment by antlad** [comment]
@dambrisco Thanks a lot! I'll try on our end asap.

**Comment by antlad** [comment]
@dambrisco Thanks! Looks like inside https://github.com/MachineShop-IOT/paho.mqtt.golang/releases/tag/v1.1.4 issue is fixed. Test is working for a hour without freeze.

**Comment by dambrisco** [comment]
@alsm Looks like this can be closed.

**Comment by alsm** [comment]
Thanks everyone
