### ISSUE TITLE
How to set the Last Will and Testament message

### ISSUE THREAD

**Issue by zg1211** [eclipse/paho.mqtt.golang#284]
I want to set the Last Will and Testament message which is sent to broker after disconnect for a created client,  and I found a method in options.go, but it seems not the method from the comment

// SetWill accepts a string will message to be set. When the client connects,
// it will give this will message to the broker, which will then publish the
// provided payload (the will) to any clients that are subscribed to the provided
// topic.
func (o *ClientOptions) SetWill(topic string, payload string, qos byte, retained bool) *ClientOptions {
	o.SetBinaryWill(topic, []byte(payload), qos, retained)
	return o
}

**Comment by vvhuang0909** [comment]
hi, do you find a method to set LWT in paho.mqtt.golang ?
