### ISSUE TITLE
Token Error and setError are not implementing concurrency pattern correctly

### ISSUE THREAD

**Issue by satishThakur** [eclipse/paho.mqtt.golang#285]
In version 1.1.1 in token.go:

`func (b *baseToken) Error() error {
	b.m.RLock()
	defer b.m.RUnlock()
	return b.err
}`

`func (b *baseToken) setError(e error) {
	b.m.Lock()
	defer b.m.Unlock()
	b.err = e
	b.flowComplete()
}`

Which leads to deadlock in case of token.wait() and setError(). But In master now we are calling setError and not taking any locks - while in Error() - reading the error we are still taking the locks. This is wrong as we have to take locks for both setting errors as well as reading error. In cases where different go routines would be executed on different CPU the reading goroutine might never see value of error.
To fix this we should have used different mutex for error and different one for complete flag. I had done that on my local code and tested this against load (where I was getting frequent deadlocks).

**Comment by alsm** [comment]
Thanks for this, I just read it after trying to fix the problem in #280 I think the fix I've put in there resovles this issue too, if you could take a look at the last updates to master. Thanks.

**Comment by satishThakur** [comment]
So now we are back to 1.1.1 code right? This has another problem. Let me state the scenerio:

1. We try to publish a message using the client and get a Token. Now we wait for completion using token.Wait(). which means we have acquired the lock on mutex.
2. In Goroutine where we send the message (outgoing) when we write to message assume we get error.
3. outgoing goroutine tries to set the error - but tries to take the lock first.

Now we have typical deadlock. BTW I have reproduced this issue very easily in my environment and have a fix ready. If you want I can raise a PR with a fix which is well tested on good load over 5-7 days.

**Comment by satishThakur** [comment]
Stacktrace for your reference which shows deadlock:

1 @ 0x102eacb 0x102eb73 0x100748e 0x100717b 0x123dad8 0x124fa41 0x105a2c1
#	0x123dad7	bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).Wait+0x97	/Users/satish/sandbox/go/src/bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho.mqtt.golang/token.go:58
#	0x124fa40	main.publishToBroker+0x210										/Users/satish/sandbox/go/src/bitbucket.org/rivigotech/tracker/cmd/mqtt/broker/producer.go:120

1 @ 0x102eacb 0x102eb73 0x103eb7c 0x103e7b9 0x106f8e4 0x123343d 0x105a2c1
#	0x103e7b8	sync.runtime_Semacquire+0x38											/usr/local/Cellar/go/1.11.5/libexec/src/runtime/sema.go:56
#	0x106f8e3	sync.(*WaitGroup).Wait+0x63											/usr/local/Cellar/go/1.11.5/libexec/src/sync/waitgroup.go:130
#	0x123343c	bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost+0x7c	/Users/satish/sandbox/go/src/bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho.mqtt.golang/client.go:461

1 @ 0x102eacb 0x102eb73 0x103eb7c 0x103e8ad 0x106e73f 0x106f5cd 0x123ddc1 0x1238aae 0x105a2c1
#	0x103e8ac	sync.runtime_SemacquireMutex+0x3c										/usr/local/Cellar/go/1.11.5/libexec/src/runtime/sema.go:71
#	0x106e73e	sync.(*Mutex).Lock+0xfe												/usr/local/Cellar/go/1.11.5/libexec/src/sync/mutex.go:134
#	0x106f5cc	sync.(*RWMutex).Lock+0x2c											/usr/local/Cellar/go/1.11.5/libexec/src/sync/rwmutex.go:93
#	0x123ddc0	bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).setError+0x30	/Users/satish/sandbox/go/src/bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho.mqtt.golang/token.go:96
#	0x1238aad	bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho%2emqtt%2egolang.outgoing+0x61d			/Users/satish/sandbox/go/src/bitbucket.org/rivigotech/tracker/vendor/github.com/eclipse/paho.mqtt.golang/net.go:177

**Comment by alsm** [comment]
Damn it

**Comment by alsm** [comment]
Looking at the code again I think the ready field was unnecessary and removing it means we don't need to take a lock in Wait() or WaitTimeout().

**Comment by satishThakur** [comment]
Agree - even I could not think of a reason for having complete flag - and then combing channel with mutex looked bit odd as well:

We can simplify the code as following:

`// Wait will wait indefinitely for the Token to complete, ie the Publish
// to be sent and confirmed receipt from the broker
func (b *baseToken) Wait() bool {
		<-b.complete
		return true
}

// WaitTimeout takes a time.Duration to wait for the flow associated with the
// Token to complete, returns true if it returned before the timeout or
// returns false if the timeout occurred. In the case of a timeout the Token
// does not have an error set in case the caller wishes to wait again
func (b *baseToken) WaitTimeout(d time.Duration) bool {
		select {
		case <-b.complete:
			return true
		case <-time.After(d):
			return false
		}
}`

I can try this locally on system which has decent load and deadlock scenerio also happens frequently. Let me know your views!!

**Comment by alsm** [comment]
That's almost exactly what I did in https://github.com/eclipse/paho.mqtt.golang/commit/ba971f185f1bce82b0e8d19c74da95e37c68234a if you pull master and test that please

**Comment by satishThakur** [comment]
saw the code it looks good - will pull the master and test once. Closing the issue.
