### ISSUE TITLE
hi，this take up big memeory。

### ISSUE THREAD

**Issue by FristResponder** [eclipse/paho.mqtt.golang#287]
hi，when i used paho for my IM project，sometimes this backend  server crash。
so，i use pprof to search and location this problem.i used only two client to test.below is pprof screenshot。
![image](https://user-images.githubusercontent.com/12823785/54584863-79570d80-4a53-11e9-98ed-ead96d8b170f.png)
and flamegraph。
![image](https://user-images.githubusercontent.com/12823785/54584884-97247280-4a53-11e9-9972-a09ae1439d9e.png)
i lookup the Session package，the MemorySession is a struct。

type MemorySession struct {
	Counter  *IDCounter
	Incoming *PacketStore
	Outgoing *PacketStore
}
can you tell how can i solve this problem？
thank you！

**Comment by alsm** [comment]
I'm sorry but this code is not part of this library
