### ISSUE TITLE
Need Sample to Verify Peer Certificate

### ISSUE THREAD

**Issue by shawnhankim** [eclipse/paho.mqtt.golang#309]
I would like to verify remote server's certificate issuer using this MQTT code.
- HTTP has a response which contains `TLS.PeerCertificates` as follows.

```
res, err := http:Client.Do(requestPayload)
for _, cert := range resp.TLS.PeerCertificates {
    strCert := fmt.Sprintf("Peer certificate \"%v\"", cert.Subject.CommonName)
    strIssu := fmt.Sprintf("ISSUED BY \"%v\"", cert.Issuer.CommonName)
    fmt.Printf("%s, %s\n", strCert, strIssu)
}
```

- Does this MQTT code provide those function?

**Comment by alsm** [comment]
You can provide your own *tls.Config in the client options, within that there is
```
