### ISSUE TITLE
Publish with message id generated by the caller

### ISSUE THREAD

**Issue by Florimond** [eclipse/paho.mqtt.golang#314]
In [Emitter](https://github.com/emitter-io/go), we match responses and requests based on the token.

[Code](https://github.com/emitter-io/go/blob/a64c9aca4bab172bf3e4a5ded3b38d1b17ae1427/v2/emitter.go#L407):
```go
// Makes a request
func (c *Client) request(operation string, req interface{}) (Response, error) {
	request, err := json.Marshal(req)
	if err != nil {
		panic("unable to encode the request")
	}

	// publish and wait for an error, response or puback
	token := c.conn.Publish(fmt.Sprintf("emitter/%s/", operation), 1, false, request)
	resp := <-c.store.PutCallback(token.(*mqtt.PublishToken).MessageID())
	if err := c.do(token); err != nil {
		return nil, err
	}

	if err, ok := resp.(error); ok {
		return nil, err
	}
	return resp, nil
}

// do waits for the operation to complete
func (c *Client) do(t mqtt.Token) error {
	if !t.WaitTimeout(c.timeout) {
		return ErrTimeout
	}

	return t.Error()
}
```

So first we publish and retrieve the token, then only store a callback for the token. Which means that, although improbable, it's possible in theory that the response is received before we created the callback.
This is most likely not an issue for Emitter alone. And it seems to me the simplest solution would be to be able to generate a token prior to publishing, and have some `PublishWithToken` function that would use this token instead. Thus allowing the creation of the callback earlier.

**Comment by alsm** [comment]
That would mean allowing you to set the MessageID? I don't know what broker you're using but if it supports MQTTv5 that is better suited for your needs I think, it has support for message metadata including correlation ids and other fields.
