### ISSUE TITLE
fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by FristResponder** [eclipse/paho.mqtt.golang#315]
hi，i find a crash,it aways appear,below is the console information 
fatal error: sync: unlock of unlocked mutex
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa4eb7e]
![image](https://user-images.githubusercontent.com/12823785/57207344-9776ce00-6fff-11e9-8056-48881651fea4.png)

**Comment by FristResponder** [comment]
// kill existing client if session is taken
	if ok && existingSession.owner != nil {
		// close client
		existingSession.owner.Close()

		// release global mutex to allow publish and termination, but leave the
		// setup mutex to prevent setups
		m.globalMutex.Unlock()
		
		// wait for client to close
		var err error
		select {
		case <-existingSession.owner.Closed():
			// continue
		case <-time.After(m.KillTimeout):
			err = ErrKillTimeout
		}

		// acquire mutex again
		m.globalMutex.Lock()
		
		// return err if set
		if err != nil {
			
			return nil, false, err
		}
	}

**Comment by FristResponder** [comment]
i find a bug in this package, it will be a nil pointer

//i added a if judge,existingSession.owner maybe a nil pointer

// kill existing client if session is taken
	if ok && existingSession.owner != nil {
		// close client
		existingSession.owner.Close()
		// release global mutex to allow publish and termination, but leave the
		// setup mutex to prevent setups
		m.globalMutex.Unlock()
		var err error
		if existingSession.owner != nil{
			select {
			case <-existingSession.owner.Closed():
				// continue
			case <-time.After(m.KillTimeout):
				err = ErrKillTimeout
			}
		}else{
			err = ErrKillTimeout
		}

**Comment by FristResponder** [comment]
hello, who can help me?

**Comment by alsm** [comment]
I'm not sure I can help, the code you have posted here does not appear to be from this library.
