### ISSUE TITLE
Document how to run the tests

### ISSUE THREAD

**Issue by kevinburke** [eclipse/paho.mqtt.golang#321]
It would be nice if the `fvt/start_IMA.sh` script that is apparently necessary to run the tests was referenced anywhere else in the documentation.

Alternatively, it would be nice if the test suite could work out of the box for people who don't have access to an IBM device - maybe we could skip the tests that require an IBM machine if it's not present.

**Comment by alsm** [comment]
By default all that is required for the tests to run is an mqtt broker at 127.0.0.1:1883, there are no tests that require an IBM system.

**Comment by kevinburke** [comment]
I guess as someone who is trying to get the tests running but unfamiliar with this project you might want to document what sort of broker needs to be running there, then.

You might also want to update the documentation in fvt/README.md. I don't know what FVT is but I tried running the tests, saw that stuff broke and then started reading and saw this.

> The FVT tests are currenly only supported by [IBM MessageSight](http://www-03.ibm.com/software/products/us/en/messagesight/).

> Support for [mosquitto](http://mosquitto.org/) and [IBM Really Small Message Broker](https://www.ibm.com/developerworks/community/groups/service/html/communityview?communityUuid=d5bedadd-e46f-4c97-af89-22d65ffee070) might be added in the future.

**Comment by MattBrittan** [comment]
Pull request #366 (merged a week ago) included updates to ```fvt/README.md``` (there was some info re mosquitto at the bottom of the file but it conflicted with what was said at the top) and added a ```fvt/docker``` folder which should hopefully be of assistance to anyone trying to find an easy way to run the tests.

**Comment by MattBrittan** [comment]
Closing this issue as I believe the updates in #366 have sufficiently improved the documentation re tests.
