### ISSUE TITLE
Publishing freeze on connection lost

### ISSUE THREAD

**Issue by panter-dsd** [eclipse/paho.mqtt.golang#325]
Version: master
If the option `options.AutoReconnect` is false then `options.MessageChannelDepth` is set to 0 [here](https://github.com/eclipse/paho.mqtt.golang/blob/0d81c295c555691f527a3e6f5b5c0a889f198bc3/client.go#L143). So, we have a channel with zero length. When we get into the line https://github.com/eclipse/paho.mqtt.golang/blob/0d81c295c555691f527a3e6f5b5c0a889f198bc3/client.go#L602 and connection is lost (channel reader has already exited), we're stuck at this line and never leave the `Publish` function.

**Comment by ChIoT-Tech** [comment]
I believe that the fix introduces a new issue; if WriteTimeout is set to 0 (the default) then the "case <-time.After(c.options.WriteTimeout):" triggers immediately. This sometimes (approx 10% in my test code) ends up getting selected before the write to c.obound meaning that the publish message token is flagged as being in error state incorrectly (and the published message is lost despite AutoReconenct and persistence being active).

While setting WriteTimeout to a non-zero value would fix this the default value is currently is 0 (supposed to mean no timeout) and when used with AutoReconenct and Persistence these values make sense as the data will be written at some point. 
 
The simplest solution might be: 

```
if c.options.WriteTimeout == 0 {
	c.obound <- &PacketAndToken{p: pub, t: token}
} else {
	select {
	case c.obound <- &PacketAndToken{p: pub, t: token}:
	case <-time.After(c.options.WriteTimeout):
		token.setError(errors.New("publish was broken by timeout"))
	}
}
```

**Comment by panter-dsd** [comment]
@ChIoT-Tech sorry, I didn't notice this. Fixed. Better would be to using contexts but this will change API.

**Comment by MattBrittan** [comment]
Closing this because the change has been merged.
