### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by aadarshpratik1** [eclipse/paho.mqtt.golang#329]
When I am trying to use the Write function of the interface ControlPacket, I am getting this error.

package main

import (
	"bytes"
	"fmt"

	"github.com/eclipse/paho.mqtt.golang/packets"
)

func main() {
	a := packets.NewControlPacket(8)
	fmt.Println(a)
	cp := a.(*packets.SubscribePacket)
	fmt.Println(cp.Topics)
	cp.Topics = append(cp.Topics,  "this should work")
	fmt.Println(len(cp.Topics))
	var buf bytes.Buffer
	errwrite := cp.Write(&buf)
	if errwrite != nil {
	}
	fmt.Println(buf)

}

**Comment by MattBrittan** [comment]
Know this is an old issue (and you did not post the error message) but thought I might as well respond so it can be closed off. You are using the low level ```packets``` package directly; if doing this you will need to have a good look at the code (its not well commented and generally only used by the main package). In this case the SubscribePacket has two member slices:

```
Topics    []string
Qoss      []byte
```

If you manually put something into Topic then you need to put the QOS level for that topic into the Qos slice (so ```cp.Topics = append(cp.Topics, "this should work");cp.Qoss= append(cp.Qoss, 0)```)

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
