### ISSUE TITLE
Unsubscribe surprisingly breaks previous subscribe

### ISSUE THREAD

**Issue by rollulus** [eclipse/paho.mqtt.golang#336]
Subscribing to `/a/#` works correctly.
However, if one subscribes to `/a/b/#` and unsubscribes from it afterwards, the earlier message handler doesn't receive anything anymore, although the broker publishes according to `tcpdump`.

To reproduce:
```go
package main

import (
	"log"
	"time"

	mqtt "github.com/eclipse/paho.mqtt.golang"
)

func msgHandler(_ mqtt.Client, m mqtt.Message) {
	log.Printf("received message for topic %s: %s", m.Topic(), string(m.Payload()))
}

func main() {
	o := mqtt.NewClientOptions().AddBroker("tcp://" + "iot.eclipse.org:1883")
	c := mqtt.NewClient(o)
	if t := c.Connect(); t.Wait() && t.Error() != nil {
		panic(t.Error())
	}

	if t := c.Subscribe("/a/#", 1, msgHandler); t.Wait() && t.Error() != nil {
		panic(t.Error())
	}

	if t := c.Subscribe("/a/b/#", 1, msgHandler); t.Wait() && t.Error() != nil {
		panic(t.Error())
	}

	if t := c.Unsubscribe("/a/b/#"); t.Wait() && t.Error() != nil {
		panic(t.Error())
	}

	time.Sleep(time.Hour)
}
```

And publish messages from the console with:
```
mosquitto_pub -h iot.eclipse.org -t '/a/b/hello'   -d -m 'xxxx' -q 1
mosquitto_pub -h iot.eclipse.org -t '/a/hello'   -d -m 'xxxx' -q 1
```

My expectation is to receive those messages. In practice, nothing happens.

To verify that the example isn't broken itself, remove the last `Subscribe` and `Unsubscribe`.

**Comment by boki** [comment]
I think this is the same issue I ran into: `router.addRoute` uses `route.match` to update existing routes, resulting in wildcards being applied. The fix seems to be to change [line 102](https://github.com/eclipse/paho.mqtt.golang/blob/master/router.go#L102) in route.go from

```diff
--- a/router.go
+++ b/router.go
@@ -105,7 +105,7 @@ func (r *router) addRoute(topic string, callback MessageHandler) {
        r.Lock()
        defer r.Unlock()
        for e := r.routes.Front(); e != nil; e = e.Next() {
-               if e.Value.(*route).match(topic) {
+               if e.Value.(*route).topic == topic {
                        r := e.Value.(*route)
                        r.callback = callback
                        return
```

**Comment by v-zhuravlev** [comment]
Had exactly the same issue with `router.addRoute`. 
In my case, I had subscriptions to `#`, `topic1`, `topic2` with different callbacks set for each. Due to ` if e.Value.(*route).match(topic) {`, new subscription overrides previous routes instead of creating new one and only last callback is working for all routes.

And in my app I expect:
If I publish something to `topic`, I expect both callbacks from `#` and `topic` subscriptions to fire. Not just the last one.

**Comment by MattBrittan** [comment]
Closing this because a fix was committed a year ago; please feel free to reopen if its still an issue.
