### ISSUE TITLE
http:// as broker scheme doesn't error

### ISSUE THREAD

**Issue by Ashtonian** [eclipse/paho.mqtt.golang#337]
If you set your broker address as http:// the connect token wait calls will return true indicating everything is working and then immediately disconnect. I think it should instead error or panic as this is an invalid scheme.

**Comment by MattBrittan** [comment]
Hi @Ashtonian, 
Can you please confirm if you are just calling token.Wait() or if you are checking token.Error()?

token.Wait() will always return true. token.WaitTimeout(dur) will return true if the job is complete (either successfully or with an error) or false if it is still running (after the duration has passed).

If you want to check for an error you need to call token.Error() (after waiting for the token to be complete) and I suspect that you will get an error if you just set the broker address to "http://".

An example (from fvt_client_test.go) is:
```
if token := c.Connect(); token.Wait() && token.Error() != nil {
   t.Fatalf("Error on Client.Connect(): %v", token.Error())
}
```

**Comment by alsm** [comment]
If I change one of the samples and put http as the protocol I get an error back from the connect token
```
Network Error : Unknown protocol
```

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
