### ISSUE TITLE
Outbound SubscribePackets are not persisted

### ISSUE THREAD

**Issue by robbawebba** [eclipse/paho.mqtt.golang#358]
I'm currently improving my application's resilience to network instability , and one of the edge cases I'm concerned with is sending subscription requests while the connection status is `connecting` or `reconnecting`.

I noticed that the `client.resume` method is designed to handle saved SubscribePackets if `options.ResumeSubs` is true. I've never seen this logic used, however, because it seems that outgoing SubscribePackets are not persisted. I would expect the `client.Subscribe` method would persist it's outgoing packets similar to how the `client.Publish` method persists outbound PublishPackets when the connection status is either `connecting` or `reconnecting`. the `persistOutbound` function also seems to contain the proper logic to save SubscribePackets.

I would love to add the logic to persist outbound subscribe packets in a new PR. Also, if my understanding of `ClientOptions.ResumeSubs` or the persistence of `SubscribePackets` is incorrect, I'm definitely interested in learning the correct behavior/usage so I can improve my application's design.

Thanks in advance!

**Comment by alsm** [comment]
I was thinking about this and the spec doesn't talk about handling sub/unsub when connection is lost. Until you have the ack you don't know whether the server has received and processed your sub request, but potentially it will have and if there is a retained message that could be queued up waiting to be delivered. In that case sending the sub again could cause it to send another copy of the retained message.
Also this would only happen in the case that you are restarting an app with stored state (they aren't sent on a reconnect), in that case I would expect that you app would probably be doing its subscriptions again anyway.
Overall I can't think of an issue with what you suggest and it might help in some situations.

**Comment by robbawebba** [comment]
@alsm I've got a quick question about this statement:
> Also this would only happen in the case that you are restarting an app with stored state (they aren't sent on a reconnect), in that case I would expect that you app would probably be doing its subscriptions again anyway.

I believe you're referring to [client.go:468](https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L468) Where we run `client.resume(false)`, false meaning we won't send any persisted subscribe packets when reconnecting. Is there any reason behind hardcoding `false` instead of using `c.options.ResumeSubs` here, so we can take advantage of this functionality?

It would've made sense for me to include this change in my PR - sorry! I would be happy to open a new PR to add that change if necessary.
