### ISSUE TITLE
Detect race condition!!!

### ISSUE THREAD

**Issue by prospero78** [eclipse/paho.mqtt.golang#362]
WARNING: DATA RACE
Write at 0x00c0002840a8 by goroutine 93:
  github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      d:/coding/golang/_home/src/github.com/eclipse/paho.mqtt.golang/client.go:446 +0x1625

Previous read at 0x00c0002840a8 by goroutine 78:
  github.com/eclipse/paho%2emqtt%2egolang.(*client).resume()
      d:/coding/golang/_home/src/github.com/eclipse/paho.mqtt.golang/client.go:786 +0xb72
  github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect()
      d:/coding/golang/_home/src/github.com/eclipse/paho.mqtt.golang/client.go:468 +0x1848

Goroutine 93 (running) created at:
  github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      d:/coding/golang/_home/src/github.com/eclipse/paho.mqtt.golang/client.go:546 +0x12d

Goroutine 78 (finished) created at:
  github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost()
      d:/coding/golang/_home/src/github.com/eclipse/paho.mqtt.golang/client.go:546 +0x12d

**Comment by MattBrittan** [comment]
Hi @prospero78,

A couple of questions:
 * Were there a lot of persisted packets stored when this happened? 
 * Are you using FileStore for persistence? (or something similar thats relatively slow)
 * How long was the connection to the MQTT broker down?

I have taken a quick look at this and think I can one way it could happen (subject to answers to the above). The resume() function could, potentially, still be running when the reconnect() function establishes a new connection and attempts to restart the main go routines (calling ```c.stop = make(chan struct{})``` at line 446 which is what causes the race).

For this to happen it would seem that ```resume``` would need to have a lot of packets queued up and/or a relatively slow persistence store. It checks the ```c.stop``` channel with every send so should finnish pretty quickly in most cases (but it does still attempt to send every packet and this could take a while if they are stored on a remote disk).

If this is the issue then I think the solution would be to:
 * Check c.stop on each iteration in ```resume``` and exit if its closed (currently the resume loop still attempts to send every persisted packet so this change could speed up the exit).
 * Use the ```workers``` ```sync.WaitGroup``` to ensure that  ```resume``` completes before ```internalConnLost``` calls ```reconnect```

**Comment by prospero78** [comment]
Thank you for the full answer. The data race log given in the post above is the result of the program launch after compilation "go build -race ...". I just started the program for execution and immediately saw this message. In general, I am quite happy with the library, which internally solves the tasks of safe multithreading, and does not shift this task to the programmer (who uses this library). I found a replacement for this library, it works as it should))

**Comment by MattBrittan** [comment]
Thanks @prospero78, I understand that you were running the library with race detection enabled; the reason for my questions is that I'm trying to confirm if issue I found is likely to be what you encountered (I use the race detector too but have not encountered this one). The extra detail in my comments were not really aimed at you (more to help me, or anyone else, submitting a pull request to get this fixed). I will probably sumbit a fix for this anyway as it's something that could potentially go wrong.

**Comment by prospero78** [comment]
The library is interesting, and I liked it. It’s just that the authorities “distribute bananas,” so I don’t have time to fix all the strange things. I apologize because there is no time to answer all your questions in detail.
