### ISSUE TITLE
Failure to queue (and persist) more than 65k messages

### ISSUE THREAD

**Issue by stoxx** [eclipse/paho.mqtt.golang#364]
There appears to be an obvious design flaw in persistence; it uses on-wire message tags as persistence-id numbers. 65k messages (that's only 20 hours of losing radio coverage with one message every second) and the id-numbers run out.

What is worse: there are no obvious errors or panics, the messages are accepted for transport, but are all presisted with id 0. When looking at the filestore, i see other files 1-65534 stay put (they are ok and safe) but o.0.msg keeps getting new timestamp.

All my test messages were 50 bytes (filesize) but somehow o.0.msg got it's size to be 49 bytes. I suspect it was corrupted, because this caused mosquitto 1.6.7 to disconnect almost immediately on reconnect/resume, and sent my client to reconnect loop where it often succesfully bursted some messages, before getting disconnected and restarting. True story, that caused a bit of mobile data to be spent.

I see fixing this is a bit of work, and would require intimate knowledge of message id allocation system and other things, therefore I'm currently seeking a solution with custom persistence in my client code.

This story was written on commit 2e9e43b5d02b.

**Comment by stoxx** [comment]
https://github.com/eclipse/paho.mqtt.golang/blob/2e9e43b5d02b38840f73bf795ddc8a266a10bf53/messageids.go#L85 seems wrong; if a free id is not available, should return error or panic. Or perhaps, as zero is never allocated otherwise, perhaps error handling is missing up the call stack. Is 65535 special? it is never allocated.

**Comment by alsm** [comment]
Thanks for reporting this, it does seem to be an issue. It probably evolved from the time before offline sending of messages when persistence was purely for handling a connection loss in a persistent session.

**Comment by alsm** [comment]
This should be resolved now. Where there are no more message ids left functions which require one will set an error on their token.
