### ISSUE TITLE
Store stuff doesn't actually work

### ISSUE THREAD

**Issue by isaacseymour** [eclipse/paho.mqtt.golang#37]
Looks like the code to persist pending outbound/inbound messages was [commented out at some point](https://github.com/eclipse/paho.mqtt.golang/blob/183329365eb3c151b3f8403f90c89cf4e21ed739/net.go#L116). It would be bring this feature back, or remove it entirely if it's not going to be supported in a future release. At the moment it's quite confusing that I'm calling `opts.SetStore(mqtt.NewFileStore("./some_directory"))` but not getting anything stored there!

**Comment by alsm** [comment]
Yeah, as it's mostly there we should look to get it enabled and working again
