### ISSUE TITLE
[Question] Why is pinger not taking account of KeepAlive value if bigger than 10 ?

### ISSUE THREAD

**Issue by Acaccia** [eclipse/paho.mqtt.golang#373]
I was actually wondering if there was a reason why "pinger" upper bound ticker is of 5 seconds ?

https://github.com/eclipse/paho.mqtt.golang/blob/962bb618da6f8f3ed6bf8024e48cc4637736001a/ping.go#L31-L35

Since I use cellular data, I would like to reduce occurrences of pings to reduce consumption.
Does it actually make sense ? I'm definitely not an expert of MQTT protocol.
If yes, is there actually a way to do it ?

Thanks

**Comment by alsm** [comment]
checkInterval is used to trifgger the check to see if we need to send a ping or not, the keepAlive value is still used to determine if the ping is actually sent. You can see how it works in the following debug output
```
[net]      logic waiting for msg on ibound
[pinger]   ping check 4.999485255
[pinger]   ping check 9.999590553
[pinger]   ping check 14.999707811
[pinger]   ping check 19.999605051
[pinger]   ping check 24.999600282
[pinger]   ping check 29.999541656
[pinger]   ping check 34.9996044
[pinger]   keepalive sending ping
[net]      Received Message
[net]      logic got msg on ibound
[net]      received pingresp
```

**Comment by Acaccia** [comment]
Oh, okay, I understand, I thought each `ping check xxxx` messages where actual ping sending.
Thank you for the answer !
