### ISSUE TITLE
Subscribe return nil, When suback qos is 0x80

### ISSUE THREAD

**Issue by chowyu08** [eclipse/paho.mqtt.golang#380]
test code 
`

	token := c.Subscribe("/02bqciur4q5aaarn/ng1inkyxeg1s9ftn/set1", 0, nil)

	fmt.Println("--", token.Wait())

	fmt.Println("--", token.Error())
`

log putput:
`

	  2019/10/29 18:00:24 [net]      received suback, id: 1

        2019/10/29 18:00:24 [net]      granted qoss [128]
  
        2019/10/29 18:00:24 [net]      logic waiting for msg on ibound
        -- true
        -- <nil>

`

client do not return error for subscribe when suback qos ==0x80(128)

**Comment by alsm** [comment]
Yeah, this was an interesting one, a subscribe can have multiple topics in it, and the subacks return success/error for each of those topics in a single response. It would be simple to have the client detect if all of the response codes in a suback are failure and set the error on the token, but less clear is what to do in the case of a mix of success and failure.
It's an open question, any thoughts welcome.

**Comment by chowyu08** [comment]
maybe add an on_subscribe_callback(client, userdata, mid, granted_qos) for user to define  success and failure.

**Comment by chowyu08** [comment]
sorry , I found `token.(*mqtt.SubscribeToken)`  ,  from this, user can get suback info.

**Comment by huanxue-shen** [comment]
@chowyu08  I have the same question，but token.(*mqtt.SubscribeToken) can't get suback info

**Comment by MattBrittan** [comment]
@huanxue-shen commenting on a closed ticket that is 2 years old is unlikely to get you a resolution. `token.(*mqtt.SubscribeToken)` should work but only if the token is a `SubscribeToken`. I'd suggest raising a new question (ideally on [Stackoverflow](https://stackoverflow.com/questions/tagged/mqtt) as this is more of a question than a problem with the library)  and include example code of your attempt to get the `SubscribeToken`.
