### ISSUE TITLE
baseToken.WaitTimeout can not return earlier even if the operation has failed with an error

### ISSUE THREAD

**Issue by stonelgh** [eclipse/paho.mqtt.golang#382]
Both baseToken.WaitTimeout and baseToken.setError acquire the lock before proceeding. It results in that baseToken.WaitTimeout can not return earlier even if the operation has failed with an error. Is it by design or a logic flaw?

**Comment by MattBrittan** [comment]
Well spotted; it looks like the mutex lock was adeded ages ago when the WaitTimeout function accessed a struct variable (.ready). As it only accesses the channel now I have submitted pull request #383 to remove the lock (and add a test that demonstrates that this fixes the issue)
