### ISSUE TITLE
break statement has no effect

### ISSUE THREAD

**Issue by jvmatl** [eclipse/paho.mqtt.golang#399]
https://github.com/eclipse/paho.mqtt.golang/blob/master/net.go#L127

this break breaks out of the switch.. which would have happened on the next line anyway -- did you mean to break out of the enclosing loop?

**Comment by MattBrittan** [comment]
I believe you are correct; this should either break out of the loop or return.

However I think the important thing is that the ```case <-c.stop:``` exists as this avoids a potential deadlock. As the connection (```c.conn```)  is always closed at the same time as ```c.stop``` the ```for``` loop should exit on the next call to ```packets.ReadPacket``` meaning that the way this has been written should not cause an issue.
