### ISSUE TITLE
Documentation not displayed on go.dev due to license restrictions

### ISSUE THREAD

**Issue by paulburlumi** [eclipse/paho.mqtt.golang#403]
The documentation on go.dev is not being displayed correctly due to license restrictions.

https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang?tab=overview

> README not displayed due to license restrictions. See our license policy.

The [license policy](https://pkg.go.dev/license-policy) states:

> If you use a package whose license is not detected, please inform the package author.

**Comment by alsm** [comment]
Showing ok now

**Comment by tt2468** [comment]
Hmm, godoc is showing me this message trying to access the docs:
![image](https://user-images.githubusercontent.com/28720189/185722183-d09d4d97-c2a4-45fb-ad3c-3cd4342cca7e.png)
