### ISSUE TITLE
Block on unsubscribe

### ISSUE THREAD

**Issue by styfstr** [eclipse/paho.mqtt.golang#409]
When I try to unsubscribe from a topic,

if token := client.Unsubscribe(valt); token.Wait() && token.Error() != nil {
     fmt.Println(token.Error())
}
Token. Wait() is blocked until mqtt client is disconnected

**Comment by MattBrittan** [comment]
Please confirm that you are using the latest code from this repository. Note that the latest release is currently 1.2.0 (19 Apr 2019) and if you are using modules then you are probably using that version; run ```go get github.com/eclipse/paho.mqtt.golang@master``` to get the latest code which includes a number of fixes.

If that is not the issue then please enable logging and provide the output (ideally along with a minimum reproducable example); the below code demonstrates that ```unsubscribe``` works in a basic example (and also shows how to enable logging).

```
func main() {
	mqtt.ERROR = log.New(os.Stdout, "[ERROR] ", 0)
	mqtt.CRITICAL = log.New(os.Stdout, "[CRIT] ", 0)
	mqtt.WARN = log.New(os.Stdout, "[WARN]  ", 0)
	mqtt.DEBUG = log.New(os.Stdout, "[DEBUG] ", 0)

	opts := mqtt.NewClientOptions().AddBroker("tcp://test.mosquitto.org:1883")

	client := mqtt.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}

	var wg sync.WaitGroup
	wg.Add(1)

	token := client.Subscribe("testtopic", 0, func(client mqtt.Client, msg mqtt.Message) {
		fmt.Printf("got \"%s\"\n", msg.Payload())
	})

	if token.Wait() && token.Error() != nil {
		panic(token.Error())
	}

	if unsubToken := client.Unsubscribe("testtopic"); unsubToken.Wait() && unsubToken.Error() != nil {
		panic(unsubToken.Error())
	}

	fmt.Println("done")
}
```

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
