### ISSUE TITLE
How to connect to cluster? 

### ISSUE THREAD

**Issue by Rebellioncry** [eclipse/paho.mqtt.golang#412]
Hello,
I'm new to golang , I have three EMQX broker in cluster and want use them properly according to docs but I cannot find any mentions of how to do, is there a way to use clustered  at all?

ps: I used clustering in Java , does this library have the same function?

Thanks in advance.

**Comment by alsm** [comment]
In the client options you can call `AddBroker(server string)` multiple times to add different endpoints for the same broker. At connect and reconnect time the client will try each endpoint in the order they were added.

**Comment by Rebellioncry** [comment]
@alsm It works,thanks
