### ISSUE TITLE
Client crashes while reconnecting

### ISSUE THREAD

**Issue by d21d3q** [eclipse/paho.mqtt.golang#419]
## steps to reproduce
* run broker (eg mosquitto)
* run client with default opts (with only one broker specified)
* subscribe to some topic
* stop broker
* observe crash
```
DEBUG    11:42:53 Connection lost: EOF
DEBUG    11:42:53 [client]   enter reconnect
DEBUG    11:42:53 [client]   about to write new connect msg
DEBUG    11:42:53 [client]   socket connected to broker
DEBUG    11:42:53 [client]   Using MQTT 3.1.1 protocol
DEBUG    11:42:53 [net]      connect started
ERROR    11:42:53 [net]      connect got error read tcp 127.0.0.1:36872->127.0.0.1:1883: read: connection reset by peer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x723a40]

goroutine 33 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).attemptConnection(0xc000174a00, 0xc00003df58, 0x2, 0x2, 0x0, 0x0)
        /home/d21d3q/go/src/github.com/eclipse/paho.mqtt.golang/client.go:381 +0x4c0
github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect(0xc000174a00)
        /home/d21d3q/go/src/github.com/eclipse/paho.mqtt.golang/client.go:297 +0xc8
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost
        /home/d21d3q/go/src/github.com/eclipse/paho.mqtt.golang/client.go:458 +0x1d7
exit status 2
```
## origin
Crash comes from [err.Error()](https://github.com/eclipse/paho.mqtt.golang/blob/5ee50844ed6468fc225e717681788a3ae247b3b6/client.go#L380) where `err` is `nil`

**Comment by MattBrittan** [comment]
Apologies - this was another issue introduced in the big refactor pulled recently (not quite sure how I managed this one!). I have submitted PR #420 which should resolve the issue. Thanks very much for the really clear error report!

**Comment by alsm** [comment]
The PR is merged, please confirm this has resolved the issue.

**Comment by d21d3q** [comment]
I placed comment [here](https://github.com/eclipse/paho.mqtt.golang/pull/420#issuecomment-625170114) - it does resolve issue.

**Comment by YiuTerran** [comment]
> I placed comment [here](https://github.com/eclipse/paho.mqtt.golang/pull/420#issuecomment-625170114) - it does resolve issue.

so, please close this issue
