### ISSUE TITLE
Paho not retrying PUBLISH when PUB ACK messages not received 

### ISSUE THREAD

**Issue by kumaya** [eclipse/paho.mqtt.golang#421]
When a QoS 1 or 2 PUBLISH message is sent by the paho client and the ACK response gets lost (e.g. due to subscribe message handler taking time to start), Paho does not resend the PUBLISH message after some amount of waiting. Only complete loss of connectivity is triggering resending unacknowledged messages.

**Comment by kumaya** [comment]
Similar to [paho.mqtt.c issue](https://github.com/eclipse/paho.mqtt.c/issues/651)

**Comment by MattBrittan** [comment]
I believe that the current behaviour complies with the spec (for MQTT 3.1.1 - I have not looked at earlier versions; see below).

Its not something that this package currently supports. Implementing it would probably not be too difficult; you would probably want to hold the last attempt time in [messageIds](https://github.com/eclipse/paho.mqtt.golang/blob/master/messageids.go#L28) (or the [PublishToken ](https://github.com/eclipse/paho.mqtt.golang/blob/master/token.go#L143) referenced via ```messageIds```) and periodically check if a retry is needed (perhaps from [IncommingComms](https://github.com/eclipse/paho.mqtt.golang/blob/master/net.go#L136)) but would need to take into account disconnects and not attempt to transmit too much at once.

---

In the section 4.4 ("Message delivery retry") of the [MQTT 3.11 spec](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718103) it says:

> When a Client reconnects with CleanSession set to 0, both the Client and Server MUST re-send any unacknowledged PUBLISH Packets (where QoS > 0) and PUBREL Packets using their original Packet Identifiers [MQTT-4.4.0-1]. This is the only circumstance where a Client or Server is REQUIRED to redeliver messages.

> Non normative comment
> Historically retransmission of Control Packets was required to overcome data loss on some older TCP networks. This might remain a concern where MQTT 3.1.1 implementations are to be deployed in such environments.
> 

This is mentioned in the C [clients source](https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTAsync.h#L1133):

```
/**
	 * The time interval in seconds after which unacknowledged publish requests are
	 * retried during a TCP session.  With MQTT 3.1.1 and later, retries are
	 * not required except on reconnect.  0 turns off in-session retries, and is the
	 * recommended setting.  Adding retries to an already overloaded network only
	 * exacerbates the problem.
	 */
	int retryInterval;
```

**Comment by alsm** [comment]
As per Matt's comment this is intended behaviour and spec compliant
