### ISSUE TITLE
Publish stalls if client is in connecting state

### ISSUE THREAD

**Issue by phoenix147** [eclipse/paho.mqtt.golang#43]
Hi!

I'm developing an application that connects to a lot of different brokers. For this it needs to handle the unavailability of brokers and take necessary actions.

I've ran into a problem regarding publishing messages. If you try to connect to a client with AutoReconnect = true (which is the default), the client will be in connecting state, even if the connect fails.

If you try to publish a message with this client, the application will stall.
This is because the isConnected method returns true if AutoReconnect is true and the connection status is > disconnected, which is true for every client that tried connecting at least once.

The only way to prevent this is to set AutoReconnect to false and handle reconnects manually or to disconnect the client after a failed attempt to connect.

Here is an example code to reconstruct the issue:

```golang
package main

import (
    "fmt"
    "log"
    "os"
    "time"

    "github.com/eclipse/paho.mqtt.golang"
)

func main() {
	mqtt.DEBUG = log.New(os.Stdout, "", 0)
	mqtt.ERROR = log.New(os.Stdout, "", 0)

	// Set some broker that is not reachable
	opts := mqtt.NewClientOptions().AddBroker("tcp://notreachable:1883").SetClientID("gotrivial")

	c := mqtt.NewClient(opts)

	// Connect should and will fail
	if token := c.Connect(); token.Wait() && token.Error() != nil {
		fmt.Println(token.Error())
	}

	// Check if client is connected and if yes, send message
	if (c.IsConnected()) {

		// SHOULD NOT GO HERE, BUT DOES
		fmt.Println("publishing message")
		token := c.Publish("testtopic", 0, false, "testmessage")

		// WILL NEVER GO HERE IF BROKER IS NOT REACHABLE
		fmt.Println("waiting for publish to complete")
		token.WaitTimeout(time.Second*5)
		fmt.Println("publish finished")
	}

	fmt.Println("Disconnecting")
	c.Disconnect(250)

	time.Sleep(1 * time.Second)
}
```

I would suggest to integrate a new method like isReachable() or to modify the isConnected() method.

**Comment by alsm** [comment]
I think this is just an error in the code, if we fail to make a connection to any of the servers given in the initial connect() as you've noticed the token.Error is set but state is left as connecting, but actually in the code we aren't trying to connect again, the autoreconnect feature is only designed to try and make it seamless when you've lost an already existing connection, I think it's better (and certainly the planned) behaviour to error out and do nothing if we couldn't make any initial connection. This should now be the behaviour with https://github.com/eclipse/paho.mqtt.golang/commit/0f7a459f04f13a41b7ed752d47944528d4bf9a86

**Comment by phoenix147** [comment]
This works for me! Thank you!
