### ISSUE TITLE
msgRouter do not dispatch incoming message when reconnected

### ISSUE THREAD

**Issue by haowanxing** [eclipse/paho.mqtt.golang#433]
I did a lot of tests to locate the problem. Finally, I found that the reason why I couldn't receive the message after reconnection was that the router didn't consume the incoming message(client.incomingPubChan).

![image](https://user-images.githubusercontent.com/7816296/85534755-2dc2e480-b644-11ea-8d6b-89d6c4f13ebc.png)

And then I found that the root cause of this problem was that the channel(router.stop) was permanently turned off.

Is that a bug or is it my wrong way of using it?

```
// pseudo code
opts := MQTT.NewClientOptions().
	AddBroker(host).
	SetClientID(clientId).
	SetUsername(username).
	SetPassword(password).
	SetCleanSession(true).
	SetOnConnectHandler(func (client MQTT.Client){
		client.Subscribe(...)
	}).
	SetAutoReconnect(true).
	SetKeepAlive(time.Second * 60).
	SetConnectTimeout(time.Second * 5)
client = MQTT.NewClient(opts)
client.Connect()
// when connected. wait for 5s  (during this. Can receive messages)
client.Disconnect(0)
// wait for 2s
client.Connect()
// after this. Message not processed correctly

```

Looking forward to your reply.  Best wish

**Comment by MattBrittan** [comment]
Hi @haowanxing 

The last release (1.4.0), which I suspect you are using, was released over a year ago and there have been numerious fixes since. Please try the latest code (```go get github.com/eclipse/paho.mqtt.golang@master```) in which the handling of incomming messages has been rewritten (hopefully there will be a new release in the near future).

Regards,
Matt

**Comment by haowanxing** [comment]
Thank you. @MattBrittan 

As you said, I used the version (v1.2.0) released a year ago.

Following your advice. I update the go.mod file content to change the version of `paho.mqtt.golang` to `master` which is finally shows "v1.2.1-0.20200609161119-ca94c5368c77"

In the end, the problem was solved. Thank you very much! :smile:
