### ISSUE TITLE
ConnectTimeout documentation is wrong

### ISSUE THREAD

**Issue by leventov** [eclipse/paho.mqtt.golang#437]
In options.go, it says the default timeout is 30 seconds. This is not so. The same thing was fixed for WriteTimeout in this commit: https://github.com/eclipse/paho.mqtt.golang/commit/d24d1cc39f51e1b3b90361548a0b59a47af3a465

**Comment by MattBrittan** [comment]
Looking at ```options.go``` in the [master branch](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L95) I see:

```
//   ConnectTimeout: 30 (seconds)
```

Then the [default is set](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L115):
```
ConnectTimeout:          30 * time.Second,
```

and the [comment for the setter](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L325):

```
// SetConnectTimeout limits how long the client will wait when trying to open a connection
// to an MQTT server before timing out and erroring the attempt. A duration of 0 never times out.
// Default 30 seconds. Currently only operational on TCP/TLS connections.
func (o *ClientOptions) SetConnectTimeout(t time.Duration) *ClientOptions {
```

So this looks correct to me?

Regards,
Matt

**Comment by deadprogram** [comment]
It also looks correct to me from examining the current release branch.

The default value of 30 seconds is set here: 
https://github.com/eclipse/paho.mqtt.golang/blob/ca94c5368c77af55b2418768a7c55f6430839779/options.go#L115

That value is passed to open the network connect here: https://github.com/eclipse/paho.mqtt.golang/blob/ca94c5368c77af55b2418768a7c55f6430839779/client.go#L358

Which then is passed to call either `net.DialTimeout()` here: https://github.com/eclipse/paho.mqtt.golang/blob/ca94c5368c77af55b2418768a7c55f6430839779/netconn.go#L45

Or else used for `net.Dialer{Timeout: timeout}` here in the case of a TLS connection: https://github.com/eclipse/paho.mqtt.golang/blob/ca94c5368c77af55b2418768a7c55f6430839779/netconn.go#L67

**Comment by MattBrittan** [comment]
Closing this because the current documentation appears correct. Please feel free to reopen with further information.
