### ISSUE TITLE
Add cookie jar option to websocket options

### ISSUE THREAD

**Issue by nejtr0n** [eclipse/paho.mqtt.golang#456]
Please provide cookie jar option to websocket connection.
I've created PR.
https://github.com/eclipse/paho.mqtt.golang/pull/448/files

**Comment by MattBrittan** [comment]
Thanks for the pull request - unfortunately it does not appear to have passed the automated Eclipse Contributor Agreement (ECA) check.  Getting it to pass this check is likely to speed up acceptance; see this [article](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git) for info. To pass all contributors need to have signed the agreement (your pull request has a number of commits from two authors;) and all commits need to include a "Signed-off-by" entry (detailed in the article). I believe you can add this by checking out the commit and running `git commit --amend --signoff`. 
Note that @alsm is the only one active committer and (I am going through the setup process).

**Comment by MattBrittan** [comment]
Closing this issue because the commit cannot be accepted without an ECA.
