### ISSUE TITLE
Token Interface and Context

### ISSUE THREAD

**Issue by teivah** [eclipse/paho.mqtt.golang#463]
Hello guys,

First of, thanks for this cool library.
There is one thing that I think could be improved is the `Token` interface. In my opinion, both `Wait` and `WaitTimeout` methods are missing a context as a parameter.

Let's consider a simple use case where we expose a REST API. This API is going to call the Paho library and the `Publish` method. 
While exposing an API in Go, we are going to inherit a context. Thus, while calling `Publish` and getting a `Token`, we should have the capability to stop `WaitTimeout`:
* Either when there is a timeout
* Or the parent context has been cancelled

Most of the IO libraries are accepting a context as an input to deal with such a use case.
Do you believe it would make sense? If yes I could handle the PR, it would be pretty much easy.

**Comment by MattBrittan** [comment]
Hi @teivah,

`Done() <-chan struct{}` was added to `Token` recently so you can just use that i.e. (with `token` in `t`)..

```
select {
case <-t.Done():
   break
case <-ctx.Done():
   return errors.New("Context done")
}
err = t.Err()
```

I doubt that`context` will be added to `Wait`/`WaitTimeout` - these functions were created before the `context` package was introduced, the above alternative works, and `context` would be a bit confusing (the context could cancel the wait but not the operation itseld).

Matt

**Comment by teivah** [comment]
Hey @MattBrittan, I didn't notice, I was using the latest released version, not the one from master. Good to know though, it is an answer to my problem.
Thanks

**Comment by MattBrittan** [comment]
I believe that @master is currently more stable than @1.2.0 so would suggest using it (it includes a fairly major rewrite of the network code and lots of fixes). We hope to have a new release out shortly.
