### ISSUE TITLE
Reconnection memory resources are not freed

### ISSUE THREAD

**Issue by cappuccino5** [eclipse/paho.mqtt.golang#467]
In the case of network instability, the resource cannot be released before connecting MQTT again. This is the test result of using Pprof. What should I do?

`
goroutine 268 [select, 124 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1423440, 0x15e0330, 0x1490f00, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 284 [select, 118 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x14233c0, 0x15e00f0, 0x1491040, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 316 [select, 106 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1423000, 0x15e04e0, 0x14912c0, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 450 [select, 65 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d180, 0x15e0840, 0x1491b80, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 610 [select, 5 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x161e1c0, 0x15e0c60, 0x157a8c0, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 382 [select, 88 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155c040, 0x15e03c0, 0x1491680, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 398 [select, 82 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1423d00, 0x15e0720, 0x14917c0, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 414 [select, 78 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155c840, 0x15e06f0, 0x1491900, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 546 [select, 28 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d4c0, 0x15e0b10, 0x157a3c0, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 613 [select, 1 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.alllogic(0x157a8c0)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/net.go:240 +0x1d8
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/client.go:320 +0x5f8

goroutine 466 [select, 59 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d2c0, 0x15e0870, 0x1491cc0, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 482 [select, 53 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d480, 0x15e0960, 0x1491e00, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 498 [select, 46 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d600, 0x15e0990, 0x157a000, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 514 [select, 40 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d7c0, 0x15e09c0, 0x157a140, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 530 [select, 34 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x155d780, 0x15e0750, 0x157a280, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 612 [select, 5 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.errorWatch(0x157a8c0)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/net.go:346 +0xe0
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/client.go:319 +0x5d4

goroutine 594 [select, 11 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1423f00, 0x15e0bd0, 0x157a780, 0x3c5801)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/router.go:143 +0x68

goroutine 614 [select, 5 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.outgoing(0x157a8c0)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/net.go:171 +0x1ec
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/client.go:321 +0x61c

goroutine 609 [select]:
github.com/eclipse/paho%2emqtt%2egolang.keepalive(0x157a8c0)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/ping.go:41 +0x210
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v0.0.0-20190322152051-20337d8c3947/client.go:306 +0x92c`

**Comment by cappuccino5** [comment]
hello:
This doesn't seem to have freed the matchAndDispatch Func, which is how my client implements it
func (b *Backend) reconnectLoop() {
	if b.auth.ReconnectAfter() > 0 {
		for {
			if b.closed {
				break
			}
			time.Sleep(b.auth.ReconnectAfter())
			log.Info("mqtt: re-connect triggered")

			b.disconnect()
			b.connectLoop()
		}
	}
}


func (b *Backend) disconnect() error {
	mqttEventCounter("disconnect")

	b.Lock()
	defer b.Unlock()

	b.conn.Disconnect(250)
	return nil
}


func (b *Backend) connectLoop() {
	for {
		if err := b.connect(); err != nil {
			log.WithError(err).Error("mqtt: connection error")
			time.Sleep(time.Second * 2)

		} else {
			break
		}
	}

// Backend implements a MQTT backend.
type Backend struct {
	sync.RWMutex

	auth                     auth.Authentication
	conn                     paho.Client
	closed                   bool
	clientOpts               *paho.ClientOptions
	downlinkFrameChan        chan gw.DownlinkFrame
	gatewayConfigurationChan chan gw.GatewayConfiguration
	gateways                 map[lorawan.EUI64]bool // the bool indicates if the gateway must always be subscribed
	topicHandlers            []topicHandler

	qos              uint8
	uplinkTemplate   *template.Template
	downlinkTemplate *template.Template
	statsTemplate    *template.Template
	ackTemplate      *template.Template
	configTemplate   *template.Template

	marshal   func(msg proto.Message) ([]byte, error)
	unmarshal func(b []byte, msg proto.Message) error
}

``

**Comment by MattBrittan** [comment]
Please confirm which version of the package you are using. In the latest (1.3.0) line 145 of `matchAndDispatch` is in the middle of an `if` statement so seems an unlikely place to block; in the much older v1.2.0 it's a `select` so I expect you are using an old version (To be fair I only released 1.3 a week ago but 1.2 is 18 months old now).

`1.3.0` includes a major rewrite of the comms code which aimed to remove a lot of issues like this so if you are on `1.2.0` I'd suggest upgrading. I believe that 1.3.0 shuts everything down when `Disconnect` is called and it's probably OK to reuse the client (possibly safer to dispose of it and create another as I have not tested this) - that was definitely not the case with 1.2.0.

In terms of reconnecting I'd suggest using the built in functionality unless you are trying to do something special (see [this example](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/docker/subscriber/main.go#L102)). I have machines that have been running for 6 months on very unstable connections without issue.

**Comment by cappuccino5** [comment]
hello 
Look at the go mo  ,The version I'm using is
 github.com/eclipse/paho.mqtt.golang v0.0.0-20190322152051-20337d8c3947

I don't know the exact version number

**Comment by MattBrittan** [comment]
That is pre `1.1.0` (commit date  Mar 23, 2019) - please update to `v1.3.0` and let me know if the issue persists.

**Comment by cappuccino5** [comment]
1.I tested the problem with V1.2.0 and it still exists,After 12 hours of testing, Reconnection increases when the network is disconnected.
2.I tested for 1 hour with V1.3.0 and found no such phenomenon,From the log it looks like every time you create it it goes to the goroutine before you release it
3.The premise of the test is that my client processing has not made any changes.
remark:My question is has this phenomenon been resolved in version 1.2.0?Because we want to use it


V1.2.0  testing 
goroutine 4161 [select, 613 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x119d480, 0x10f8f00, 0x10eeb40, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4361 [select, 602 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x101dc40, 0x1047200, 0x10eec80, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4424 [select, 600 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1155b40, 0x11522a0, 0x10eedc0, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4593 [select, 592 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x114e9c0, 0x1152a50, 0x10eef00, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 13520 [select, 181 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1342680, 0x117f170, 0x12ba780, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4726 [select, 586 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x101d100, 0x1046db0, 0x10ef180, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4816 [select, 582 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x119dc40, 0x117fda0, 0x10ef2c0, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4932 [select, 576 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x1154140, 0x1046ff0, 0x10ef400, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68

goroutine 4998 [select, 574 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1(0x119de00, 0x117e0f0, 0x10ef540, 0x3c5701)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:145 +0x3a8
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/router.go:143 +0x68


	
	
V1.3.0  testing 
goroutine 542 [chan receive, 4 minutes]:
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch(0x1047dd0, 0x101d200, 0x1, 0x1088500)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.0/router.go:135 +0x33c
github.com/eclipse/paho%2emqtt%2egolang.(*client).startCommsWorkers.func1(0x1088500, 0x101d200)
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.0/client.go:504 +0x54
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).startCommsWorkers
	/home/go/path/dev.risinghf.com/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.0/client.go:503 +0x1f4

**Comment by cappuccino5** [comment]
Thank you very  very very  very much !!

**Comment by MattBrittan** [comment]
`1.2.0` is 18 months old and major refactoring was undertaken for `1.3.0` (to simplify the comms code and avoid this kind of issue). Because of this I don't envision anyone taking the time to attempt to resolve the issue with `1.2.0` (but you are welcome to do so!).

`1.3.0` resoles this and a significant number of other issues; for most users it should be a drop in replacement so I'd recommend that you update (see the [release info](https://github.com/eclipse/paho.mqtt.golang/releases/tag/v1.3.0) for a list of changes). Please note that a lot of users have been following `@master` to avoid issues with `1.2.0` so the new release is better tested than it may appear based on the time since release.

**Comment by cappuccino5** [comment]
ok  Thank you,I will be testing with V1.3.0 for a while

**Comment by MattBrittan** [comment]
Great - Please do let me know if you encounter any issues. I'll close this issue for now because you mentioned that it is resolved in `v1.3.0`.
