### ISSUE TITLE
Deadlocks in library when not wrapping callbacks in goroutine

### ISSUE THREAD

**Issue by bartmeuris** [eclipse/paho.mqtt.golang#474]
Split from #473

> @bartmeuris - please raise this as a separate issue (without additional information its not possible to ascertain if these have the same cause so its simpler to assume they differ).
> 
> Given that your code was working with `1.2.0` its most likely your issue is due to the change mentioned in the [release notes](https://github.com/eclipse/paho.mqtt.golang/releases/tag/v1.3.0):
> 
> > Note that [this commit](https://github.com/eclipse/paho.mqtt.golang/commit/782a0f6f87cc9dedb511cbfa8ea6f064590d7836) changes internal message channels from buffered to unbuffered and may impact users who publish from within a message handler (the documentation has been updated to highlight the issue; running potentially blocking operations within a message handle has always been problematic).
> 
> The section of the logs you included (from Ctrl-C press) gives some indications this may be the case (there is no `matchAndDispatch exiting`). Unfortunately you have not included enough of the log to draw any further conclusions (`pingresp not received, disconnecting` is a symptom; the cause will most likely be earlier in the logs).

With 1.3.0, without code changes, I get publishes and subscriptions, pings (handled by the library) and the closing of the connection that hangs and stops working. It's indeed related to different library behavior. 

My use case is the following: I do device discovery, and subscribe on one announce topic where all devices publish their discovery messages. When I receive a message there, depending on the device type, I subscribe on more specific topics depending on the device type within that callback. I tried wrapping this callback in a go routine, and this seems to have fixed everything.

Would it be an idea to just always call the callbacks in a go-routine? This shouldn't be an issue since the callbacks don't return any values, and the whole thing is supposed to be async anyway. This is currently really counter-intuitive behavior, can completely break existing applications, is virtually impossible to debug from the application side without in-depth knowledge of how the library works internally, what might be blocking or non-blocking there, and breaks completely unrelated things like publishing messages in non-blocking paths.

**Comment by MattBrittan** [comment]
> Would it be an idea to just always call the callbacks in a go-routine? ...the whole thing is supposed to be async anyway...

If you set order matters to false `ClientOptions.SetOrderMatters(false)` then that is what happens. With order matters set to `true` (the default) the library waits for the handler to return before proceeding (this predates my involvement; I would assume the rationale is that the `ACK` should not be sent before the handler completes). 

>This is currently really counter-intuitive behavior, can completely break existing applications, is virtually impossible to debug from the application side without in-depth knowledge of how the library works ...

I agree and mentioned it in the release notes and the readme in an effort to raise visibility of the potential issues. I have been toying with the idea of changing the default for `order` to `false` but am concerned that this may be too much of a breaking change. I'm not sure how many applications rely upon this default (for this to be useful you would also need to configure the broker i.e. `max_inflight_messages=0` in Mosquitto). Would appreciate feedback on this.

I suspect that the blocking is an unintended consequence of making the channel unbuffered and agree that its not ideal (the [change](https://github.com/eclipse/paho.mqtt.golang/commit/782a0f6f87cc9dedb511cbfa8ea6f064590d7836) was made over a year ago). However using a buffered channel did hide some potential issues and made them even more difficult to diagnose (I suspect this, and simplifying the code, was the rationale for the original change).

**Comment by bartmeuris** [comment]
I see. This for me is just used in a toy-project at the moment, so I'm not sure my use-case is really that representative. Order doesn't usually matter to me, but there are probably scenarios where it would.

This is just a brainfart, but maybe the way the subscriptions are registered can be extended, so you can choose between a sync and async subscription, which could have different callback signatures, where the sync-one could return a ack/nack?

Also, ideally the async-one should have the possibility to send an ack/nack itself? Not sure if that would be possible, and might also make stuff a bit less intuitive. You could then wrap this in a go-routine, which could send an ack if no ack/nack was sent by the callback itself after it finishes or something?

Not sure if that's even possible and I'm making wrong assumptions, don't know anything about the low-level mqtt protocol details :)

**Comment by MattBrittan** [comment]
Thanks for the suggestion; unfortunately I don't think anyone is keen to make major changes to this package (would prefer to focus on the new MQTT5 package which has a completely different interface). The package does currently allow users to send the `ACK` but if they don't do so it is automatically returned when the handler exits so it's not all that useful. The `ACK` should acknowledge that the packet has been received, its not really intended to confirm that your application has processed it (the wording in [the spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref384138490) is "having accepted ownership of the Application Message ").

"Order doesn't usually matter to me"; it takes a bit of configuration if you want to ensure ordered delivery (QOS 1+, `max_inflight_messages=1`) and this significantly slows message delivery (because the broker needs to wait for an acknowledgement before sending the next message). I may just update the documentation to recommend that users call `ClientOptions.SetOrderMatters(false)` (worried that changing the default will break other things; such as handlers that do not support simultaneous execution).

**Comment by MattBrittan** [comment]
I have updated the documentation (only in @master currently so use https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang@master to view), readme and docker example to reflect this. Hopefully these changes will reduce the chance of future users encountering this issue.

**Comment by MattBrittan** [comment]
Closing this issue because I believe the updated documentation addresses the concern raised.

**Comment by MattBrittan** [comment]
Closing this issue because I believe the updated documentation addresses the concern raised.

**Comment by winngz** [comment]
Regarding the phrasing
> callback must be safe for concurrent use by multiple goroutines.

Would it be more precise to write

> If options.OrderMatters is false then callback must be safe for concurrent use by multiple goroutines.

Or is unsafe callback something the library doesn't support even in the orderMatters=true case?

**Comment by MattBrittan** [comment]
> Would it be more precise to write

Yep - if `options.OrderMatters` is `true` then the handlers are called sequentially (assuming they are only used with one `client`).
