### ISSUE TITLE
If a type is concurrency-safe, its documentation should state that explicitly

### ISSUE THREAD

**Issue by miham** [eclipse/paho.mqtt.golang#476]
It would be nice if types that are safe for concurrent use by multiple goroutines would state that in their documentation. That way the API user wouldn't have to spend time figuring out what exactly is concurrency-safe by browsing the source code. In particular: Is mqtt.Client concurrency-safe?

For example, package net/http (https://pkg.go.dev/net/http) in Go's standard library documents concurrency-safe types in the following way:

- For interfaces: "Implementations of {interface-name} must be safe for concurrent use by multiple goroutines." 
- For structs: "{struct-name}s are safe for concurrent use by multiple goroutines".

**Comment by MattBrittan** [comment]
I have add the requested comments; mqtt.Client should be concurrency-safe (but some of the code is fairly complex so there is always the possibility of a bug!).

**Comment by MattBrittan** [comment]
Note: as change is not yet in a release use `https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang@master` to view (may not include the latest small update).

**Comment by MattBrittan** [comment]
Closing this as the requested change was made.
