### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by dh1tw** [eclipse/paho.mqtt.golang#48]
Hi, 

the example at https://eclipse.org/paho/clients/golang/ is broken. 

The following error is returned during compilation:

`go-projects/src/mqttTest/main.go:15: cannot use func literal (type func(*mqtt.Client, mqtt.Message)) as type mqtt.MessageHandler in assignment`

This is easily reproducible - just copy & paste the example code into a new project and try compiling it.

I'm using go 1.6.2 linux/arm

**Comment by houssemFat** [comment]
Hi,
please use this library `git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git` with the same example instead of the official website

https://godoc.org/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git

**Comment by alsm** [comment]
Thanks, the paho page is being updated atm, I'll make sure the example is updated to work with the current library. The github repo is the canonical library, the git.eclipse.org is still there for historical reasons atm but will be going away/redirected to this one.

**Comment by alsm** [comment]
I've pushed the change to the example, it should show up shortly.

**Comment by vishnutm** [comment]
Sorry to Reopen the issue. I got the same issue while am trying out this. could you please share an example because the above now expired it
