### ISSUE TITLE
validateTopicAndQos improvements

### ISSUE THREAD

**Issue by cravler** [eclipse/paho.mqtt.golang#483]
Can we improve [validateTopicAndQos](https://github.com/eclipse/paho.mqtt.golang/blob/master/topic.go#L75) ?
I need this ability:
```go
// topic := "demo/#/"
// topic := "demo/#/?foo=bar"

levels := strings.Split(topic, "/")
for i, level := range levels {
    if level == "#" && i != len(levels)-1 {
        str := levels[len(levels)-1]
        if "" != str && !strings.HasPrefix(str, "?") {
            return ErrInvalidTopicMultilevel
        }
    }
}
```

**Comment by alsm** [comment]
This is not possible, the spec says in section 4.7.1.2

The multi-level wildcard character MUST be specified either on its own or following a topic level separator. In either case it MUST be the last character specified in the Topic Filter
