### ISSUE TITLE
all_proxy 环境变量与golang.org\x\net\proxy\proxy.go中的不统一

### ISSUE THREAD

**Issue by getbuguai** [eclipse/paho.mqtt.golang#486]
github.com\eclipse\paho.mqtt.golang@v1.3.2\netconn.go 中的 64--72 行的代码

```
	case "ssl", "tls", "mqtts", "mqtt+ssl", "tcps":
		allProxy := os.Getenv("all_proxy")
		if len(allProxy) == 0 {
			conn, err := tls.DialWithDialer(&net.Dialer{Timeout: timeout}, "tcp", uri.Host, tlsc)
			if err != nil {
				return nil, err
			}
			return conn, nil
		}
		proxyDialer := proxy.FromEnvironment()
```

其中的 allProxy := os.Getenv("all_proxy") 中的 all_proxy 与 proxyDialer := proxy.FromEnvironment() 中获取的

golang.org\x\net@v0.0.0-20200425230154-ff2c4b7c35a0\proxy\proxy.go 中的 allProxyEnv 环境变量不统一

```
allProxyEnv = &envOnce{
		names: []string{"ALL_PROXY", "all_proxy"},
	}
```

建议:

>  兼容 golang.org\x\net@v0.0.0-20200425230154-ff2c4b7c35a0\proxy\proxy.go 中的环境变量参数

**Comment by MattBrittan** [comment]
Sorry - I'm not sure that any regular contributor speaks Chinese so it's unlikely we will be able to assist without a translaton. I suspect your suggestion is that we use the `x\net` codes technique for handling the proxy environment variable (effectively adding support for `ALL_PROXY`); happy to accept a pull request making this change (but see it as a new feature).

**Comment by MattBrittan** [comment]
Closing this because it is still unclear what is being requested.
