### ISSUE TITLE
Dup flag not set on re-transmission of pending publish

### ISSUE THREAD

**Issue by jhhurwitz** [eclipse/paho.mqtt.golang#487]
Hello. First of all, thank you for the great library.

**Bug Report**

**Version**: v1.2.0

**Problem**: When the mqtt client is disconnected with pending publishes that have not received a corresponding ack, the publishes are retried on reconnect but the DUP flag is not set. This DUP requirement is specified in [MQTT-3.3.1.-1].

**Reproduce**: 
1. Send a QOS 1 message with a shorter wait timeout than the ack response
2. Disconnect the client
3. Reconnect the client

Thanks,

Jordan

**Comment by MattBrittan** [comment]
You are correct; no attempt is made to set the DUP flag and this does mean that we are not in compliance with the spec. There are two ways that this could be handled:

1. Set the DUP flag for any PUBLISH message sent in resume() with QOS1+
2. Update the store after a message has been written to the connection so DUP will be set if its retried

Neither of these are ideal. Option 1 may result in messages being transmitted with DUP=true despite not having been sent previously (for example if `Publish` is called whilst the client is connecting/reconnecting). Option 2 would require that the store be updated after each message has been transmitted (extra overhead and a bit of work to implement). 

I suspect that option 1 may be sufficient (the spec says "If the DUP flag is set to 1, it indicates that this *might* be re-delivery of an earlier attempt to send the Packet.") but I am not sure how this will impact the broker processes in reality (given that "The recipient of a Control Packet that contains the DUP flag set to 1 cannot assume that it has seen an earlier copy of this packet.").

**Comment by jhhurwitz** [comment]
I would say option 1 sounds good to me. 

According to the [mqtt 3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) the DUP flag only denotes probable duplication:

"If the DUP flag is set to 0, it indicates that this is the first occasion that the Client or Server has attempted to send this MQTT PUBLISH Packet. If the DUP flag is set to 1, it indicates that this might be re-delivery of an earlier attempt to send the Packet."

Which sounds inline with the solution proposed.

**Comment by MattBrittan** [comment]
I have implement this in @master (`go get github.com/eclipse/paho.mqtt.golang@master`). Please note that I don't think this will have the result you are expecting (I have verified that the broker is receiving the packet with the DUP flag set; however it may well determine that it has not seen the packet before and sent it on without the DUP flag set).

**Comment by jhhurwitz** [comment]
Appreciate the fast follow-up here. All I care about is that the packet has the correct dup flag when it gets to the broker. So this looks great. Thanks so much.

**Comment by MattBrittan** [comment]
Great - closing this off (feel free to reopen if the change does not address the issue).
