### ISSUE TITLE
Improve error reporiting in NewWebsocket

### ISSUE THREAD

**Issue by TomasVojacek** [eclipse/paho.mqtt.golang#493]
NewWebsocket return error "websocket: bad handshake" without any details.
Gorila websocket return error "websocket: bad handshake" and  details are in response object.
NewWebsocket is omitting response object and thus hidding cause of error.
https://github.com/eclipse/paho.mqtt.golang/blob/18bfbdece2e98c020293755a3468bf510a7b2497/websocket.go#L41
Would it be possible to get more details? 

	ws, res, err := dialer.Dial(host, requestHeader)

	if err != nil {
		if res!=nil{
			DEBUG.Println(CLI,res.Status)
		}
		return nil, err
	}

**Comment by MattBrittan** [comment]
You are linking to a commit made 5th May 2020; the change you are requesting was already made in [this commit](https://github.com/eclipse/paho.mqtt.golang/commit/4c64ea82d6ee01f8dd7359006a769f9051ad04b0) on 19th Jun 2020..

**Comment by TomasVojacek** [comment]
Sorry did not checked closed issues and release 1.3.2 is from January 2021 I did not expect changes since it. Looking forward to next release.

**Comment by MattBrittan** [comment]
Have made a new release (I also missed the fact that this had already been done because I'd not updated my local repo).
