### ISSUE TITLE
Redact password in Stringer of `packets.ConnectPacket`

### ISSUE THREAD

**Issue by besedad** [eclipse/paho.mqtt.golang#499]
Return value of `String()` is not safe to use because it may contain unredacted password. If not careful, a password may leak out to logs and subsequently spread to other channels. I propose to modify the Stringer to replace any non-empty string with `<redacted>`. I'll follow up with a pull-request if the issue gets accepted.

**Comment by MattBrittan** [comment]
This is mainly intended for use when testing (and including the password could allow the user to spot an issue). Having said that I can see how this lead to the password leaking into logs so have no issue with your proposed change.
