### ISSUE TITLE
How can i get client struct conn attributes

### ISSUE THREAD

**Issue by SPuerBRead** [eclipse/paho.mqtt.golang#510]
conn attributes is private property, i try use unsafe.Pointer but failed, how can i get client struct conn attributes,is any object can get this attributes
```
type client struct {
	lastSent        atomic.Value // time.Time - the last time a packet was successfully sent to network
	lastReceived    atomic.Value // time.Time - the last time a packet was successfully received from network
	pingOutstanding int32        // set to 1 if a ping has been sent but response not ret received

	status       uint32 // see const definitions at top of file for possible values
	sync.RWMutex        // Protects the above two variables (note: atomic writes are also used somewhat inconsistently)

	messageIds // effectively a map from message id to token completor

	obound    chan *PacketAndToken // outgoing publish packet
	oboundP   chan *PacketAndToken // outgoing 'priority' packet (anything other than publish)
	msgRouter *router              // routes topics to handlers
	persist   Store
	options   ClientOptions
	optionsMu sync.Mutex // Protects the options in a few limited cases where needed for testing

	conn   net.Conn   // the network connection, must only be set with connMu locked (only used when starting/stopping workers)
	connMu sync.Mutex // mutex for the connection (again only used in two functions)

	stop         chan struct{}  // Closed to request that workers stop
	workers      sync.WaitGroup // used to wait for workers to complete (ping, keepalive, errwatch, resume)
	commsStopped chan struct{}  // closed when the comms routines have stopped (kept running until after workers have closed to avoid deadlocks)
}
```

**Comment by MattBrittan** [comment]
As you say `conn` is private; this is deliberate because the connection is managed by the library (using the connection outside of the library is likely to break things).

If you can explain why you need access to this then I'd consider incorporating a solution into the library but would be reluctant to make `conn` public.  Failing that I'd suggest forking the library and adding a getter.

**Comment by SPuerBRead** [comment]
> As you say `conn` is private; this is deliberate because the connection is managed by the library (using the connection outside of the library is likely to break things).
> 
> If you can explain why you need access to this then I'd consider incorporating a solution into the library but would be reluctant to make `conn` public. Failing that I'd suggest forking the library and adding a getter.

 I want use peerCertificates to get server certificates and do some check

**Comment by MattBrittan** [comment]
I believe the standard way to do that is to set `VerifyPeerCertificate` in the `tls.Config` that you pass the library. Because the library supports automatic reconnection etc working directly with the `conn` is likely to be problematic.

**Comment by SPuerBRead** [comment]
> I believe the standard way to do that is to set `VerifyPeerCertificate` in the `tls.Config` that you pass the library. Because the library supports automatic reconnection etc working directly with the `conn` is likely to be problematic.

Thank you for your guidance. I didn’t notice that I can customize the callback function here.
