### ISSUE TITLE
How to allow untrust certificate

### ISSUE THREAD

**Issue by Kowiste** [eclipse/paho.mqtt.golang#516]
I'm in localhost trying to  connect to my mqtt using secure  websocket, I'm using  self signed certificate  so  I have  this error:

x509: certificate signed by unknown authority

There is  any option to allow untrusted certificate?

**Comment by MattBrittan** [comment]
Please see the [ssl demo](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/ssl/main.go#L88).
