### ISSUE TITLE
[bug] auto-reconnect hangs on first attempt.

### ISSUE THREAD

**Issue by brycereitano** [eclipse/paho.mqtt.golang#52]
Auto-reconnect seems to be hanging when attempting to reconnect to a SSL host with credentials. Using latest master for the golang client and using 1.4.9 mosquitto. There is a loadbalancer in front of it forwarding 1883 to it, and forwarding 8883 with enforced ssl.
Edit: I just attempted with an non-SSL connection, and same issue arrises. 

This is my method of connecting. 
```go
	opts := mqtt.NewClientOptions()
	opts.AddBroker(secureMQTTHost)
	opts.SetCleanSession(false)
	opts.SetAutoReconnect(true)
	opts.SetUsername(username)
	opts.SetPassword(password)
	if config.DebugMode {
		mqtt.DEBUG = log.New(os.Stdout, "DEBUG ", 0)
		mqtt.WARN = log.New(os.Stdout, "WARN ", 0)
		mqtt.CRITICAL = log.New(os.Stdout, "CRITICAL ", 0)
		mqtt.ERROR = log.New(os.Stdout, "ERROR ", 0)
	}

	mqttClient =: mqtt.NewClient(opts)
	if token := s.mqttClient.Connect(); token.Wait() && token.Error() != nil {
		log.Fatalf("Could not connect to mqtt broker.")
	}
```
Even when the broker host is local, with some self-signed certificates. I run into the same issue.

The trace log is as follows, and it will forever hang on `DEBUG [net]      connect started`. Publish messages will hang forever, unless I specify a timeout. Which of course always times out.
```
DEBUG [client]   Connect()
DEBUG [store]    memorystore initialized
DEBUG [client]   about to write new connect msg
DEBUG [client]   socket connected to broker
DEBUG [client]   Using MQTT 3.1.1 protocol
DEBUG [net]      connect started
DEBUG [net]      received connack
DEBUG [client]   client is connected
DEBUG [client]   exit startClient
DEBUG [net]      outgoing started
DEBUG [net]      outgoing waiting for an outbound message
DEBUG [net]      incoming started
DEBUG [pinger]   keepalive starting
DEBUG [net]      logic started
DEBUG [net]      logic waiting for msg on ibound
DEBUG [client]   enter Publish
DEBUG [client]   sending publish message, topic: heartbeat
DEBUG [net]      obound wrote msg, id: 1
DEBUG [net]      outgoing waiting for an outbound message
DEBUG [net]      Received Message
DEBUG [net]      logic got msg on ibound
DEBUG [store]    memorystore del: message 1 was deleted
DEBUG [net]      received puback, id: 1
DEBUG [net]      logic waiting for msg on ibound
...
ERROR [net]      incoming stopped with error EOF
ERROR [net]      logic received from error channel, other components have errored, stopping
DEBUG [pinger]   keepalive stopped
DEBUG [net]      outgoing stopped
DEBUG [client]   enter reconnect
DEBUG [client]   about to write new connect msg
DEBUG Connection lost: EOF
DEBUG [client]   socket connected to broker
DEBUG [client]   Using MQTT 3.1.1 protocol
DEBUG [net]      connect started
```

**Comment by alsm** [comment]
Can you make sure you're running the latest code from this repo and run the test suite against your local mqtt server, there is an autoreconnect test in there.

**Comment by brycereitano** [comment]
I'm running on latest and mqtt tests pass.

After digging into it a bit more, it seems to be a problem with having a proxy in front of the mqtt server. Where the go client connects socket wise to the proxy but the mqtt server is still down, for example when migrating hosts in a kubernetes cluster. The connection request never makes it to the mqtt server.

**Comment by alsm** [comment]
Thanks for investigating further, I'll close this issue now, although if you find anything that could be done by the client to assist in handling it please reopen.
