### ISSUE TITLE
Example golang compiler build flags

### ISSUE THREAD

**Issue by dvcorreia** [eclipse/paho.mqtt.golang#526]
https://github.com/eclipse/paho.mqtt.golang/blob/21ffd9190b7f3916a82abe907d5820feaff1ff46/cmd/docker/subscriber/dockerfile#L7

There's any motive regarding the `-N -l` flags? If i'm not mistaken, they are for disabling optimisations and inlining, respectively. Does this affect the client in any way?

**Comment by MattBrittan** [comment]
Prior to adding the docker setup to the repo I was using it when debugging a deadlock; these flags are probably left over from that. The flags should have been removed before the this was added to the repo (and the library should work with, or without them).
