### ISSUE TITLE
No messageArrived Callback like Java SDK

### ISSUE THREAD

**Issue by zhangcunli** [eclipse/paho.mqtt.golang#528]

**Comment by zhangcunli** [comment]
no...

**Comment by heliping** [comment]
same question? how to do?

**Comment by MattBrittan** [comment]
@heliping you are commenting on a closed issue (so are unlikely to get an answer). 

If you have a question then please see the [readme](https://github.com/eclipse/paho.mqtt.golang#more-information) for info on where to ask. If you do decide to raise a new issue then you will need to provide significantly more detail than this issue contains (and don't assume that readers have any knowledge of how the Java SDK works). Please ensure that you read the [documentation](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang) and look at the [examples](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker) before raising an issue.
