### ISSUE TITLE
Servers slice

### ISSUE THREAD

**Issue by dvcorreia** [eclipse/paho.mqtt.golang#530]
Any reason for `Servers` to be a slice? At first I taught the client was able to connect to multiple brokers. Tried and it couldn't. The documentation is not clear in this point, and from the code I couldn't figure it out.

https://github.com/eclipse/paho.mqtt.golang/blob/77d851e09af4fbb4ab43624c033683e6070579b6/options.go#L62

**Comment by MattBrittan** [comment]
>At first I taught the client was able to connect to multiple brokers

That is pretty much what happens; if it cannot connect to the first broker in the list it tries the next one until connected (see [`attemptConnection`](https://github.com/eclipse/paho.mqtt.golang/blob/77d851e09af4fbb4ab43624c033683e6070579b6/client.go#L386)).
