### ISSUE TITLE
The memory storage will not be freed until the MQTT client is disconnected

### ISSUE THREAD

**Issue by jyzbamboo** [eclipse/paho.mqtt.golang#532]
My project is that the MQTT client will keep connected and publish data every 1 second.

I found that the memory usage of my project keep increasing and increasing.....

I checked the source code of this project and found that the publish message will store in memory when the QOS is 1 or 2:

![image](https://user-images.githubusercontent.com/25757420/132183279-8f871db9-7d00-4333-a4aa-0f04fab66fe6.png)

And only be freed when MQTT client diconnect:

![image](https://user-images.githubusercontent.com/25757420/132183977-9a06539e-86ee-4c26-8b3a-d8eb1781a03c.png)

![image](https://user-images.githubusercontent.com/25757420/132183992-321ea40e-43c7-4fb1-bac5-2d6760784214.png)

Suggest that add the function for user to delete/free the memory or automatically free the memory every 1 or 2 minutes.

Thank you.

**Comment by MattBrittan** [comment]
The memory is released [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/memstore.go#L104); this is called when the packet that completes the transaction is received [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/store.go#L116. Note that the references to QOS here can be confusing because the [QOS bits](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L275) on acknowledgments do not match those of the request ([spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc353481062)).

This works the way that it does to maintain the session state as per the [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref362965194).

If you went to see this in action the simplest way is to use the [filestore](https://github.com/eclipse/paho.mqtt.golang/blob/master/filestore.go); when using this the packets are written to disk and you can watch the folder and see the files appear/disappear. I would recommend the filestore for any project where it is critical that messages are not lost (with the memory store you may loose messages if the application is restarted). I have deployments that message multiple times a second and have been running for months without any issues (using the filestore) so am confident that the packets are, in fact, being deleted (note that a maximum of 65534 messages can be held so if they were not being deleted your application would run out of IDs within a day).

**Comment by jyzbamboo** [comment]
> The memory is released [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/memstore.go#L104); this is called when the packet that completes the transaction is received [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/store.go#L116. Note that the references to QOS here can be confusing because the [QOS bits](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L275) on acknowledgments do not match those of the request ([spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc353481062)).
> 
> This works the way that it does to maintain the session state as per the [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref362965194).
> 
> If you went to see this in action the simplest way is to use the [filestore](https://github.com/eclipse/paho.mqtt.golang/blob/master/filestore.go); when using this the packets are written to disk and you can watch the folder and see the files appear/disappear. I would recommend the filestore for any project where it is critical that messages are not lost (with the memory store you may loose messages if the application is restarted). I have deployments that message multiple times a second and have been running for months without any issues (using the filestore) so am confident that the packets are, in fact, being deleted (note that a maximum of 65534 messages can be held so if they were not being deleted your application would run out of IDs within a day).

Hi Matt,

Thanks for your detailed explanation.

I will try to set filestore to see what happans.

Our project has more than 200+ MQTT Clients and all publish 1 data in 1 second. 
After our server has been running for three days, the memory usage has increased from 0.5% to 12.5%. (8GB memory on our linux server)

I will review our codes and perform more tests.

Thank you! !

**Comment by jyzbamboo** [comment]
> The memory is released [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/memstore.go#L104); this is called when the packet that completes the transaction is received [here](https://github.com/eclipse/paho.mqtt.golang/blob/master/store.go#L116. Note that the references to QOS here can be confusing because the [QOS bits](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L275) on acknowledgments do not match those of the request ([spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc353481062)).
> 
> This works the way that it does to maintain the session state as per the [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Ref362965194).
> 
> If you went to see this in action the simplest way is to use the [filestore](https://github.com/eclipse/paho.mqtt.golang/blob/master/filestore.go); when using this the packets are written to disk and you can watch the folder and see the files appear/disappear. I would recommend the filestore for any project where it is critical that messages are not lost (with the memory store you may loose messages if the application is restarted). I have deployments that message multiple times a second and have been running for months without any issues (using the filestore) so am confident that the packets are, in fact, being deleted (note that a maximum of 65534 messages can be held so if they were not being deleted your application would run out of IDs within a day).

Hi Matt,

May I ask you one more question?

https://github.com/eclipse/paho.mqtt.golang/blob/master/store.go#L116
In these code, is that means the memory will only be released when QOS is 0? (will not be released when QOS is 1 or 2)

Thank you

**Comment by MattBrittan** [comment]
>In these code, is that means the memory will only be released when QOS is 0? (will not be released when QOS is 1 or 2)

No - see my previous comment:

>Note that the references to QOS here can be confusing because the [QOS bits](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L275) on acknowledgments do not match those of the request ([spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc353481062)).

**Comment by jyzbamboo** [comment]
> > In these code, is that means the memory will only be released when QOS is 0? (will not be released when QOS is 1 or 2)
> 
> No - see my previous comment:
> 
> > Note that the references to QOS here can be confusing because the [QOS bits](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L275) on acknowledgments do not match those of the request ([spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc353481062)).

Hi Matt,

I use fileStore to test, and I saw that the number of files keeps increasing, and the previous message has not been deleted.

These files will not be released until I disconnect the MQTT client, then reconnect to MQTT and publish again.

![image](https://user-images.githubusercontent.com/25757420/132299267-c3f6460f-e7e9-418c-ba46-817f21548bde.png)


![image](https://user-images.githubusercontent.com/25757420/132298523-0964029b-d11a-4862-8b14-fcbebfb4b19b.png)

P.S.  I am using "github.com/patrickmn/go-cache" to save the mqtt client object. I will get the mqtt client object from cache and then publish msg everytime.

My client code:

		if x, found := c.Get(usn); found {// c for Cache
			// log.Printf("Already connected, directly send %s", usn)
			clientTB := x.(mqtt.Client)
			go pub(clientTB, topic, payloadStr, usn)
		} else {
			var tbBroker = tbMqttAdress
			var port = tbMqttPort
			opts := mqtt.NewClientOptions()
			opts.AddBroker(fmt.Sprintf("tcps://%s:%d", tbBroker, port))
			opts.SetClientID(NewClientId())
			opts.SetUsername(usn)
			opts.SetStore(mqtt.NewFileStore("C:\\wamp\\www\\go_mqtt\\store"))
			tlsConfig := NewTlsConfig()
			opts.SetTLSConfig(tlsConfig)
			opts.SetDefaultPublishHandler(messagePubHandler)
			opts.SetAutoReconnect(false)
			clientTB := mqtt.NewClient(opts)
			if token := clientTB.Connect(); token.Wait() && token.Error() != nil {
				// panic(token.Error())
			} else {
				// log.Printf("Connect new MQTT %s", usn)
				c.Set(usn, clientTB, cache.NoExpiration)
				go pub(clientTB, topic, payloadStr, usn)
			}
		}

My publish code:

	var pub = func(client mqtt.Client, topic string, payload string, username string) {
            sendPayload, _ := sjson.Delete(payload, "Username")
		token = client.Publish(topic, 1, false, sendPayload)
		token.Wait()
		if token.Error() != nil {
			log.Printf("Publish Error: %s; Payload: %s", token.Error(), payload)
		}
	}


Would you please tell why my filestore will not be deleted automatically? I am new to Golang.

Thank you.

**Comment by jyzbamboo** [comment]
> > > In these code, is that means the memory will only be released when QOS is 0? (will not be released when QOS is 1 or 2)
> > 
> > 
> > No - see my previous comment:
> > > Note that the references to QOS here can be confusing because the [QOS bits](https://github.com/eclipse/paho.mqtt.golang/blob/master/packets/packets.go#L275) on acknowledgments do not match those of the request ([spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc353481062)).
> 
> Hi Matt,
> 
> I use fileStore to test, and I saw that the number of files keeps increasing, and the previous message has not been deleted.
> 
> These files will not be released until I disconnect the MQTT client, then reconnect to MQTT and publish again.
> 
> ![image](https://user-images.githubusercontent.com/25757420/132299267-c3f6460f-e7e9-418c-ba46-817f21548bde.png)
> 
> ![image](https://user-images.githubusercontent.com/25757420/132298523-0964029b-d11a-4862-8b14-fcbebfb4b19b.png)
> 
> P.S. I am using "github.com/patrickmn/go-cache" to save the mqtt client object. I will get the mqtt client object from cache and then publish msg everytime.
> 
> My client code:
> 
> ```
> 	if x, found := c.Get(usn); found {// c for Cache
> 		// log.Printf("Already connected, directly send %s", usn)
> 		clientTB := x.(mqtt.Client)
> 		go pub(clientTB, topic, payloadStr, usn)
> 	} else {
> 		var tbBroker = tbMqttAdress
> 		var port = tbMqttPort
> 		opts := mqtt.NewClientOptions()
> 		opts.AddBroker(fmt.Sprintf("tcps://%s:%d", tbBroker, port))
> 		opts.SetClientID(NewClientId())
> 		opts.SetUsername(usn)
> 		opts.SetStore(mqtt.NewFileStore("C:\\wamp\\www\\go_mqtt\\store"))
> 		tlsConfig := NewTlsConfig()
> 		opts.SetTLSConfig(tlsConfig)
> 		opts.SetDefaultPublishHandler(messagePubHandler)
> 		opts.SetAutoReconnect(false)
> 		clientTB := mqtt.NewClient(opts)
> 		if token := clientTB.Connect(); token.Wait() && token.Error() != nil {
> 			// panic(token.Error())
> 		} else {
> 			// log.Printf("Connect new MQTT %s", usn)
> 			c.Set(usn, clientTB, cache.NoExpiration)
> 			go pub(clientTB, topic, payloadStr, usn)
> 		}
> 	}
> ```
> 
> My publish code:
> 
> ```
> var pub = func(client mqtt.Client, topic string, payload string, username string) {
>         sendPayload, _ := sjson.Delete(payload, "Username")
> 	token = client.Publish(topic, 1, false, sendPayload)
> 	token.Wait()
> 	if token.Error() != nil {
> 		log.Printf("Publish Error: %s; Payload: %s", token.Error(), payload)
> 	}
> }
> ```
> 
> Would you please tell why my filestore will not be deleted automatically? I am new to Golang.
> 
> Thank you.

I also use pprof to debug as below:

![image](https://user-images.githubusercontent.com/25757420/132302120-c8a7587c-923c-4c47-ac9b-c4097b653359.png)

![image](https://user-images.githubusercontent.com/25757420/132302146-d823196c-f0c8-4754-8e2b-b214185b4c67.png)

**Comment by MattBrittan** [comment]
The messages are only deleted when the correct acknowledgments are received from the MQTT broker; please check your broker logs and confirm the messages are being received (the point of using QOS1/2 is guaranteed delivery; the client stores the messages so they can be resent upon reconnection). You can also get information from the client by [activating logging](https://github.com/eclipse/paho.mqtt.golang#logging). In order to help you further I'll really need the information requested in the [readme](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) including logs and a minimal, reproducible example.

I have no experience with `github.com/patrickmn/go-cache` and really cannot see what benefit it brings in this case (and its likely to cause issues as this package uses go routines, mutexes etc so cannot just be treated like data). I cannot say if this might be contributing to the issue but would suggest removing it (I will not be able to help while you are using it as it complicates things).

I would suggest creating an application that just uses the client to send messages ([e.g.])https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/docker/publisher/main.go)) and see if you still experience the issue. If so let me know; if not start adding other bits of your code until the issue reappears.

**Comment by jyzbamboo** [comment]
> The messages are only deleted when the correct acknowledgments are received from the MQTT broker; please check your broker logs and confirm the messages are being received (the point of using QOS1/2 is guaranteed delivery; the client stores the messages so they can be resent upon reconnection). You can also get information from the client by [activating logging](https://github.com/eclipse/paho.mqtt.golang#logging). In order to help you further I'll really need the information requested in the [readme](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) including logs and a minimal, reproducible example.
> 
> I have no experience with `github.com/patrickmn/go-cache` and really cannot see what benefit it brings in this case (and its likely to cause issues as this package uses go routines, mutexes etc so cannot just be treated like data). I cannot say if this might be contributing to the issue but would suggest removing it (I will not be able to help while you are using it as it complicates things).
> 
> I would suggest creating an application that just uses the client to send messages ([e.g.])https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/docker/publisher/main.go)) and see if you still experience the issue. If so let me know; if not start adding other bits of your code until the issue reappears.

Hi Matt,

Thanks for your suggestion.

I follow the [demo client code](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/docker/publisher/main.go) :

1. Connect our broker: the issue still exists.
2. Connect the 3rd party MQTT broker: **the issue disappear, the fileStore will automatically be deleted.**

Probably this is the issue of our MQTT broker.

Really thank you for your help.

Best Regard

**Comment by MattBrittan** [comment]
>Probably this is the issue of our MQTT broker.

Please let me know if it turns out to be something else. The library should work with all standard compliant brokers and sometimes the standard can be interpreted in multiple ways (but I cannot know if that is the case here without more info).
