### ISSUE TITLE
MQTT Client hangs up 

### ISSUE THREAD

**Issue by JimmyWang** [eclipse/paho.mqtt.golang#534]
Hi there, 

our service use mqtt client to publish data, sometimes we found Publish() method hangs up, 

screenshort by pprof:

![image](https://user-images.githubusercontent.com/6657454/132787036-2969a96f-b98b-4f43-a431-ec05c8fec48f.png)

this is a very old service, not using go mod but vendor, I don't know the version using.

but i can provide codes detail in paho.mqtt.golang lib to detect version

Thanks,
Jimmy

**Comment by MattBrittan** [comment]
Sorry - I cannot help without a lot more details and am unlikely to assist unless you update to the latest release (a lot of changes have been made over the last couple of years). Please see the [reporting bugs](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) section of the readme for the info needed.

**Comment by JimmyWang** [comment]
> Sorry - I cannot help without a lot more details and am unlikely to assist unless you update to the latest release (a lot of changes have been made over the last couple of years). Please see the [reporting bugs](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) section of the readme for the info needed.

ok, already update to v.1.3.5 
run to see if it happens.
