### ISSUE TITLE
reconnect

### ISSUE THREAD

**Issue by carr123** [eclipse/paho.mqtt.golang#535]
hello, what's the difference between opts.SetAutoReconnect(true) and opts.SetConnectRetry(true) ?
it seems they all perform reconnection when detect lost .
thanks.

**Comment by MattBrittan** [comment]
[The documentation](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetConnectRetry) could probably do with a bit of work:

>func (o *ClientOptions) SetAutoReconnect(a bool) *ClientOptions
>
>SetAutoReconnect sets whether the automatic reconnection logic should be used when the connection is lost, even if disabled the ConnectionLostHandler is still called


>func (o *ClientOptions) SetConnectRetry(a bool) *ClientOptions
>
>SetConnectRetry sets whether the connect function will automatically retry the connection in the event of a failure (when true the token returned by the Connect function will not complete until the connection is up or it is cancelled) If ConnectRetry is true then subscriptions should be requested in OnConnect handler Setting this to TRUE permits messages to be published before the connection is established

The difference is that `SetConnectRetry` applies to the initial connection and `SetAutoReconnect` applies when a connection has been established and is then lost.

Use `SetConnectRetry` if you want to call `Connect` and then send start messages regardless of whether the client was able to connect to the broker (assumes QOS1+ so messages get queued). This works well on PC's connected via cell links and powered by battery (so they may restart from time to time and the network link might be down when they restart). You would probably not want to use this on a cloud server (not being able to reach the broker should probably be considered an error).

Use `SetAutoReconnect` when you want the client to re-establish a connection that has dropped.

It's quite possible that you might want to set both of these to `true` (I do).

**Comment by carr123** [comment]
@MattBrittan thanks very much

my program runs on a cloud server. i want it could reconnect and resubscribe after it get disconnected(eg. i want it to be self healing)
should i move "Subscribe( )" part into OnConnect handler ?

----------------------------------------------------------------------------------------------------------------------------------
opts := mqtt.NewClientOptions()
opts.AddBroker("tcp://" + BrokerURL + ":1883")
opts.SetClientID(ClientID)
opts.SetUsername(username)
opts.SetPassword(password)
opts.SetAutoReconnect(true)
opts.SetConnectRetry(false)
opts.SetResumeSubs(true) // i expect it can auto sub some topic when reconnected.
opts.SetCleanSession(false) // i don't want lose message during connection lost.
opts.SetKeepAlive(time.Second * 10)

opts.OnConnectionLost = func(client mqtt.Client, err error) {
	fmt.Println("MQTT lost connection")
}

opts.OnConnect = func(client mqtt.Client) {
	fmt.Println("MQTT on connect")
}

nc := mqtt.NewClient(opts)
if !nc.Connect().WaitTimeout(time.Second * 10) {
	fmt.Println("mqtt connect fail")
     return
}

if !nc.Subscribe(SubTopic, 0, callback).WaitTimeout(time.Second * 10) {
	fmt.Println("mqtt Subscribe fail")
    return
}

**Comment by MattBrittan** [comment]
As you are subscribing with `QOS=0` you should call `Subscribe` from `OnConnect` (see [this example](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/docker/subscriber/main.go#L137)).

**Comment by carr123** [comment]
thanks very much !
