### ISSUE TITLE
Strange QoS 1 store behavior

### ISSUE THREAD

**Issue by estutzenberger** [eclipse/paho.mqtt.golang#538]
We are working with a customer that uses Kaa cloud and their MQTT broker (docs [here](https://docs.kaaiot.io/KAA/docs/current/Welcome/)). Recently, we have noticed that MQTT messages fail to be posted after a while. Today I investigated further and what I discovered is that our limited storage queue is filling up for QoS 1 messages. We cap the store due to RAM limitations for our embedded linux hardware. Further digging led me to the fact that Puback messages from Kaa are being returned with a QoS of 1 rather than a QoS of 0. This means that the ``persistInbound`` produces an error message rather than ever removing the message from the store.

Here is the code for reference:

    case 0:
		switch m.(type) {
		case *packets.PubackPacket, *packets.SubackPacket, *packets.UnsubackPacket, *packets.PubcompPacket:
			// Received a puback. delete matching publish
			// from obound
			s.Del(outboundKeyFromMID(m.Details().MessageID))
		case *packets.PublishPacket, *packets.PubrecPacket, *packets.PingrespPacket, *packets.ConnackPacket:
		default:
			ERROR.Println(STR, "Asked to persist an invalid messages type")
		}
	case 1:
		switch m.(type) {
		case *packets.PublishPacket, *packets.PubrelPacket:
			// Received a publish. store it in ibound
			// until puback sent
			s.Put(inboundKeyFromMID(m.Details().MessageID), m)
		default:
			ERROR.Println(STR, "Asked to persist an invalid messages type") <- this is the error message we always see
		}

I forked the repo and added a tiny bit of debug code here to denote the QoS of the incoming packet and the packet type. The result for every Puback were:

    qos 1: {Qos:1 MessageID:10}, *packets.PubackPacket

I've looked through the MQTT specification (sections 2.1 and 3.4), but it is not clear to me which code behaves incorrectly. The above code has been in the Paho MQTT library for a long time (since at least v1.1.1). My suspicion is that Kaa is incorrect in the behavior, but I am not sure.

Can someone please clarify the correct behavior and/or determine if this is an issue with the library or not. I made a small change to fix this for the time being by changing `case 1` above to:

    case 1:
		switch m.(type) {
                //added this case
		case *packets.PubackPacket:
			// Received a puback. delete matching publish
			// from obound
			s.Del(outboundKeyFromMID(m.Details().MessageID))
		case *packets.PublishPacket, *packets.PubrelPacket:
			// Received a publish. store it in ibound
			// until puback sent
			s.Put(inboundKeyFromMID(m.Details().MessageID), m)
		default:
			ERROR.Println(STR, "Asked to persist an invalid messages type")
			ERROR.Printf("qos 1: %+v, %T", m.Details(), m)
		}

I have no idea if this is an appropriate change or not.

Thanks!

**Comment by MattBrittan** [comment]
The [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718043) specified the fixed header for the `PUBACK` as:

<html>
<body>
<!DOCTYPE html>

<table class="MsoNormalTable" style="border-collapse:collapse;border:none" cellspacing="0" cellpadding="0" border="1">
 <tbody><tr>
  <td style="width:72.85pt;border:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="97" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>Bit</b></p>
  </td>
  <td style="width:50.7pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>7</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>6</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>5</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>4</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>3</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>2</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>1</b></p>
  </td>
  <td style="width:50.75pt;border:solid windowtext 1.0pt;
  border-left:none;padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center"><b>0</b></p>
  </td>
 </tr>
 <tr>
  <td style="width:72.85pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt" width="97" valign="top">
  <p class="MsoNormal">byte 1</p>
  </td>
  <td colspan="4" style="width:202.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="271" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">MQTT Control Packet
  type (4)</p>
  </td>
  <td colspan="4" style="width:203.0pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="271" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">Reserved</p>
  </td>
 </tr>
 <tr>
  <td style="width:72.85pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt" width="97" valign="top">
  <p class="MsoNormal">&nbsp;</p>
  </td>
  <td style="width:50.7pt;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">1</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
 </tr>
 <tr>
  <td style="width:72.85pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt" width="97" valign="top">
  <p class="MsoNormal">byte 2</p>
  </td>
  <td colspan="8" style="width:405.95pt;border-top:none;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="541" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">Remaining Length
  (2)</p>
  </td>
 </tr>
 <tr>
  <td style="width:72.85pt;border:solid windowtext 1.0pt;
  border-top:none;padding:0in 5.4pt 0in 5.4pt" width="97" valign="top">
  <p class="MsoNormal">&nbsp;</p>
  </td>
  <td style="width:50.7pt;border-top:none;border-left:none;
  border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">1</p>
  </td>
  <td style="width:50.75pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  padding:0in 5.4pt 0in 5.4pt" width="68" valign="top">
  <p class="MsoNormal" style="text-align:center" align="center">0</p>
  </td>
 </tr>
</tbody></table>


</body>
</html>

So this means there is no `QOS` associated with this packet (the bits that set the QOS level on some other packets are flagged as reserved and should be `0`).  This seems like a minor thing, and I had been considering altering this libraries behaviour to ignore these reserved bits, but then noticed that the spec states:

>[MQTT-3.14.1-1] | The Server MUST validate that   reserved bits are set to zero and disconnect the Client if they are not zero.

So we really should be dropping the connection when these are received (and accepting them would really breach the spec). I'd suggest logging this issue with Kaa .

**Comment by stutzenbergere** [comment]
Thanks! This is how I was reading the spec as well but wasn't entirely sure. I'll follow up with them.

**Comment by estutzenberger** [comment]
Kaa has confirmed with me that the issue is on their end. Thanks for the response and support!
