### ISSUE TITLE
Last message is not delivered to a newly connected subscriber with retain message set to true

### ISSUE THREAD

**Issue by deepavk** [eclipse/paho.mqtt.golang#539]
Subscriber established a new connection with the qos parameter set to 1. The subscriber doesn't receive the last published message even though the retain value at publisher was set to true. Whether the cleanSession value is set to true or false the same behaviour is observed.

Subscriber:
```
func sub(client mqtt.Client) {
	topic := "topic/try/me"
	token := client.Subscribe(topic, 1, nil)
	fmt.Printf("Subscribed to topic: %s", topic)

	for {
		token.Wait()
	}
}
```

Publisher:
```
func publish(client mqtt.Client, msg string) {

	text := fmt.Sprintf("Message %s", msg)
	token := client.Publish("topic/try/me", 0, true, text)
	token.Wait()
	
}
```

The client options are set as follows:
```
        var broker = "broker.emqx.io"
	var port = 1883
	opts := mqtt.NewClientOptions()
	opts.AddBroker(fmt.Sprintf("tcp://%s:%d", broker, port))
	opts.SetClientID("go-mqtt-pub-test")
        opts.CleanSession = false 
```

The same behaviour is observed with the solace broker as well

**Comment by MattBrittan** [comment]
You have not really provided enough information to enable me to assist (see [reporting bugs](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) in the readme). 

Having said that I suspect your issue is listed in [common problems][(https://github.com/eclipse/paho.mqtt.golang#common-problems):

>When QOS1+ subscriptions have been created previously and you connect with CleanSession set to false it is possible that the broker will deliver retained messages before Subscribe can be called. To process these messages either configure a handler with AddRoute or set a DefaultPublishHandler.

**Comment by deepavk** [comment]
Hi @MattBrittan 

Thank you for the explanation, I have contacted Solace to find more information about this.
