### ISSUE TITLE
Disconnect hangs if a message is received during disconnect

### ISSUE THREAD

**Issue by alexeits** [eclipse/paho.mqtt.golang#54]
Symptom: `Disconnect` never returns

Debug logging indicates that there's a possible race in the disconnect code causing `incoming` goroutine to block on a write to `c.ibound` channel. As a result the `disconnect` waits forever on  the workers `WaitGroup`.

Here's the debug log for the disconnect illustrating the issue:
```
[client]   disconnecting
[net]      obound priority msg to write, type *packets.DisconnectPacket
[net]      outbound wrote disconnect, stopping
[net]      logic stopped
[net]      Received Message
[pinger]   keepalive stopped
```

compare this to a normal disconnect sequence:
```
[client]   disconnecting
[net]      obound priority msg to write, type *packets.DisconnectPacket
[net]      outbound wrote disconnect, stopping
[net]      incoming stopped
[net]      logic stopped
[pinger]   keepalive stopped
[client]   disconnected
[store]    memorystore closed
```

**Comment by alsm** [comment]
I've changed the order of things with disconnect in the changes trying to resolve issue 56, I'd be interested if you still see this problem with these changes.

**Comment by alsm** [comment]
Closing this as pretty sure we've resolved it now, if seen again please reopen.
