### ISSUE TITLE
[Feature suggestion] Limit ClientOptions visibility to prevent zero-value KeepAlive problems (v1.3.5 -> mosquitto 2.0.12)  

### ISSUE THREAD

**Issue by ebudan** [eclipse/paho.mqtt.golang#545]
The documentation for ClientOptions gently nudges toward using setters, but it doesn't enforce.  
I recently ran into the following scenario:

- 3rd party code constructed ClientOptions{...} explicitly (paho.mqtt.golang 1.3.5), leaving KeepAlive zero 
- code ran against Mosquitto 1.6.x apparently fine
- code failed against Mosquitto 2.0.12 with the following broker-side message:

```
1633594305: New connection from ::1:33582 on port 1883.
1633594305: New client connected from ::1:33582 as test (p2, c0, k0).
1633594305: Bad socket read/write on client test: Invalid arguments provided.
```

The k0 output wasn't obvious to me, but comparing to a successful connection with 'k30' it was enough to let me look that up in the mosquitto source, then test the code with KeepAlive set to 30, connecting successfully.

Would it be an option to make ClientOptions private to prevent uninitialized usage? If not, should its documentation perhaps emphasize using NewClientOptions() in a stronger tone?

**Comment by MattBrittan** [comment]
Closing this issue. I believe that the comments added address the issue (the alternative, making `ClientOptions` public, is not something I'm keen on).

**Comment by ebudan** [comment]
Thank you, those comments should help the casual user stay on track.
