### ISSUE TITLE
Would you like to tell me how to delete retained message 

### ISSUE THREAD

**Issue by roooneychina** [eclipse/paho.mqtt.golang#549]
topic := "....."
,type Spacex struct{
 }
var structxx2 Spacex
structxx3,_ := json.Marshal(structxx2)

Publish(topic, 1, true, structxx3) 

it seems does not work. would you like to help me?

**Comment by roooneychina** [comment]
var xxx [] byte
							
Publish("topic", 1, true, xxx)
is that ok? many thanks

**Comment by MattBrittan** [comment]
Closing this as it's a question that I believe I have answered,
