### ISSUE TITLE
Shared Subscription doesn't work as expected

### ISSUE THREAD

**Issue by fherryfherry** [eclipse/paho.mqtt.golang#556]
Hi anyone, is this library support shared subscription? because I tried but there is no message received
Topic Example: ``$shared/group/blabla``

**Comment by MattBrittan** [comment]
Shared subscriptions are an MQTT v5 feature; some v3 (which this library supports) brokers do offer support but this is outside the v3 spec. [This issue](https://github.com/eclipse/paho.mqtt.golang/issues/264) may help; from this it is my understanding that the library supports shared subscriptions (but it's not something I use or have tested).  If you want help you will need to provide more information (what broker are you using, what topic are you publishing on, do other clients such as `mosquitto_sub` receive the message etc).

**Comment by fherryfherry** [comment]
> Shared subscriptions are an MQTT v5 feature; some v3 (which this library supports) brokers do offer support but this is outside the v3 spec. [This issue](https://github.com/eclipse/paho.mqtt.golang/issues/264) may help; from this it is my understanding that the library supports shared subscriptions (but it's not something I use or have tested). If you want help you will need to provide more information (what broker are you using, what topic are you publishing on, do other clients such as `mosquitto_sub` receive the message etc).

Thanks for your fast response. Is there any go lang library for mosquitto_sub?

**Comment by MattBrittan** [comment]
`mosquitto_sub` is a command line tool that comes with Mosquito ([MQTT explorer](http://mqtt-explorer.com/) or similar would be fine too). I was just asking if you have tested this with another program (rather than assuming it's an issue with this library and not the broker/publisher).
