### ISSUE TITLE
Block on unsubscribe when mqtt is a reconnecting status

### ISSUE THREAD

**Issue by goleo007** [eclipse/paho.mqtt.golang#566]
```
func (c *client) Unsubscribe(topics ...string) Token {
	token := newToken(packets.Unsubscribe).(*UnsubscribeToken)
	DEBUG.Println(CLI, "enter Unsubscribe")
	if !c.IsConnected() {
		token.setError(ErrNotConnected)
		return token
	}
	if !c.IsConnectionOpen() {
		switch {
		case !c.options.ResumeSubs:
			// if not connected and resumesubs not set this unsub will be thrown away
			token.setError(fmt.Errorf("not currently connected and ResumeSubs not set"))
			return token
		case c.options.CleanSession && c.connectionStatus() == reconnecting:
			// if reconnecting and cleansession is true this unsub will be thrown away
			token.setError(fmt.Errorf("reconnecting state and cleansession is true"))
			return token
		}
	}
	unsub := packets.NewControlPacket(packets.Unsubscribe).(*packets.UnsubscribePacket)
	unsub.Topics = make([]string, len(topics))
	copy(unsub.Topics, topics)

	if unsub.MessageID == 0 {
		mID := c.getID(token)
		if mID == 0 {
			token.setError(fmt.Errorf("no message IDs available"))
			return token
		}
		unsub.MessageID = mID
		token.messageID = mID
	}

	if c.options.ResumeSubs { // Only persist if we need this to resume subs after a disconnection
		persistOutbound(c.persist, unsub)
	}

	switch c.connectionStatus() {
	case connecting:
		DEBUG.Println(CLI, "storing unsubscribe message (connecting), topics:", topics)
	case reconnecting:
		DEBUG.Println(CLI, "storing unsubscribe message (reconnecting), topics:", topics)
	default:
		DEBUG.Println(CLI, "sending unsubscribe message, topics:", topics)
		subscribeWaitTimeout := c.options.WriteTimeout
		if subscribeWaitTimeout == 0 {
			subscribeWaitTimeout = time.Second * 30
		}
		select {
		case c.oboundP <- &PacketAndToken{p: unsub, t: token}:
			for _, topic := range topics {
				c.msgRouter.deleteRoute(topic)
			}
		case <-time.After(subscribeWaitTimeout):
			token.setError(errors.New("unsubscribe was broken by timeout"))
		}
	}

	DEBUG.Println(CLI, "exit Unsubscribe")
	return token
}
```
this is my test code:
```
        mqtt.DEBUG = log.New(os.Stdout, "", 0)
	mqtt.ERROR = log.New(os.Stdout, "", 0)
	
	opts := mqtt.NewClientOptions().AddBroker("tcp://127.0.0.1:1883").SetClientID("emqx_test_client")

	opts.SetKeepAlive(60 * time.Second)
	// Set the message callback handler
	opts.SetDefaultPublishHandler(f)
	opts.SetPingTimeout(30 * time.Second)
	opts.SetAutoReconnect(true)
	opts.SetProtocolVersion(5)
	opts.SetConnectionLostHandler(func(client mqtt.Client, err error) {
		log.Println("[mqtt initDefaultConfig] SetConnectionLostHandler has been triggered : ", err.Error())
	})


	c := mqtt.NewClient(opts)
	if token := c.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}

	// Subscribe to a topic
	if token := c.Subscribe("test", 0, nil); token.Wait() && token.Error() != nil {
		fmt.Println(token.Error())
		os.Exit(1)
	}

	// Publish a message
	//token := c.Publish("testtopic/1", 0, false, "Hello World")
	//token.Wait()

	time.Sleep(6 * time.Second)

	// Unscribe
	if token := c.Unsubscribe("testtopic/#"); token.Wait() && token.Error() != nil {
		fmt.Println(token.Error())
		os.Exit(1)
	}
```

sub or unsub a topic will block （because of token.Wait）when mqtt is in a reconnecting status。Does the SDK need to consider this situation ？Or the caller considers this situation by himself？

**Comment by MattBrittan** [comment]
I'm not really clear on what you are reporting - is it:

>If I call `Subscribe` or `Unsubscribe` while the client is in the process of reconnecting to the broker then `token.Wait()` will block permanently.

What happens is going to depend upon the options; from a quick look at the code:

- If `options.SetResumeSubs(true)` then the function will return immediately. The token will complete after the client reconnects (or if a non-connection related error occurs).
- Otherwise the function will return after  the timeout set with `SetWriteTimeout` (default never!) with the token already completed (unless the connection comes up in the interim).

I think that this makes a degree of sense (I'd probably prefer to see the function return more quickly and close the token after the timeout but don't see that as a huge issue). Note that this is not an area I've spent much time looking at/testing (I don't use `Unsubscribe` myself). 

Note: This library does not support `opts.SetProtocolVersion(5)` (this will be ignored).

**Comment by goleo007** [comment]
> I'm not really clear on what you are reporting - is it:
> 
> > If I call `Subscribe` or `Unsubscribe` while the client is in the process of reconnecting to the broker then `token.Wait()` will block permanently.
> 
> What happens is going to depend upon the options; from a quick look at the code:
> 
> * If `options.SetResumeSubs(true)` then the function will return immediately. The token will complete after the client reconnects (or if a non-connection related error occurs).
> * Otherwise the function will return after  the timeout set with `SetWriteTimeout` (default never!) with the token already completed (unless the connection comes up in the interim).
> 
> I think that this makes a degree of sense (I'd probably prefer to see the function return more quickly and close the token after the timeout but don't see that as a huge issue). Note that this is not an area I've spent much time looking at/testing (I don't use `Unsubscribe` myself).
> 
> Note: This library does not support `opts.SetProtocolVersion(5)` (this will be ignored).

In fact, I'm just not sure whether token.wait block permanently is reasonable. Now I got it。Thanks for your reply。
