### ISSUE TITLE
Can not use in go1.18 version

### ISSUE THREAD

**Issue by datafeng** [eclipse/paho.mqtt.golang#591]
Can not use in go1.18 version.. 
It will have some bugs~~

**Comment by someburner** [comment]
@datafeng could you elaborate?

**Comment by MattBrittan** [comment]
The tests all pass with 1.18 and I've upgraded a few of my systems and not experienced any issues. Without more information I don't think its going to be possible to help (please see the [readme](https://github.com/eclipse/paho.mqtt.golang#reporting-bugs) for information on what to include when reporting an issue).

**Comment by datafeng** [comment]
It's not a package problem, it's solved..
^^
