### ISSUE TITLE
When to release 1.3.6?

### ISSUE THREAD

**Issue by oyljerry** [eclipse/paho.mqtt.golang#592]
It seems 1.3.5 has released 10 month ago. When will be new release? Thanks.

**Comment by MattBrittan** [comment]
Will probably make a release fairly soon; the changes since 1.3.5 are all fairly minor and unlikely to impact most users.

**Comment by oyljerry** [comment]
@MattBrittan  Do you have release schedule for 1.3.6? I need [SetCustomOpenConnectionFn](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L443)

**Comment by MattBrittan** [comment]
Sorry - I've been travelling for the last month and a half. Aiming to get a release out within a week (want to do this before looking at the outstanding PR's again).

**Comment by MattBrittan** [comment]
I've published 1.4.0 (as there were new features I've changed the minor version).
