### ISSUE TITLE
Published messages do not buffer during ConnectRetry

### ISSUE THREAD

**Issue by sirockin** [eclipse/paho.mqtt.golang#596]
When I set `AutoReconnect` to `true`, the client will attempt to reconnect to the broker after its connection is lost, then once successful, resend any messages I published of QoS > 1.

Setting `ConnectRetry` to `true` will (as expected) ensure that after a *first* attempt to connect has failed, the client continues to attempt connecting until successful but in this case, does not seem to send any messages I have already published.

Is this by design or have I could I be doing something wrong?

Thanks in advance!

**Comment by MattBrittan** [comment]
What you describe should work (there is a [test to confirm this](https://github.com/eclipse/paho.mqtt.golang/blob/master/fvt_client_test.go#L1239)). Please share your code.

**Comment by sirockin** [comment]
Hi @MattBrittan . I've looked through that test and I'm not clear how it is testing my use-case.

It seems the test:
1. Creates a subscriber (`s`) against a valid server
2. Creates a publisher (`p`) against an invalid server
3. Attempts to publish a test message and confirms it hasn't left the store
4. Reconnects to the correct server, transferring over the memstore

However it doesn't seem to ever:
5. Check that the saved packet has left the memstore after reconnection
6. Check that the subscriber has received the message (what *is* the purpose of the subscriber?)
7. Actually check reconnection against the same server

Sorry if I've misunderstood.

My own code is embedded in some of our integration tests but I'll try to reproduce the example in a similar format to your own.

**Comment by MattBrittan** [comment]
Unfortunately the structure of the library made testing this difficult and the approach currently used was the best I could come up with.

>unexpected difference when connecting reconnecting to the same broker.

Anything is possible and I may be misunderstanding your issue; a test would be ideal (as we can add it to the library) but being able to duplicate the issue with Docker ([example](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker)) would also be fine.

**Comment by sirockin** [comment]
[Here](https://github.com/sirockin/paho.mqtt.golang/blob/6829df15bc74675189a8c823b0955a7e1e79019d/fvt_client_test.go#L1322) is a new test which demonstrates the issue. It:
1. Connects the publisher with ConnectRetry
2. Publishes the test message (with retain set)
3. Starts a broker via docker
4. Connects the subscriber
5. Waits for the message (which doesn't arrive)

**Comment by sirockin** [comment]
I agree writing tests reliable tests for MQTT can be difficult and starting/stopping docker containers isn't optimal. Another approach I have used is using an embedded broker like `github.com/mochi-co/mqtt/server`, which has the added advantage of letting you intercept published messages without creating a separate subscriber.

**Comment by sirockin** [comment]
Hi @MattBrittan were you able to reproduce my issue OK with the [test I provided](https://github.com/sirockin/paho.mqtt.golang/blob/6829df15bc74675189a8c823b0955a7e1e79019d/fvt_client_test.go#L1322)? Please let me know if you need any further information.

Cheers!

Dave

**Comment by MattBrittan** [comment]
Hi @sirockin - I'm travelling for the next couple of weeks so may be slow to respond (and not often in a position to run test code).

`CleanSession` defaults to `true` and when in that state the session (including anything stored on the client) is cleared when the connection is established (as required by the MQTT spec). Fix this and your test passes i.e.:

```
pops := NewClientOptions().AddBroker(tempLocalBroker).SetClientID("crp-pub").SetCleanSession(false).
		SetStore(memStore).SetConnectRetry(true).SetConnectRetryInterval(time.Second / 2)
```

**Comment by sirockin** [comment]
Thanks for clarifying, I'll try that. Safe travels!
