### ISSUE TITLE
AddRoute function How to catch the message?

### ISSUE THREAD

**Issue by heliping** [eclipse/paho.mqtt.golang#610]
The AddRoute how to get the message and callback?

client.AddRoute(topic, CallbackHandler)

**Comment by MattBrittan** [comment]
You earlier made the same comment on a closed issue and I said:

>If you have a question then please see the [readme](https://github.com/eclipse/paho.mqtt.golang#more-information) for info on where to ask. If you do decide to raise a new issue then you will need to provide significantly more detail than this issue contains (and don't assume that readers have any knowledge of how the Java SDK works). Please ensure that you read the [documentation](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang) and look at the [examples](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker) before raising an issue.

It's not currently clear what you are asking (the example I pointed you towards provides an example of how to use [AddRoute](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/docker/subscriber/main.go#L160)) so I'm not really sure what I can add to that.

The readme states "if you have a general question please see the resources in the [more information](https://github.com/eclipse/paho.mqtt.golang#more-information) section for help". As such I'm going to close this question; please take a look at the example I provided and if you have further questions raise them at one of the suggested places (but ensure you provide enough detail to allow someone to answer).
