### ISSUE TITLE
Publishing dict/tuple to MQTT broker

### ISSUE THREAD

**Issue by saket-sudo** [eclipse/paho.mqtt.golang#618]
In publish.py it is mentioned in the comment that sending a dict or tuple is possible while publishing to broker. But when I try to send a dict in publish, it is returning with an error that 'dict/tuple' has no attribute 'encode'.

**Comment by MattBrittan** [comment]
This repo is for the Go Client - I think you want the [python one ](https://github.com/eclipse/paho.mqtt.python). I would also suggest including your code and the full error when creating an issue.
