### ISSUE TITLE
Qos 0 during reconnect

### ISSUE THREAD

**Issue by 12bchl** [eclipse/paho.mqtt.golang#630]
https://github.com/eclipse/paho.mqtt.golang/blob/e3fa5031fa86ee9233dfebd71a1879f6b2b813b4/client.go#L759

How does the message get persisted in store if we return right away before persistOutbound?

**Comment by MattBrittan** [comment]
They dont; Qos0 messages are dropped if there is no connection (only qos1+ messages have any delivery guarantees).

**Comment by 12bchl** [comment]
Understood, just confused on the comment. NP

**Comment by MattBrittan** [comment]
You are right - the comment is wrong!
