### ISSUE TITLE
Ability to refresh connect options during automatic reconnect maybe, supporting Reconnect Handler

### ISSUE THREAD

**Issue by tn185075** [eclipse/paho.mqtt.golang#640]
* The broker we communicate with, would accept JWT's for authenticating and authorising clients.
* Whenever a connection is lost, Paho tries to reconnect with the token in the original packet, which would have been expired by then.
* An ability to refresh the authentication options for every reconnect trial at least would be nice to have in these kind of scenarios.
* Much better way, is if we can write our own reconnect handlers which must be processed before performing an automated reconnect.

Please do let me know, if this mechanism already exists.

**Comment by MattBrittan** [comment]
>Much better way, is if we can write our own reconnect handlers

This is exactly what [`SetCustomOpenConnectionFn`](https://github.com/eclipse/paho.mqtt.golang/blob/v1.4.2/options.go#L445) [¶](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetCustomOpenConnectionFn) provides.

**Comment by tn185075** [comment]
Will check it out, Thanks. Do you think it's possible to solve the scenario I was talking about?

**Comment by tn185075** [comment]
I meant to ask this question on `Paho.golang` repository, confused between two libraries supporting MQTT. Let me reopen there. Thank you.

**Comment by tn185075** [comment]
Opened there: https://github.com/eclipse/paho.golang/issues/127
