### ISSUE TITLE
MQTTv5: Publish Release encoding is invalid

### ISSUE THREAD

**Issue by zzrrxx** [eclipse/paho.mqtt.golang#641]
I tried to use `paho/cmd/stdinpub/main.go` to test the mqttv5 QoS2 publish functions, but it doesnt' work.

The packet "Publish Release" doesn't contain any properties. As the rfc says, it should be encoded as byte array []byte { 0 }.

Just like:

![image](https://github.com/eclipse/paho.mqtt.golang/assets/33322359/ee03c474-1dae-479c-b61f-000ec1b48f2c)

But its encoding is like:

![image](https://github.com/eclipse/paho.mqtt.golang/assets/33322359/1fdf22c9-afe3-4968-8a8f-01b9005d519f)

**Comment by MattBrittan** [comment]
This client does not support MQTT v5 (as stated in the readme), so it's unsurprising that there are no properties. See [this project](https://github.com/eclipse/paho.golang) for v5 support (but note that it does not fully support QOS1/2 yet - it works but the session state will not survive a disconnect and messages will never be retried).
