### ISSUE TITLE
Why is the release version V1.4.3 and not v1.4.3?

### ISSUE THREAD

**Issue by iGoogle-ink** [eclipse/paho.mqtt.golang#643]
@MattBrittan 
Why is the release version V1.4.3 and not v1.4.3? I think v should be lowercase rather than uppercase, the release name is v1.4.3, but the tag is V1.4.3.

**Comment by MattBrittan** [comment]
Apologies - I have corrected this (and confirmed that `go get -u` gets the correct tag as does the [docs site](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang)).

**Comment by iGoogle-ink** [comment]
> Apologies - I have corrected this (and confirmed that `go get -u` gets the correct tag as does the [docs site](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang)).

Have been OK

**Comment by MattBrittan** [comment]
Closing this off as I believe it's resolved.
