### ISSUE TITLE
support of shared subscription in paho.mqtt.golang

### ISSUE THREAD

**Issue by Abhijithm2447** [eclipse/paho.mqtt.golang#647]
Hi,

I found one statement on documentation of paho.mqtt.golang that this library is not supporting MQTT-5. However, I am able to use shared subscription with use of this library and code inside attached file. As shared subscription is part of MQTT-5 then how this library is supporting shared subscription if MQTT-5 is not supported by this library?

code file:
![shared_subscription.go.txt](https://github.com/eclipse/paho.mqtt.golang/files/12394705/shared_subscription.go.txt)
output file:
[output](https://github.com/eclipse/paho.mqtt.golang/assets/29754503/a688869b-cd93-4644-acd8-558314cc76ac)

**Comment by MattBrittan** [comment]
Shared subscriptions are supported by a range of V3 brokers (not part of the v3 standard but there is nothing in the standard prevents the feature being implemented and some of these implementations are from before v5 was released)..

Note: Please see the [readme](https://github.com/eclipse/paho.mqtt.golang#more-information) for places to ask questions like this (this section is intended for issues with this specific library, not general questions).

**Comment by Abhijithm2447** [comment]
Is there any thorough testing happened for shared subscription using paho.mqtt.golang with either v3 or v5 broker? If Yes, can I get some references please.

**Comment by MattBrittan** [comment]
The feature is implemented in the broker; it has almost no impact on the client (the one possible impact is ignoring the $share/groupname in the router, which this library does).

**Comment by Abhijithm2447** [comment]
Just for confirmation, what is the meaning of router in your comment? Is it topic name or broker or something else?

**Comment by MattBrittan** [comment]
>what is the meaning of router in your comment?

The [router](https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L133) is part of this library; it's what works out what user functions should be called when a PUBLISH is received. So when you call:

```
t := c.Subscribe(TOPIC, QOS, h.handle)
```

The client adds an entry in the router such that messages to `TOPIC` will result in `h.handle` being called. The reason that this needs to take shared subscriptions into account is that if you call:


```
t := c.Subscribe(`$share/group1/foo`, QOS, h.handle)
```

Then the broker will deliver messages with the topic `foo` (not `$share/group1/foo`). So we need to remove the `$share/group1/` when adding the entry in the router.
