### ISSUE TITLE
packets.(*PingreqPacket).Write(0xc8200f3b60, 0x0, 0x0, 0x0, 0x0), invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by carl-leopard** [eclipse/paho.mqtt.golang#65]
panic: runtime error: invalid memory address or nil pointer dereference
 [signal 0xb code=0x1 addr=0x20 pc=0x561e72]
 goroutine 38 [running]:
 bytes.(*Buffer).WriteTo(0xc82048adf8, 0x0, 0x0, 0x0, 0x0, 0x0)
     /usr/local/go/src/bytes/buffer.go:206 +0xc2
 org.eclipse.paho.mqtt.golang.git/packets.(*PingreqPacket).Write(0xc8200f3b60, 0x0, 0x0, 0x0, 0x0)
    org.eclipse.paho.mqtt.golang.git/packets/pingreq.go:23 +0x83               
 org%2eeclipse%2epaho%2emqtt%2egolang%2egit.keepalive(0xc8201dc300)
    org.eclipse.paho.mqtt.golang.git/ping.go:60 +0x77a
 created by org%2eeclipse%2epaho%2emqtt%2egolang%2egit.(*Client).Connect.func1
   org.eclipse.paho.mqtt.golang.git/client.go:212 +0x13a1

using it in my project, after running a few days(maybe 10, 0000 times), packets.(*PingreqPacket).Write(0xc8200f3b60, 0x0, 0x0, 0x0, 0x0) will write fail case the err above "invalid memory address or nil pointer dereference"

i use the packets like this :
func main() { 
   client := MQTT.NewClient(opts)
   go publishMessage(
      client.Publish() //will be exec every 3 seconds
    )
  client.Subscribe()
}

**Comment by alsm** [comment]
It looks from the trace there as though you might be using an old version of the library, the repository at org.eclipse.paho.mqtt.golang.git is not up to date compared to the github.com hosted one. Please ensure you are have downloaded and are importing `"github.com/eclipse/paho.mqtt.golang"`

**Comment by carl-leopard** [comment]
It doesn't work. Thanks anyway.

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
