### ISSUE TITLE
Feature Request: support json.RawMessage as payload for publishing messages

### ISSUE THREAD

**Issue by joshuar** [eclipse/paho.mqtt.golang#651]
Hey there,

I've been using `json.RawMessage` in a program, as I have a situation where I need to publish different messages that kinda are the same but might have all different bits in the JSON. So `json.RawMessage`, which is just a `[]byte` anyway, works nicely.

It looks like the client code does not recognise a payload that is a `json.RawMessage`, so you get an "unknown payload type" error when using it. 

Was wondering if there would be a possibility/interest to support `json.RawMessage` as a payload type?

**Comment by MattBrittan** [comment]
It would be a very quick addition; feel free to submit a PR (alternatively just converting, `[]byte(rawMsg)` is pretty much a no-op).
