### ISSUE TITLE
Token.Wait() crashes

### ISSUE THREAD

**Issue by traveltoaiur** [eclipse/paho.mqtt.golang#68]
`b.MqttClient = MQTT.NewClient(opts)`
`if token := b.MqttClient.Connect(); token.Wait() && token.Error() != nil { .............`

After narrowing it down I found the problem to be with .Wait() function.
Everytime I enter a wrong broker URL with a white space in it(in the middle, or at the end of the string...) the  .Wait() function of the client.connect() token crashes the whole program and I can't figure out how to intercept this as the function doesn't allow error handling.

token.Error() is nil
b.MqttClient.Connect() works fine, this is the token I get
&{baseToken:{m:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} complete:0xc4200633e0 ready:false err:<nil>} returnCode:0}

This is the panicking error I get 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x581117]

**Comment by alsm** [comment]
in options.go this function handles adding servers to the list of brokers to connect to
```go
func (o *ClientOptions) AddBroker(server string) *ClientOptions {
	brokerURI, _ := url.Parse(server)
	o.Servers = append(o.Servers, brokerURI)
	return o
}
```
As you can see we ignore the err returned from url.Parse() which will happen when you try and add an invalid url such as one with a space in, which results in a nil entry being added to the slice.

**Comment by alsm** [comment]
The change I've made won't add the url to the slice if the parse fails, but it will do this silently.
