### ISSUE TITLE
Dockerfile not building image because of go.sum not updated with dependencies

### ISSUE THREAD

**Issue by JefJrFigueiredo** [eclipse/paho.mqtt.golang#690]
In this directory https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/docker , 
I've followed the instructions, which said: 
"Ensure that you have docker and docker-compose installed.

To start everything up change into the cmd/docker folder and run:

`docker-compose up --build --detach` "

But I've got this error:

=> ERROR [sub build-env 4/4] RUN go build -gcflags "all=-N -l" -o /sub                                                                                                                               0.8s
 => ERROR [pub build-env 4/4] RUN go build -gcflags "all=-N -l" -o /pub                                                                                                                               0.7s
------
 > [sub build-env 4/4] RUN go build -gcflags "all=-N -l" -o /sub:
0.695 main.go:27:2: missing go.sum entry for module providing package github.com/eclipse/paho.mqtt.golang (imported by subscriber); to add:
0.695   go get subscriber
------
------
 > [pub build-env 4/4] RUN go build -gcflags "all=-N -l" -o /pub:
0.696 main.go:26:2: missing go.sum entry for module providing package github.com/eclipse/paho.mqtt.golang (imported by publisher); to add:
0.696   go get publisher
------
failed to solve: process "/bin/sh -c go build -gcflags \"all=-N -l\" -o /pub" did not complete successfully: exit code: 1

I've already solved that by adding `go mod tidy &&` before `go build -gcflags` in cmd/docker/publisher/dockerfile and cmd/docker/subscriber/dockerfile. After that, `docker-compose up --build --detach` runs smoothly:

Attaching to mosquitto-1, pub-1, sub-1
mosquitto-1  | chown: /mosquitto/config/mosquitto.conf: Read-only file system
mosquitto-1  | chown: /mosquitto/config: Read-only file system
mosquitto-1  | chown: /mosquitto/config: Read-only file system
mosquitto-1  | 2024-09-03T08:18:26: mosquitto version 2.0.18 starting
mosquitto-1  | 2024-09-03T08:18:26: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto-1  | 2024-09-03T08:18:26: Opening ipv4 listen socket on port 1883.
mosquitto-1  | 2024-09-03T08:18:26: Opening ipv6 listen socket on port 1883.
mosquitto-1  | 2024-09-03T08:18:26: mosquitto version 2.0.18 running
mosquitto-1  | 2024-09-03T08:18:26: New connection from 172.20.0.3:34322 on port 1883.
mosquitto-1  | 2024-09-03T08:18:26: New client connected from 172.20.0.3:34322 as mqtt_subscriber (p2, c1, k10).
mosquitto-1  | 2024-09-03T08:18:26: No will message specified.
mosquitto-1  | 2024-09-03T08:18:26: Sending CONNACK to mqtt_subscriber (0, 0)
sub-1        | Connection is up
sub-1        | connection established
mosquitto-1  | 2024-09-03T08:18:26: Received SUBSCRIBE from mqtt_subscriber
mosquitto-1  | 2024-09-03T08:18:26:     topic1 (QoS 1)
mosquitto-1  | 2024-09-03T08:18:26: mqtt_subscriber 1 topic1
mosquitto-1  | 2024-09-03T08:18:26: Sending SUBACK to mqtt_subscriber
sub-1        | subscribed to:  topic1
mosquitto-1  | 2024-09-03T08:18:26: New connection from 172.20.0.4:56042 on port 1883.
mosquitto-1  | 2024-09-03T08:18:26: New client connected from 172.20.0.4:56042 as mqtt_publisher (p2, c1, k10).
mosquitto-1  | 2024-09-03T08:18:26: No will message specified.
mosquitto-1  | 2024-09-03T08:18:26: Sending CONNACK to mqtt_publisher (0, 0)
pub-1        | Connection is up
pub-1        | connection established
pub-1        | sending message: {"Count":1}
mosquitto-1  | 2024-09-03T08:18:27: Received PUBLISH from mqtt_publisher (d0, q1, r0, m1, 'topic1', ... (11 bytes))
mosquitto-1  | 2024-09-03T08:18:27: Sending PUBLISH to mqtt_subscriber (d0, q1, r0, m1, 'topic1', ... (11 bytes))
mosquitto-1  | 2024-09-03T08:18:27: Sending PUBACK to mqtt_publisher (m1, rc0)
sub-1        | received message: {"Count":1}
mosquitto-1  | 2024-09-03T08:18:27: Received PUBACK from mqtt_subscriber (Mid: 1, RC:0)
pub-1        | sending message: {"Count":2}

**Comment by MattBrittan** [comment]
Apologies - looks like this was introduced by the last commit (that just updated delendencies). Running `go mod tidy` in the pub/sub folder resolves this (but your solution looks a better long term fix).
