### ISSUE TITLE
How to set a SOCKS5 proxy in code?

### ISSUE THREAD

**Issue by m7rick** [eclipse/paho.mqtt.golang#694]
I want to set the proxy directly in the code, but I haven't found the relevant method. Could you provide an example?

**Comment by MattBrittan** [comment]
There is an [http proxy example](https://github.com/eclipse/paho.mqtt.golang/tree/master/cmd/httpproxy) (have not personally used or tested this but it would be a good place to start). The library provides the ability to provide your own dialer (e.g. [`SetDialer`](https://pkg.go.dev/github.com/eclipse/paho.mqtt.golang#ClientOptions.SetDialer)) so it should be pretty easy to work with SOCKS5. Sorry - I'm not going to write a custom example (and doubt anyone else will). 
Note: This area is intended for issues/bugs - please see the [readme](https://github.com/eclipse/paho.mqtt.golang?tab=readme-ov-file#more-information) for the appropriate places to ask questions (but note that, to get a decent response, you will probably need to show your attempt at accompliching this and provide more detail - e.g. is the connection type MQTT/MQTTS/WS or WSS etc).

**Comment by m7rick** [comment]
Thanks
