### ISSUE TITLE
Crash when using SetCleanSession(false)

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.golang#7]
migrated from Bugzilla [#483372](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483372)
status UNCONFIRMED severity *normal* in component *MQTT-Go* for *1.2*
Reported in version *unspecified* on platform *PC*
Assigned to: Al Stockdill-Mander

On 2015-12-01 06:34:24 -0500, sam Nay wrote:

> I get the following trace when I try to connect with SetCleanSession(false). Things work fine with SetCleanSession(true).
> 
> ---------
> 
> panic: Network Error : %!s(<nil>)
> 
> goroutine 16 [running]:
> runtime.panic(0x28b820, 0xc208000d40)
> 	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
> main.main()
> 	/Users/Foo/Work/Go/src/github.com/bar/rabbitmq/tutorial/mqtt_receiver.go:24 +0x24b
> 
> goroutine 19 [finalizer wait]:
> runtime.park(0x14e70, 0x4910d0, 0x48fbc9)
> 	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
> runtime.parkunlock(0x4910d0, 0x48fbc9)
> 	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
> runfinq()
> 	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
> runtime.goexit()
> 	/usr/local/go/src/pkg/runtime/proc.c:1445
> 
> goroutine 17 [syscall]:
> runtime.goexit()
> 	/usr/local/go/src/pkg/runtime/proc.c:1445
> exit status 2
> 
> ------------
> 
> My code is:
> 
> func main() {
> 	opts := mqtt.NewClientOptions().AddBroker("tcp://localhost:1883/")
> 	opts.SetClientID("clientB")
> 	opts.SetDefaultPublishHandler(mqttFunc)
> 	opts.SetCleanSession(false)
> 
> 	c := mqtt.NewClient(opts)
> 	token := c.Connect()
> 	if token.Wait() && token.Error() != nil {
> 		panic(token.Error())  // *** Crashes here ***
> 	}
> 
> ...

On 2015-12-01 06:44:00 -0500, sam Nay wrote:

> I just tried creating a connection with a new ClientId and things work. Seems like I cannot connect with cleanSession=false, when using the same ClientId that has previously created a connection with cleanSession=true. Was not aware that there was a limitation like this. Even if there was, I assume there should be a better error message?
> 
> Seems like the connection needs to be properly disconnected before you can reconnect with a different cleanSession value.

On 2015-12-01 08:01:03 -0500, Al Stockdill-Mander wrote:

> That's not behaviour I am familiar with and sounds like a configuration issue with the mqtt server you're using. What are you using as your mqtt server?

**Comment by alsm** [comment]
Closing as no follow up and sounds like a server configuration issue.
