### ISSUE TITLE
certificate validation fails for servers behind load balancer

### ISSUE THREAD

**Issue by tomazbracic** [eclipse/paho.mqtt.golang#71]
Using a client within setup where TLS is terminated behind load balancer (HAProxy behind AWS ELB with proxy protocol enabled) results in error. Error is like "certificate is valid for IP of server behind ELB and not server used in command execution (-server). 

I have to specify ELB (entry point) under -server, but nothing should happen there. TLS should be terminated behind. I use HAProxy for termination, which then redirects TLS offloaded traffic to broker on port 1883. I use certificates on server side and clients use certificates.

**Comment by alsm** [comment]
This is not a client issue but a TLS one, if you tell your client you're connecting to abc.com and it receives back a certificate that says it is for xyz.com, it's not going to validate. Can you not do TLS termination on the ELB, and if necessary have a separate TLS session from the ELB to HAProxy.

**Comment by tomazbracic** [comment]
AWS ELB does not support Client Certificates. That's why I do TLS termination behind on 2 nodes of HAProxy. Paho golang client thinks that my -server directive is where TLS termination and cert should be equal, but certificate that is gained from behind ELB is reporting CN of that server. Isn't this a problem of paho golang client 'interpretation'? It should ignore my -server directive since this is basically gateway to my infrastructure?

**Comment by alsm** [comment]
The client connects to the system it's told is the server, it doesn't know anything about how your system handles the connections and, as far as it's concerned the tcp connection ends at the -server, so when using TLS that is the host/ip it expects the certificate to match, telling a client to accept a certificate that doesn't match the host it's connecting to compromises the security of TLS. One way to allow it though is to change the TLSConfig used by the client. The ClientOptions struct allows you to set your own TLSConfig (https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L54) and the Go tls.Config (https://golang.org/pkg/crypto/tls/#Config) has a field `InsecureSkipVerify` this will allow the connection but as it warns allows MITM attacks.

**Comment by tomazbracic** [comment]
I solved this by adding subjectAltName in openssl.cnf while creating .csr. Added one DNS and 2 IPs. Solved.
