### ISSUE TITLE
Connecting to AWS IoT

### ISSUE THREAD

**Issue by mark2b** [eclipse/paho.mqtt.golang#72]
Do you have example of connection to AWS IoT. I have all certificates and keys, but can't connect to the broker.

Got "Network Error : %!s(<nil>)"

**Comment by adityashedge** [comment]
Can you create [playground](play.golang.org) link? Don't add your AWS credentials anywhere. I'll test with my account.

**Comment by mark2b** [comment]
https://play.golang.org/p/mrPIJ2XYf6

**Comment by sebastianvera** [comment]
@mark2b I recently connected my app to AWS IoT service, here is a working example on how I achieve to do it, I hope is not too late :)

```golang
package main

import (
	"crypto/tls"
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	MQTT "github.com/eclipse/paho.mqtt.golang"
)

func main() {
	cer, err := tls.LoadX509KeyPair("/path/to/cert", "/path/to/key")
	check(err)

	cid := "ClientID"

	connOpts := &MQTT.ClientOptions{
		ClientID:             cid,
		CleanSession:         true,
		AutoReconnect:        true,
		MaxReconnectInterval: 1 * time.Second,
		KeepAlive:            30 * time.Second,
		TLSConfig:            tls.Config{Certificates: []tls.Certificate{cer}},
	}

	host := "myawsioturl.iot.us-west-2.amazonaws.com"
	port := 8883
	path := "/mqtt" 

	brokerURL := fmt.Sprintf("tcps://%s:%d%s", host, port, path)
	connOpts.AddBroker(brokerURL)

	mqttClient := MQTT.NewClient(connOpts)
	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	log.Println("[MQTT] Connected")

	quit := make(chan struct{})
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		mqttClient.Disconnect(250)
		fmt.Println("[MQTT] Disconnected")

		quit <- struct{}{}
	}()
	<-quit
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
```

**Comment by tgruben** [comment]
In my instance using the above code, I receive events fine for the first 10 minutes, then events are no longer received. Any thoughts on how to prevent this?  I assumed the keepalive would accommodate but it appears I'm incorrect.

**Comment by sebastianvera** [comment]
Yes, that's because we are not using the default settings, here's the updated code:

```golang
package main

import (
	"crypto/tls"
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	MQTT "github.com/eclipse/paho.mqtt.golang"
)

func main() {
	cer, err := tls.LoadX509KeyPair("/path/to/cert.pem", "/path/to/private.key")
	check(err)

	cid := "ClientID"

	// AutoReconnect option is true by default
	// CleanSession option is true by default
	// KeepAlive option is 30 seconds by default
	connOpts := &MQTT.NewClientOptions()
	connOpts.SetClientID(cid)
	connOpts.SetMaxReconnectInterval(1 * time.Second)
	connOpts.SetTLSConfig(&tls.Config{Certificates: []tls.Certificate{cer}})

	host := "myawsioturl.iot.us-west-2.amazonaws.com"
	port := 8883
	path := "/mqtt"

	brokerURL := fmt.Sprintf("tcps://%s:%d%s", host, port, path)
	connOpts.AddBroker(brokerURL)

	mqttClient := MQTT.NewClient(connOpts)
	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	log.Println("[MQTT] Connected")

	quit := make(chan struct{})
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		mqttClient.Disconnect(250)
		fmt.Println("[MQTT] Disconnected")

		quit <- struct{}{}
	}()
	<-quit
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
```

**Comment by sebastianvera** [comment]
Did it work? @tgruben

**Comment by tgruben** [comment]
no, it still works great for about 10 minutes then it quits responding to
publications

**Comment by eran0lavi** [comment]
I have the same issue of:
panic: Network Error : %!s(<nil>)

in "mqttClient.Connect()"
token.Error()  is not nil and I recive the panic error,

The looking at the log I can that:
- socket connected to broker.
- connect started.

but just then it recives:
connect got error EOF.

why do I get that?
and what am I doing wrong in order to connect?

here is the logging for "pato.mqtt.golang"
And it gives me the following trace:

[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1.1 protocol
[net]      connect started
[net]      connect got error EOF
[client]   Trying reconnect using MQTT 3.1 protocol
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1 protocol
[net]      connect started
[net]      connect got error EOF
[client]   Failed to connect to a broker
[store]    memorystore closed

 Regards
Eran.

**Comment by eran0lavi** [comment]
here is my code:
``	///Start/////////////////////////////////

	cer, err := tls.LoadX509KeyPair("path/f8527f7924-certificate.pem", "path/f8527f7924-private.pem.key")
	check(err)
	topic := "anom/pred"
	qos := 1

	//cid := "ClientID"
	cid := "ad82c26c-3674-fb9f-44ec-15c0b59a0ed6"

	connOpts := &MQTT.ClientOptions{
		ClientID:             cid,
		CleanSession:         true,
		AutoReconnect:        true,
		MaxReconnectInterval: 1 * time.Second,
		KeepAlive:            30 * time.Second,
		TLSConfig:            tls.Config{Certificates: []tls.Certificate{cer}},
	}

//	host := "myawsioturl.iot.us-west-2.amazonaws.com"
	host := "a3a5un32wgqe74.iot.us-east-1.amazonaws.com"
	mqttPort := 8883
	path := "/mqtt"

	brokerURL := fmt.Sprintf("tcps://%s:%d%s", host, mqttPort, path)
//	brokerURL := "tcps://a3a5un32wgqe74.iot.us-east-1.amazonaws.com:8883"
	connOpts.AddBroker(brokerURL)

	received := 0

	connOpts.SetDefaultPublishHandler(func(client MQTT.Client, msg MQTT.Message) {
		s := string(msg.Payload())
		log.Printf("%d heard %s %s", received, msg.Topic(), s)
		t, err := time.Parse(time.RFC3339Nano, s)
		if err != nil {
			log.Printf("message '%s' not a time", s)
		} else {
			log.Printf("elasped %dms", int(time.Now().Sub(t).Seconds()*1000))
		}
		received++
	})

	mqttClient := MQTT.NewClient(connOpts)
	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}

	// Subscribe
	go func() {
		log.Printf("subscribing")
		if token := mqttClient.Subscribe(topic, byte(qos), nil); token.Wait() && token.Error() != nil {
			fmt.Println(token.Error())
			os.Exit(1)
		}
		log.Printf("subscribed")

	}()
	log.Println("[MQTT] Connected")

**Comment by sebastianvera** [comment]
@eran0lavi can you try with the second example that I posted? The first one is slightly wrong 😅

**Comment by eran0lavi** [comment]
Hi Sebastian,

After Changing the code I still get:
panic: Network Error : %!s(<nil>)

I belive that is someting to do with the certificates.

Sebastian Can describe how you created the certificates?

I would like to create them exaclly like you have.

Regards
Eran

**Comment by aldrinlealataurea** [comment]
@eran0lavi since you're the only reference of this EOF issue on Google, I'm making it here to help you document:

EOF happens when you have a certificate without a policy. Create / Attach one into the certificate and it should work

**Comment by aldrinlealataurea** [comment]
@tgruben btw, 10 minutes might be related to AWS Usage of Stateful Firewalls. See if you can set a keepalive interval, like 30 seconds. It will send a ping packet and refresh the firewall state.

**Comment by aldrinleal** [comment]
Also, enable cloudwatch logs and read it closely. In my case, I've forgotten iot:Connect and iot:Receive.

http://docs.aws.amazon.com/iot/latest/developerguide/connect-policy.html

**Comment by jadekler** [comment]
Hi @eran0lavi @mark2b 

I've had the same problem (`panic: Network Error : %!s(<nil>)`) and figured out the problem for me:

In your AWS IoT certificate policy list you need the following statement:

```
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-east-1:<whatever-account>:client/myClientId"
    },
```

Then, you can use `myClientId` as your client id. I believe you can use `:client/*` if you want to accept any clients.

**Comment by jadekler** [comment]
I'm unable to subscribe at the moment though, if anyone has tips on that. It's just stuck at `token := mqttClient.Subscribe(..); token.Wait()`

**Comment by MetalBlueberry** [comment]
TIP, Read aws docs 
https://docs.aws.amazon.com/iot/latest/developerguide/action-resources.html
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:XXXXXXXXXX:thing/{ID}"
      ]
    }
  ]
}
```
This policy allows only the connection of clients with the ID that you specify here.
seriously, read the docs carefully, is complex and everything is explained there.

btw: Thank you for the post, this helped me to create my go client

**Comment by charles-d-burton** [comment]
I'm still having issues with this.  My code is here:
https://github.com/charles-d-burton/aws-mqtt/blob/master/cmd/start.go

No matter what I do, most of the time I get this error when I try to subscribe:
Connection lost before Subscribe completed

I'm passing in the TLS certificates provided by Amazon when I setup the project.  In addition I have those attached to a policy that looks like this:
```json
{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ],
  "Version": "2012-10-17"
}
```

The policy is wide open, but more often than not I get that connection error when I try to connect.

**Comment by dolanor** [comment]
For a weird reason, I set `cOpts.SetCleanSession(false)`
And I got those messages also. Should be more explicit, but it's hard since AWS just closes the connection and we get a `io.EOF` on ReadPacket().

**Comment by johnhydroware** [comment]
FYI AWS now supports SetCleanSession(false)

**Comment by johnhydroware** [comment]
> Just curious. Is it possible or not to get a stable connection from Paho to AWS?

It works fine for me.

**Comment by votiakov** [comment]
Did anybody find what causes this issue? I am having the same error: `Network Error : %!s(<nil>)`

@johnhydroware do you have any tips?

**Comment by michilu** [comment]
You can also implement the logger to get more information about the problem.
https://github.com/eclipse/paho.mqtt.golang/blob/99e16732783b84a6edbe5dc86d6ac394402fecba/trace.go#L17-L40

**Comment by nitinkap** [comment]
please help with this error 
panic: Network Error : %!s()

i Have policy attached and certs as well but still this error .....
policy below

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.

**Comment by bluewelkin** [comment]
`package test

import (
"crypto/tls"
"fmt"
"log"
"os"
"os/signal"
	"testing"
	"time"

	MQTT "github.com/eclipse/paho.mqtt.golang"
)

func TestMqttConnectionFromGithub(t *testing.T) {
	cer, err := tls.LoadX509KeyPair("your-certificate.pem.crt", "your-private.pem.key")

	check(err)

	cid := "ClientID"

	// AutoReconnect option is true by default
	// CleanSession option is true by default
	// KeepAlive option is 30 seconds by default
	connOpts := MQTT.NewClientOptions()
	// This line is different, we use the constructor function instead of creating the instance ourselves.
	connOpts.SetClientID(cid)
	connOpts.SetMaxReconnectInterval(1 * time.Second)
	connOpts.SetTLSConfig(&tls.Config{Certificates: []tls.Certificate{cer}})

	host := "your-aws-host-add"
	port := 8883
	path := "/mqtt"

	brokerURL := fmt.Sprintf("tcps://%s:%d%s", host, port, path)
	connOpts.AddBroker(brokerURL)

	mqttClient := MQTT.NewClient(connOpts)
	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	log.Println("[MQTT] Connected")
	update := `{
    "state": {
        "desired" : {
            "color" : { "r" : 10 },
            "engine" : "ON"
        }
    }
}`
	fmt.Println("Sending update.")
	if token := mqttClient.Publish("sdk/test/Python", 0, false, update); token.Wait() && token.Error() != nil {
		log.Fatalf("failed to send update: %v", token.Error())
	}
	fmt.Println("Sending Successfully.")


	quit := make(chan struct{})
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		mqttClient.Disconnect(250)
		fmt.Println("[MQTT] Disconnected")

		quit <- struct{}{}
	}()
	<-quit
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
`


then add connect-policy,such as 
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "arn:aws-cn:iot:cn-north-1:090321107501:client/*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": [
        "arn:aws-cn:iot:cn-north-1:090321107501:topic/sdk/test/Python",
        "arn:aws-cn:iot:cn-north-1:090321107501:topic/sdk/test/java22"
      ]
    },
    {
      "Effect": "Allow",
      "Action": "iot:RetainPublish",
      "Resource": "arn:aws-cn:iot:cn-north-1:090321107501:topic/*"
    }
  ]
}`

**Comment by bluewelkin** [comment]
then add connect-policy,such as
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "arn:aws-cn:iot:cn-north-1:090321107501:client/*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": [
        "arn:aws-cn:iot:cn-north-1:090321107501:topic/sdk/test/Python",
        "arn:aws-cn:iot:cn-north-1:090321107501:topic/sdk/test/java22"
      ]
    },
    {
      "Effect": "Allow",
      "Action": "iot:RetainPublish",
      "Resource": "arn:aws-cn:iot:cn-north-1:090321107501:topic/*"
    }
  ]
}`

**Comment by moneroexamples** [comment]
I just had this issue and spend all day troubleshooting this, until I found this thread and the hint about **certificate policies**.  My code had nothing to do with the issue, it was the policies. Just for reference, to get certificate policies go to `Manage->Security->Policies`:


![image](https://user-images.githubusercontent.com/15305358/230765597-2f7ae898-f25f-421b-9a7d-013fcda4587b.png)

Then when you open the policy, check its `JSON` and verify `iot:Connect` permissions (fragment showed):

```
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:xxxx:client/sdk-java",
        "arn:aws:iot:us-east-1:xxxx:client/basicPubSub",
        "arn:aws:iot:us-east-1:xxxx:client/sdk-nodejs-*"
      ]
    }
```

The names `sdk-java`, `basicPubSub`,`sdk-nodejs-*` are the names of client in my Go code that I had to use. In other words, you can't just set random ClientIDs in your Go code. If the policy says, e.g. `client/basicPubSub`, then the Go client must use `ClientId := "basicPubSub"`.

Below is the code that worked for me after changing the ClientId. Is is based on: https://adrianhesketh.com/2019/11/04/aws-iot-with-go/

```
package main

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io/ioutil"
	"log"

	mqtt "github.com/eclipse/paho.mqtt.golang"
)

const brokerUrl string = "a1yk76hc7i0xqz-ats.iot.us-east-1.amazonaws.com"

var f mqtt.MessageHandler = func(client mqtt.Client, msg mqtt.Message) {
	fmt.Printf("TOPIC: %s\n", msg.Topic())
	fmt.Printf("MSG: %s\n", msg.Payload())
}

func main() {

	tlsconfig, err := NewTLSConfig()

	if err != nil {
		log.Fatalf("failed to create TLS configuration: %v", err)
	}

	opts := mqtt.NewClientOptions()
	opts.AddBroker("tls://" + brokerUrl + ":8883")
	opts.SetClientID("basicPubSub").SetTLSConfig(tlsconfig)

	// Start the connection.
	c := mqtt.NewClient(opts)
	if token := c.Connect(); token.Wait() && token.Error() != nil {
		log.Fatalf("failed to create connection: %v", token.Error())
	}

	log.Println("[MQTT] connected")

	c.Disconnect(0)
}

// Adapted from https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/ssl/main.go
// Also see https://www.eclipse.org/paho/clients/golang/
// https://adrianhesketh.com/2019/11/04/aws-iot-with-go/
func NewTLSConfig() (config *tls.Config, err error) {
	// Import trusted certificates from CAfile.pem.
	certpool := x509.NewCertPool()
	pemCerts, err := ioutil.ReadFile("./AmazonRootCA1.pem")
	if err != nil {
		log.Fatalf("ReadFile: %v", err)
		return
	}
	certpool.AppendCertsFromPEM(pemCerts)

	// Import client certificate/key pair.
	cert, err := tls.LoadX509KeyPair(
		"./connect_device_package/dlc-thing.cert.pem",
		"./connect_device_package/dlc-thing.private.key")

	if err != nil {
		log.Fatalf("failedLoadX509KeyPair: %v", err)
		return
	}

	// Create tls.Config with desired tls properties
	config = &tls.Config{
		// RootCAs = certs used to verify server cert.
		RootCAs: certpool,
		// ClientAuth = whether to request cert from server.
		// Since the server is set up for SSL, this happens
		// anyways.
		ClientAuth: tls.NoClientCert,
		// ClientCAs = certs used to validate client cert.
		ClientCAs: nil,
		// Certificates = list of certs client sends to server.
		Certificates: []tls.Certificate{cert},
	}
	return
}
```
