### ISSUE TITLE
missing PUBACK not recognized ?!

### ISSUE THREAD

**Issue by mfick76** [eclipse/paho.mqtt.golang#76]
Hi,
i have a simple MQTT Client which publishes messages to a MQTT Broker using QoS1.
If the broker did not send the PUBACK or it got lost then i would think the WaitTimout function used with the token from Client.publish should run in a timeout ?

I used following code:

```
 timer := time.NewTicker(1 * time.Second)
   for t := range timer.C {
      if initialized == 1 {
         token := cli.Publish(topic, 1, false, t.String())
         if( !token.WaitTimeout(5000) ) {
           if( token.Error() != nil ) {
              fmt.Println(token.Error())
           } else {
              mutex.Lock()
              sent = sent + 1
              mutex.Unlock()
           }
         } else {
            fmt.Println("timeout ACK");
         }
      }
   }
```

I have checked that the PUBACK from the Broker is missing by using a different Client written with the paho-mqtt3c library.

best regards
Markus

**Comment by alsm** [comment]
Hi, WaitTimeout returns false if it times out, I think the if statement you have should not have the ! in it.
