### ISSUE TITLE
auto-reconnect not working for initial connection attempt.

### ISSUE THREAD

**Issue by databus23** [eclipse/paho.mqtt.golang#77]
This is a follow up on #52, maybe, sort of, I don't know...
I might be missing something here, it seems to me that the re-connect logic is not kicking in for the initial connection to the broker.
Only when the initial connection is successful, the client goes into a reconnect loop whenever the connection is lost.

Is this by design? If so this would mean users of the client would need to implement a second reconnect logic outside of the client to cover all cases. Otherwise they are stuck with disconnected client when the broker happened to be unreachable when the client starts up.

**Comment by kylycht** [comment]
@databus23 initial connection can be inside a loop

so something like 
```
retry := time.NewTicker(5 * time.Second)
RetryLoop:
	for {
		select {
		case <-retry.C:
			if token := client.Connect(); token.Wait() && token.Error() != nil {
				//handle error
			} else {
				retry.Stop()
				break RetryLoop
			}
		}
	}
```
this will try to connect every 5 seconds, once connection is established it will break out the loop
if connection is lost, re-connect should kick in
hope this helps to solve your problem

**Comment by alsm** [comment]
This is working as designed, in that there was no intention to do automatic reattempts to connect on initial connection. If you have specified multiple servers to connect to the client will attempt to connect to each in turn if it fails to connect to the previous one, and if we are in automatic version mode we will attempt to connect at version 3 if version 4 was unsuccessful.
When I say as designed though, there was no explicit thought that it should not, at some point, do automatic connection reattempts at initial connection, it just wasn't written that way.

**Comment by masc3d** [comment]
I don't see how this is a good reason to close this. 
The reconnection feature is incomplete and inconsistent this way.

**Comment by huntc** [comment]
I'd like to add that I got caught out majorly on this. I'd assert that most times, there's just one URI to connect - particularly given when service discovery is in place. The distinction between an initial connection and retrying a connection is, for me at least, unintuitive and diminishes the usefulness of auto-reconnect.
