### ISSUE TITLE
occasional deadlock when connections are lost.

### ISSUE THREAD

**Issue by databus23** [eclipse/paho.mqtt.golang#83]
Every now and then I'm having clients getting stuck with something that seems like an logic deadlock.
The clients are running with critical and error logging (so mqtt warning and debug logs are not printed).
The only message I see in the logs is
```
MQTT CRITICAL [pinger]   pingresp not received, disconnecting
```
After this message nothing seems to happens anymore.

I finally managed to take a stckdump and this is what the relevant goroutines look like. From the timing perspective this matches closely with the above error message: The error was logged about 108 minutes before I took the stackdump. 
```
goroutine 40 [semacquire, 108 minutes]:
sync.runtime_notifyListWait(0xc4202b1240, 0xc400000001)
	/usr/local/go/src/runtime/sema.go:297 +0x10b
sync.(*Cond).Wait(0xc4202b1230)
	/usr/local/go/src/sync/cond.go:57 +0x89
io.(*pipe).read(0xc4202b1200, 0xc4202d603e, 0xfc2, 0xfc2, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0x104
io.(*PipeReader).Read(0xc42016e0e0, 0xc4202d603e, 0xfc2, 0xfc2, 0xc42005de58, 0x6ccd3a, 0xc42020d040)
	/usr/local/go/src/io/pipe.go:130 +0x4c
bufio.(*Scanner).Scan(0xc42005df40, 0xc42019bf30)
	/usr/local/go/src/bufio/scan.go:207 +0x294
github.wdf.sap.corp/monsoon/arc/vendor/github.com/Sirupsen/logrus.(*Logger).writerScanner(0xc42020d040, 0xc42016e0e0)
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/Sirupsen/logrus/writer.go:20 +0x86
created by github.wdf.sap.corp/monsoon/arc/vendor/github.com/Sirupsen/logrus.(*Logger).Writer
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/Sirupsen/logrus/writer.go:12 +0x107

goroutine 51 [semacquire, 108 minutes]:
sync.runtime_Semacquire(0xc42018549c)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc420185490)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost(0xc420185180, 0xb925e0, 0xc420859890)
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho.mqtt.golang/client.go:423 +0x7e
github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho%2emqtt%2egolang.keepalive(0xc420185180)
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho.mqtt.golang/ping.go:55 +0x75f
created by github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho.mqtt.golang/client.go:242 +0xc40

goroutine 52 [chan send, 108 minutes]:
github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho%2emqtt%2egolang.incoming(0xc420185180)
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho.mqtt.golang/net.go:90 +0x329
created by github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/tmp/build/80754af9/gopath/src/github.wdf.sap.corp/monsoon/arc/vendor/github.com/eclipse/paho.mqtt.golang/client.go:255 +0xab7
```

I think what happens is that the logic is stuck in [`internalConnectionLost`](https://github.com/eclipse/paho.mqtt.golang/blob/d4f545eb108a2d19f9b1a735689dbfb719bc21fb/client.go#L423) waiting for the workers to shutdown.
This seems to happened because the receiving side is stuck writing to [`c.ibound`](https://github.com/eclipse/paho.mqtt.golang/blob/d4f545eb108a2d19f9b1a735689dbfb719bc21fb/net.go#L90). So apparently the reading end of `c.ibound` inside the `alllogic` function is already gone. I also can't find any other goroutine in the stackdump that is related to the `alllogic`.

This bug seems to be triggered by an edge case when networking is flaky because it always shows this `[pinger]   pingresp not received, disconnecting` message and whenever this happens I have multiple clients that are stuck like this around the same time.

I'm using d4f545eb108a2d19f9b1a735689dbfb719bc21fb of the golang client library . But the [diff to latest master](https://github.com/eclipse/paho.mqtt.golang/compare/d4f545eb108a2d19f9b1a735689dbfb719bc21fb...master) does not look like it will make a difference

**Comment by databus23** [comment]
Looking at it some more the problem might be caused like this:

* the `keepalive` function get a timeout and calls `internalConnectionLost`(https://github.com/eclipse/paho.mqtt.golang/blob/dfe35ae8bd6ead198596c5e5f4af1f55914741cf/ping.go#L55)
* `internalConnectionLost` calls [`c.closeStop()`](https://github.com/eclipse/paho.mqtt.golang/blob/dfe35ae8bd6ead198596c5e5f4af1f55914741cf/client.go#L427)
* Closing this channel causes `alllogic` to [exit](https://github.com/eclipse/paho.mqtt.golang/blob/dfe35ae8bd6ead198596c5e5f4af1f55914741cf/net.go#L257)
* If the `incoming` receives another packet before or while the [connection is closed](https://github.com/eclipse/paho.mqtt.golang/blob/dfe35ae8bd6ead198596c5e5f4af1f55914741cf/client.go#L428)
* writing this to `c.ibound`(https://github.com/eclipse/paho.mqtt.golang/blob/dfe35ae8bd6ead198596c5e5f4af1f55914741cf/net.go#L90) blocks forever because there is nothing servicing that channel anymore.
* `internalConnectionLost` waits forever for `c.workers.Wait()` to return (https://github.com/eclipse/paho.mqtt.golang/blob/dfe35ae8bd6ead198596c5e5f4af1f55914741cf/client.go#L429)
* The client is now stuck with no connection

**Comment by alsm** [comment]
I'm going to close this now as it seems to be resolved.

**Comment by KMax** [comment]
Looks like we also faced this problem.

@alsm Are there any plan to make a release soon? Looks like the latest release was 8 months and 25 commits ago :)

**Comment by alsm** [comment]
@KMax The paho project in general was planning a service release for the end of June, and the Go client was going to go along with that. But given the importance of this fix I'll look into doing one sooner.

**Comment by foxxnuaa** [comment]
Hi,all:
i also met this problem yet.
when the network is not stable,i can see the log bellow:
**pingresp not received, disconnecting
error triggered, stopping
internalConnLost
incoming dropped a received message during shutdown
outgoing stopped
incoming stopped**
then no connections left and will not reconnect again.

this is in small chance.
but will lead to problem.
can you help solve this problem in new version?
