### ISSUE TITLE
Client sometimes disconnects right after publishing

### ISSUE THREAD

**Issue by MahlerFive** [eclipse/paho.mqtt.golang#89]
I created a simple client that connects to a broker and publishes a batch of messages every X seconds. For example, I may call publish 20 times with a message that is about 5k in size, and then repeat that every minute.  What I find is that the first batch of messages is seen by the broker, but subsequent batches are often completely missing or partially missing. When I added a trace I can see that sometimes after the 2nd batch of messages is published, the client gets disconnected and reconnects. That 2nd batch never actually seems to make it to the broker, despite there being no publish errors.

Here is how I create the client:

```
func NewClient(broker string, username string, password string, certCAFile string) (mq.Client, error) {
	opts := mq.NewClientOptions()
	opts.AddBroker(broker)
	opts.SetClientID(username)
	opts.SetUsername(username)
	opts.SetPassword(password)
	tls, err := newTLSConfig(certCAFile)
	if err != nil {
		return nil, errors.Wrap(err, "error creating TLS config")
	}
	opts.SetTLSConfig(tls)
	return mq.NewClient(opts), nil
}

func newTLSConfig(certCAFile string) (*tls.Config, error) {
	// Import trusted CA certificate
	certpool := x509.NewCertPool()
	pemCerts, err := ioutil.ReadFile(certCAFile)
	if err == nil {
		certpool.AppendCertsFromPEM(pemCerts)
	} else {
		return nil, errors.Wrap(err, "error loading CA cert file")
	}

	// Create tls.Config with desired tls properties
	return &tls.Config{
		RootCAs: certpool,
		ClientAuth: tls.NoClientCert,
		ClientCAs: nil,
		InsecureSkipVerify: true,
	}, nil
}
```

Here is how I connect initially (I never call connect again or disconnect anywhere in the code).

```
token := l.Client.Connect()
	if !token.WaitTimeout(l.ConnectTimeout) {
		return errors.New("timeout connecting to broker")
	}
	if token.Error() != nil {
		return errors.Wrapf(token.Error(), "error connecting to broker")
	}
```

And here is my publish code that gets called in a loop every few seconds or minutes.

```
func (l *LoadTester) sendPassiveReport(apMAC string, passiveReport []byte) {
	topic := fmt.Sprintf("3.0/LOC/greenfieldruckus/%s/PAR", apMAC)
	retained := false
	qos := byte(0)

	token := l.Client.Publish(topic, qos, retained, passiveReport)
	if !token.WaitTimeout(l.PublishTimeout) {
		// logging error here
	} else if token.Error() != nil {
		// logging error here
	}
}
```

Here is a trace after the last call to publish that shows the disconnect occurring.

> [client]   enter Publish
> [client]   sending publish message, topic: 3.0/LOC/greenfieldruckus/327C281854D8/PAR
> [net]      obound wrote msg, id: 0
> [net]      outgoing waiting for an outbound message
> [net]      resetting ping timers
> [client]   enter Publish
> [client]   sending publish message, topic: 3.0/LOC/greenfieldruckus/327C281854D8/PAR
> [net]      obound wrote msg, id: 0
> [net]      outgoing waiting for an outbound message
> [net]      resetting ping timers
> [net]      incoming stopped with error EOF
> [net]      logic received from error channel, other components have errored, stopping
> [pinger]   keepalive stopped
> [net]      outgoing stopped
> [client]   enter reconnect
> [client]   about to write new connect msg
> 2017-04-03T21:51:10Z info: connection lost: EOF
> [client]   socket connected to broker
> [client]   Using MQTT 3.1.1 protocol
> [net]      connect started
> [net]      received connack
> [client]   client is reconnected
> [net]      incoming started
> [net]      outgoing started
> [net]      outgoing waiting for an outbound message
> [net]      logic started
> [net]      logic waiting for msg on ibound
> [pinger]   keepalive starting

**Comment by alsm** [comment]
It's not clear why your client is getting disconnect, the EOF suggests that the broker is disconnecting your client from that end, if you have any logging there it might help determine what is happening.
I think the reason that you are losing messages is that the client is in a reconnecting state and the messages are QoS 0. https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L485 is the relevant line. When we are reconnecting and the QoS is 0 we don't actually send the packet. The reason for this is that the MQTT spec makes no guarantees about delivery for QoS 0 and from the client side we want to allow the application to continue to call publish() while we're reconnecting, so we store messages to be published is the client obound channel, which is of finite depth, so we throw away the QoS 0 publishes.
This happens in quite a few places in MQTT implementations, for example if you have a persistent session on a server most don't queue up QoS 0 messages that would have been sent to you if you were connected, essentially if there are any interruptions in the connection QoS 0 messages will be lost.

**Comment by MahlerFive** [comment]
I've hit this issue with my main application as well. Here is what happens:

- mosquitto and my client started up normally

- client successfully connects, subscribes to a few topics, and then sends a batch of publishes to various topics (a batch of publishes is about 20 different publishes, each to a different topic, with each message being only 11 bytes)

- mosquitto sees first batch of publishes from my client

- mosquitto sees the second batch of publishes from the client 5 minutes later (the interval between batches is 5 minutes)

- mosquitto does NOT see MOST of third batch of publishes from mqttd at the 10 minute mark. Below are example logs from mosquitto that show only 2 messages get published (out of about 20):

> 05:38:51
> 1491370731: Received PUBLISH from zenreach (d0, q0, r0, m0, '2.1/LOC/SMMug3jKfsoLKlXy/LS/PAQ', ... (11 bytes))
> 05:38:51
> 1491370731: Received PUBLISH from zenreach (d0, q0, r0, m0, '2.1/LOC/SMMug3jKfsoLKlXy/LS/PAQ', ... (11 bytes))

- during third batch of publishes, my client starts printing timeout errors on each publish (I'm using WaitTimeout() with a timeout of 5 seconds as shown in my original post)

- about 15 minutes after the errors started occurring, mosquitto disconnects the client user  because of timeout. This makes sense since the keepalive is set to 10 minutes and since mosquitto isn't receiving any publishes (or pings even), it should disconnect the client. Below is the log from mosquitto:

> 05:53:51
> 1491371631: Client zenreach has exceeded timeout, disconnecting.
> 05:53:51
> 1491371631: Socket error on client zenreach, disconnecting.

The question here is, why do all publishes just suddenly stop working on the 3rd batch (including pings)?

**Comment by alsm** [comment]
That's very odd, I'll look into it, might take me a few days to find the time to work it all out.

**Comment by MahlerFive** [comment]
I was able to obtain a packet capture for the first client which I've attached. Here is the breakdown of what I'm seeing:

Client: 172.16.0.114
Mosquitto Broker: 10.16.208.139 (port 8883)

The numbers below are the packet numbers in the capture file.
- 1: Client connects to broker
- 17?: Client starts publishing first batch of messages
- 386: First batch of messages complete
- 387: Client starts publishing second batch of messages
- 388: Missing packet?
- 389: Mosquitto ACKs packet 387
- 390: Mosquitto starts spamming TCP DUP ACK packets for 387
- 549: Mosquitto stops spamming TCP DUP ACK packets for 387
- 550-578: Lots of retransmissions
- 784: Second batch of messages complete
- 785: Third batch of messages starts
- 788: Mosquitto sends FIN ACK, closing the connection (WHY?)
- 790-880: Mosquitto responds to remaining messages with RST

The main question is why would mosquitto suddenly close the connection after starting to receiving the 3rd batch of messages. The logs in mosquitto at this point where the 3rd batch starts is here:

18:52:24
1491418344: OpenSSL Error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
18:52:24
1491418344: Socket error on client admin, disconnecting.

Does anyone know how an OpenSSL error would happen "while in init", if the connection has been open for a while? Note that the mosquitto broker currently supports connections by username/password over TLS using a cert (which is how this client is connecting), but also supports TLS-PSK from other clients.

Also, if mosquitto is sending back TCP RST on all the messages in the 3rd batch, why is the client not getting any errors when publishing? I'm checking for both timeout and errors every time.
[mqtt_filtered.pcap.zip](https://github.com/eclipse/paho.mqtt.golang/files/900942/mqtt_filtered.pcap.zip)

**Comment by MahlerFive** [comment]
This error was caused by an issue in mosquitto: https://github.com/eclipse/mosquitto/issues/419

**Comment by alsm** [comment]
Thanks for reporting back on this.

**Comment by JyotiD21** [comment]
hey,

could you please tell me what is this number '1491371631' in front of log messages?

Thank you

**Comment by ishrikanth** [comment]
Its UNIX epoch time

**Comment by theobouwman** [comment]
I am still having this issue

**Comment by MahlerFive** [comment]
@theobouwman are you running the latest mosquitto (1.4.14)? the bug i encountered was due to a bug in mosquitto before that version

**Comment by theobouwman** [comment]
@MahlerFive 1.4.14_2

**Comment by MahlerFive** [comment]
@theobouwman sounds like it's a different cause for you then

**Comment by axd1967** [comment]
(similar issue with paho Python RabbitMQ when using qos=2)
