### ISSUE TITLE
SUBACK

### ISSUE THREAD

**Issue by otgonbayar999** [eclipse/paho.mqtt.golang#91]
I have connection with broker tcp://iot.eclipse.org:1883, Connect, Subscribe and Publish, 
Disconnect are ok, but the function Result() returning "nil". 

var subackToken  MQTT.SubscribeToken
subackToken.Result() is nil.

i'm new to golang and mqtt, any...?

**Comment by alsm** [comment]
Do you have any more details of your code, I just tested a sub against iot.eclipse.org (both `Subscribe()` and `SubscribeMultiple()`) and I had valid data in the map returned by called `Result()` on the token.

**Comment by otgonbayar999** [comment]
I'm using Qt binding,  w.lineEditResponse widget showing text "11111", i'm can't access map m[topic] there is nothing, 

subackToken  MQTT.SubscribeToken
token := client.Subscribe(topic, qos, msgHandler)
	if token.Wait() && token.Error() != nil {
					os.Exit(1)
	}
	m := make(map[string]byte)
	m = subackToken.Result()
	if m == nil {
		w.lineEditResponse.SetText("11111")
				}

**Comment by alsm** [comment]
you create a var called `subackToken` but it looks like you're assigning the token coming back from `client.Subscribe()` to a var called `token`, then calling `.Result()` on `subackToken`. If that's correct the reason will be because `subackToken` never gets any data so is an empty instance of a SubscribeToken with a nil map for the Results.

**Comment by otgonbayar999** [comment]
Thank you for advice, i cant make any valid instance SubscribeToken, can you send example code. I apologise for the inconvenience.

**Comment by alsm** [comment]
Based on your code above;
```

**Comment by alsm** [comment]
Based on your code above
```
token := client.Subscribe(topic, qos, msgHandler)
if token.Wait() && token.Error() != nil {
os.Exit(1)
}
m := token.(*MQTT.SubscribeToken).Result()
if m == nil {
w.lineEditResponse.SetText("11111")
}
```

**Comment by otgonbayar999** [comment]
Thank you
Ok, done
