### ISSUE TITLE
Panic in net.go under an unstable network condition (occassional)

### ISSUE THREAD

**Issue by pshirali** [eclipse/paho.mqtt.golang#93]
The following panic has been seen to occur occasionally under unstable network conditions.
Commit-hash: d4f545eb108a2d19f9b1a735689dbfb719bc21fb

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x738f6b]
goroutine 21812 [running]:
panic(0x885c40, 0xc4200120b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
<withheld>/vendor/github.com/eclipse/paho%2emqtt%2egolang.alllogic(0xc4201af500)
	/go/src/<withheld>/vendor/github.com/eclipse/paho.mqtt.golang/net.go:254 +0x25ab
created by <withheld>/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/go/src/<withheld>/vendor/github.com/eclipse/paho.mqtt.golang/client.go:232 +0x968
```

Following is the code snippet (net.go):
```
                        case *packets.PubcompPacket:
                                pc := msg.(*packets.PubcompPacket)
                                DEBUG.Println(NET, "received pubcomp, id:", pc.MessageID)
#:254 --->                      c.getToken(pc.MessageID).flowComplete()
                                c.freeID(pc.MessageID)
                        }
```

Could someone throw more light on what conditions could cause this? TIA.

**Comment by alsm** [comment]
It seems we naively assume that if we get a pubcomp packet, then we will find a token for that messageid, and this be able to call flowComplete() on it. I presume that for some reason you are getting a pubcomp and the look fails and passes back a nil value, which the code then immediately calls flowComplete() on which panics.
I can't immediately see an obvious reason for this on the client side, eg; if the connection is lost we don't clear the messageIds struct.

**Comment by jnicholls** [comment]
I too receive this error, but only when running in Unordered mode `Order = false` which runs all message handlers in their own goroutine.

**Comment by jnicholls** [comment]
For what it's worth, adding a `nil` check before calling `flowComplete()` has worked around the issue for me.  There is a synchronization problem somewhere, as I could only make it happen if I had message handlers that spawned goroutines (or if I set `Order = false` in the client options).

**Comment by pshirali** [comment]
Thanks @jnicholls

I'm running `Order = true` (which is default). However, I do spawn goroutines in the handler.

There are multiple cases where a token is fetched, and a `flowComplete()` is called on it. Did you encounter the issue on a PubcompPacket as well?. Also, did you end up putting a `nil` check on all cases where `flowComplete()` is called on a token (as there are many cases).

**Comment by jnicholls** [comment]
When I ran `Order = true` and spawned goroutines in my handlers, I would have the same fault as you showed above.  Only on a PubcompPacket.  That is the only place I added a `nil` check before calling `flowComplete()` and since doing that, I have had no crashes.

My MQTT broker is VerneMQ.  I didn't try QoS 1 rigorously under my same conditions, but I presume it wouldn't be a problem...seems as though only QoS 2 w/ a final PUBCOMP has this condition.  Odd.

**Comment by pshirali** [comment]
@jnicholls, thanks again for your repro info. FYI, I'm running mosquitto as my broker. My traffic has been a mix of all three QoS levels.

@alsm ,

`messageids.go::getToken` is capable of returning a `nil` if it is unable to fetch a token for a given messageId. Hence, any code which does `.getToken(<messageId>).<action>` is susceptible to a `nil pointer dereference`. Do you think we should put a `nil` check before all such cases?

While the `nil` check is still a defensive fix, the root cause is still unknown. Is there a possibility of messageId collision? or any race scenario, where a message with `X` messageId is received and closed (there by cleared from the map), and a message with messageId `X` is again received at a time when there is no corresponding token?

This may be unrelated, but in `net.go::alllogic`, the SUBACK and  UNSUBACK, `c.freeID` runs in a goroutine, while it is synchronous for other packets. Is there a specific reason why it is this way?

**Comment by alsm** [comment]
Thanks to you both for your effort looking into this, it's very frustrating as I can't see a reason why it's happening, and I've been unable to recreate it. If possible would you be able to add a debug line to log the messageID for the message that's failing, I'm wondering if there is a problem with decoding the packet that is being hidden and we're trying to lookup an entry for id 0, which isn't used but would be a valid lookup entry and return a nil value.

**Comment by alsm** [comment]
I'm closing this in the favour of the ongoing discussion in #115
